### PR TITLE
Mapfix Palooza Round 2

### LINKED ISSUE #88: Add trash piles to maintenance
Title. Unlike Northern Star, Southern Cross lacks searchable trash piles in maintenance.

### LINKED ISSUE #122: Air pressure in disposals.
Because of the lack of airtight plastic flaps in cargo's mailroom, the room can get overpressurized by people throwing things away multiple things in quick succession. Just add some in front of the disposal outlet, and it shouuuuld fix it. Maybe.

How to reproduce: Throw things away in the trashcans a bunch. A lot.

Watch pressure in mailroom rise.

### LINKED ISSUE #130: Make resleeving more private
#### Brief overview of the feature
The resleeving room is... very unusually open and visible to the public, which is pretty counter-intuitive to anyone in Medical wanting to have scenes with freshly-resleeved crew (ESPECIALLY in regards to vore) as well as the general policy of the station in general. The current layout is counterintuitive from a patient privacy perspective: you'd realistically probably want to have the resleeving process be fairly discreet since it has the potential to be so personally impactful for someone, or at LEAST not have the majority of the room _actively visible to non-medical personnel from the medbay lobby._

#### What you want to happen
Close the room off more with actual doors where the emergency shutters to the left currently are, and change the windows to polychromatic ones that can be blacked out. This way, patients can have the privacy and respect they deserve when being resleeved... 
...and hungry medical personnel have a much easier time toying with their vulnerable victims, opening up the potential for a lot of fun teasing.
 
#### Anything else you may wish to add:
The resleeving room as it is, and proof that most of it can be seen from the lobby.
image
image

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Here we have it, folks. Enjoy reading through the long list of changes involved.

Changelog Notes:

- Main Outpost tweaks.

- - Sensor console moved behind Med Staff Only windoor, expands it one metre to the west.

- - Disposals tweaked near Main Outpost Teleporter. No going under walls!

- - Scales added to Sif Gym.

- - Sauna section extension to Sif Pool.

- - Belt Miner Shuttlebay atmos pipe fix.

- - Tweaks all tiles in Belter Hangar Bay to be standard tiled floor turfs, except under the doors.

- - Pipe/cable adjustments so they don't go underneath walls.

- Station and surface Sif Xenobio tweaks.

- - Cameras added with new network as per work from old Chompcode. Console and board included.

- - Removes windows from the tables.

- - Disposals changed for easier monkey release.

- - Buttons moved and tables deleted, latter replaced with secondary window shield.

- - Cameras shifted per no doubling up with lights standard.

- - Folders and pens moved for the camera console.

- Xenoarch FA station access restrictions removed. Also shifts disposal under wall near north entrance.

- Cryopod now has 2 sets of fans to prevent venting inside and outside the cryopod.

- Last light constructs replaced with light frames.

- Medical tweaks.

- - Expand Emergency Treatment Centre and gives 2 sleepers.

- - Expand Resleeving Room into primary Genetics Lab and replaces it. Hallway and OR/recovery sectors moved southward as a result. Resolves #130.

- - Break Room addition.

- - TransCore Packet in CMO Locker.

- - Move NIFSoft disk box into main gear storage with all the medkits.

- - Two new Patient Rooms to fill the increased space. Gives all public access and bolt hatch switches for scene purposes. Also fix tinting of external windows for original two patient rooms.

- - Adjusts maints to the southwest access and shifts it southwards several tiles, more maint items added.

- - Shifts Medbay Restrooms and removes tables and vendors in the hallway. Vendors put into new break room.

- - MD roundstart spawnpoints in lobby shifted to new break room.

- - Pill bottle boxes added in Chemistry/ETC.

- - Reception made smaller, equipment moved as deemed appropriate.

- - Slight movement of psych couch against the wall.

- - Rotate Exam Room horizontally, adjust items and equipment as needed.

- Cargo tweaks.

- - Move Mining Redemption Vendor into station's Mining Locker Room. Remove one miner's equipment locker.

- - Delivery Room fitted with airtight flaps for the conveyor lines. Resolves #122 

- - Unused scrubber pipes removed.

- - Room's made bigger and removes a maint room to make more space for the pipe systems.

- Trash piles added to maints, replaces other varieties previously mapped in. Resolves #88 

- Missed Shield Diffuser for a space-side vent.

- Also fixing Drone Fab's EVA so shields don't block exit.

- Coffee Shop now has another spawnpoint landmark for Baristas.

- All monitors changed to be offset to walls, not mapped in to be _ON_ the tile of said wall.

- Pipeworks and wiring adjusted to not go under walls as well. Also tweaks the former so that vents/scrubbers aren't placed in a clunky way on top of other pipes.

- - Station-side gym now has a mail tag disposal.

- - Reworks disposals to loop from deck 2 to 1 or 3, depending on locations.

- - As a result of the above, turns a room into an emergency storage room and uses Central Substation area for disposal loop to third deck.

- - Deck 2 Port Pressure Regulator fixed. Flipped directions to go outwards, not back to atmos which is backwards.  Also switches its placement with the shutoff valve for correct layout.

- - Research Maint's EVA Hallway's EVA pipes no longer run underneath window and rack. 

- Shifts holopad in red armoury underneath the table.

- Shifts T-comms subgrid to take from Master grid, not Central. Adjusts Pilot room to be on Master as well.

- Fixes Science Substation to not start with 75% full power.

- Crematorium in Chapel Morgue.

- ColourMate added to Locker Room.

- Replace two emitters with Thermal Regulators in Hard Storage.

- Deck 1 Escape Pods made into full hallways on southern end.

- Invert railings and windows for drop-nom balconies. Switches reinforced for weaker glass for quicker smashing.

- Missing air alarm for Sec Maint Port.

- Several walls adjusted for r_wall or standard as deemed appropriate.

- Leftover red firelocks deleted.

- Replace Station and Sif Gym wooden flooring with actual wooden flooring, not holofloor.

- Move Deck 1 lift timeclock to the west.

- Give Bridge its own disposal bin to chuck things away in.

- Fix missing Shuttle 1 Exterior Sensor. Var was duped with Shuttle 3's.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
This PR is more inflated than I am.

**Comment by TheFurryFeline** [comment]
https://travis-ci.com/CHOMPStation2/CHOMPStation2/jobs/284426637#L523 I'll get this when I'm back from my appointment. As for the active edges, that's happening on the belter z-level and was not touched by me.

**Comment by TheFurryFeline** [comment]
That's fixed those, at least. Gotta love when these don't show up in test environments or DM but it's Travis that screeches like hell.

**Comment by D-H-A** [comment]
This is what I found thus far via glancing. I haven’t bothered checking the technical stuff like if the cameras are tagged correctly, but moving on:

### southern_cross-1.dmm (z-level  1)

- Piping and wiring looks fixed for the most part. It’s way better than whatever it was going for before.
- I don’t really think the gym benefits or suffers from having the same floor as the bar.
- Trash piles are placed appropriately by the looks of it.
- I’m neutral about the deletion of another row of vents from the airlocks, because I’m not too fond of piping going through the wall like it had neither. Only complaint is try to make them attach to one pipe closer to the vents in a couple of them, like the others.
- In the gym, there is both a disposal and an APC unit on top of each other. It’ll be better to maybe replace the disposal right across from the vendor nearby it.
- Removal of the AI status near the north escape shuttles was unnecessary.
- One of the disposal shoots in xenobio is going to slam a monkey into a wall at point blank. (It’s facing into a wall.) It may be also better to put them back away from the windows like it was before as it keeps all the slimes away from the windows whenever a monkey shoots out.
- I really rather not have those tables replaced with thick windows, and those buttons replaced on a wall behind tanks. (In xenobio) Keep the camera system, I assume you tested it. I also rather not have the symmetry of the vents position ruined in xenobio too, compared to what they were before. Try moving the paper bin and pens to that blank space ontop of that table to the right. It’s better than hoarding it all with a bunch of items in one place.
- The vent placement and its symmetry in xenoflora should be what it was before.
- Those doors replacing the windows near the south bottom docks may actually be better, but try to remove the decals around them and reconstruct it like it is around the other doors in the map.
- Not sure why there’s four different status screens near each other outside of tech storage now.
- Trash piping (for other z-levels too) is getting a bit ridiculous. If you want to make more disposal units in areas without them, that’s fine, what’s not fine is two disposal pipes traveling down side-by-side one another for a long ways when they could have been connected a lot sooner into one. 


### southern_cross-1.dmm (z-level 2)

- This medical looks like it’s for long bois. There’s not really much space to the side of the sleepers too. It honestly looks like you just stretched it out in a few places. There’s not much of a benefit to extra space in medical if it’s pinched. The extra space in other rooms are a bit un-needed.
- I’m more in favor of the extra-power-security of which the comms and teleporter had via being through two SMEs across z-levels, compared to what it was changed to now.
- You didn’t move the Mining Redemption Vendor, you added another one. It’s fine where it is anyhow for now, even if it isn't the best.

### southern_cross-3.dmm

**_I’m going to go ahead and tell you that the outpost may be replaced completely rather soon-ish._** I wouldn’t waste too much time on it. You might end up changing something that will be overwritten completely.

- In the dorm room, the yellow one, you missed a spray vent under the table.
- Piping looks mostly fixed.
- Medical is too cramped via a one tile narrow space up to the sleeper
- Mostly the same things for xenobio as was on station, but I really wouldn’t bother with it in the first place as the planetside is abandoned and xenobio on station.
- The sauna looks out of place.

### southern_cross-4.dmm

- Piping looks mostly fixed but air alarms on windows is a sin.
- You accidentally deleted a hazard tape decal near the door up north.

**Comment by D-H-A** [comment]
### Suggestions on what to do in the future

**I’m going to _HIGHLY_ suggest** doing things one at a time unless warranted in the future from now on as this is a bit much to review all at once, and it may prove to be faster to get fixes in, when checked (or corrected) compared to waiting for everything in a change this size. I say unless warranted because in certain situations it may be unavoidable (Like a completely new area, or revamp of an area), but in this case it can be. For example, you can maybe do xenobio on its own, combined with the camera network, and then do the pipes in another change put forward, and so on. I also plan on cutting up the z-levels into separate map files sometime in the future so more than one person can work on the station without conflicts so long as they fit together across z-levels, and the changes remain separate across different map files. -plus, mapdiff bot. (It’s mostly mapdiff bot) Until then, anything you’re wanting to do like this, others might feel the need to wait; Hence another reason why I suggest presenting smaller changes. 

I also suggest maybe copying a map file and renamed it something else (like southern_cross-3 – Copy) within the same folder, and ignoring it (from github) and putting the changes there while keeping your files updated, and then copy/pasting your changes over when you’re ready, so you don’t have to wait on the map being updated, or updating yours. You can copy/paste over changes fewer at a time one after the other. You don’t have to do this last suggestion, and I’m sure others have his or her own way of handling it.

**Here are some additional things I would like to see done, along with the piping fixed. Anyone is free to do these:**

- You see those slimes in xenobio? Replace them with grey lifeless cores. Sometimes when we get early wormholes, they nope off station or into other areas, leaving xenobio sometimes impossible. They can be made into living grey slimes via the phoron already sitting around.
- Put a nanopaste tube in the surgery rooms somewhere for those synthetic organ surgeries.

**Comment by TheFurryFeline** [comment]
> * I’m neutral about the deletion of another row of vents from the airlocks, because I’m not too fond of piping going through the wall like it had neither. Only complaint is try to make them attach to one pipe closer to the vents in a couple of them, like the others.
Can do the pipe changes easily. Single manifolds leading into them and the vents on a opposite corner basis?
> * In the gym, there is both a disposal and an APC unit on top of each other. It’ll be better to maybe replace the disposal right across from the vendor nearby it.
Will do.
> * Removal of the AI status near the north escape shuttles was unnecessary.
I thought I covered all those and just added properly offset'd AI status displays. I'll check again.
> * One of the disposal shoots in xenobio is going to slam a monkey into a wall at point blank. (It’s facing into a wall.) It may be also better to put them back away from the windows like it was before as it keeps all the slimes away from the windows whenever a monkey shoots out.
Grey cores rather than live slimes? Sounds good to me. Virgo does that as well though they admittedly don't have the wormholes event. As for the ejection, either way the monkey still ends up being at the far wall? Thought I also had all the outlets done, will check.
> * I really rather not have those tables replaced with thick windows, and those buttons replaced on a wall behind tanks. (In xenobio) Keep the camera system, I assume you tested it. I also rather not have the symmetry of the vents position ruined in xenobio too, compared to what they were before. Try moving the paper bin and pens to that blank space ontop of that table to the right. It’s better than hoarding it all with a bunch of items in one place.
Revert the tables removal and such with the windows? I don't really like the buttons being on the tables themselves like slap in the centre of them. At least on the walls they look a bit better. However, granted, with the water tanks in the way, I can see the issue. What'cha think about moving the tanks elsewhere? As for the vent placements, I'll do that stuff and the paper bin, pens, and folders will also be shifted to be more spread out.
> * The vent placement and its symmetry in xenoflora should be what it was before.
Will do.
> * Those doors replacing the windows near the south bottom docks may actually be better, but try to remove the decals around them and reconstruct it like it is around the other doors in the map.
Will do.
> * Not sure why there’s four different status screens near each other outside of tech storage now.
Damn, whoops. Will check that out.
> * Trash piping (for other z-levels too) is getting a bit ridiculous. If you want to make more disposal units in areas without them, that’s fine, what’s not fine is two disposal pipes traveling down side-by-side one another for a long ways when they could have been connected a lot sooner into one.
Ah, I see where I went wrong for the hangar 2 and 3. However, uhhhh, it's better this way rather than have the sort junctions be closer to the central part of deck 1. Otherwise, it'd be 3 whole lines of disposals: 2 SortJunctions leading out from the main loop in 2 lines, and a third for the disposal unit at the lift if it's done to, as said, go out from the main loop. Having the loop extend out this way and then double back west is better, imo. If this wasn't what you meant, please clarify.
> ### southern_cross-1.dmm (z-level 2)
> * This medical looks like it’s for long bois. There’s not really much space to the side of the sleepers too. It honestly looks like you just stretched it out in a few places. There’s not much of a benefit to extra space in medical if it’s pinched. The extra space in other rooms are a bit un-needed.
I'll look into making the new patient rooms/new ETC/exam room be more filled or smaller. Not sure how, though, without.... Hang on... This whole thing was mostly done to accommodate for a bigger room that Resleeving would get, as well as some privacy for it. There... Just might be a way to do it regardless but it would require the southeast corner still be shifted. More like the.... No, I can't really think of a better way to make the resleeving room get some privacy with the space prior to this renovation.
> * I’m more in favor of the extra-power-security of which the comms and teleporter had via being through two SMEs across z-levels, compared to what it was changed to now.
Hang on, you want T-comms subgrid to take from Central subgrid again? It drains out Central grid faster that way, IIRC.
> * You didn’t move the Mining Redemption Vendor, you added another one. It’s fine where it is anyhow for now, even if it isn't the best.
A'ight, I'll remove the new one. Thought I deleted the old one, though, whoops.
> 
> ### southern_cross-3.dmm
> **_I’m going to go ahead and tell you that the outpost may be replaced completely rather soon-ish._** I wouldn’t waste too much time on it. You might end up changing something that will be overwritten completely.
> 
> * In the dorm room, the yellow one, you missed a spray vent under the table.
D'oh. Will fix.
> * Medical is too cramped via a one tile narrow space up to the sleeper
Will check this out. Likely requires slight expansion of the room to the east.
> * Mostly the same things for xenobio as was on station, but I really wouldn’t bother with it in the first place as the planetside is abandoned and xenobio on station.
My thinking about changing Sif Xenobio was that it'd be more usable this way if any explorers manage to bring back any live specimens that are deemed too dangerous to be taken up to the main station.
> * The sauna looks out of place.
Hmm, should it be moved to the station? Oh, hang on, I could shift it southwards as a more proper expansion, keep it looking nice with symmetry, as ya said previously.
> 
> ### southern_cross-4.dmm
> * Piping looks mostly fixed but air alarms on windows is a sin.
Damn, I didn't even notice that air alarm thing. Thanks, will fix.
> * You accidentally deleted a hazard tape decal near the door up north.
Whoopsie. Re-adding.


>I also plan on cutting up the z-levels into separate map files sometime in the future so more than one person can work on the station without conflicts so long as they fit together across z-levels, and the changes remain separate across different map files. -plus, mapdiff bot. (It’s mostly mapdiff bot) Until then, anything you’re wanting to do like this, others might feel the need to wait; Hence another reason why I suggest presenting smaller changes.
Yes, thank you so much for the z-level thing. MapDiffBot screws itself over because it's 3 z-levels on one map file that Polaris had the bright idea to do. As a note, you'll want to rename all the other .dmm files to be 4-11 from 2-9 respectively for each case after ya add two new ones for 2 and 3.
> 
> I also suggest maybe copying a map file and renamed it something else (like southern_cross-3 – Copy) within the same folder, and ignoring it (from github) and putting the changes there while keeping your files updated, and then copy/pasting your changes over when you’re ready, so you don’t have to wait on the map being updated, or updating yours. You can copy/paste over changes fewer at a time one after the other after the last is either accepted or rejected. You don’t have to do this last suggestion, and I’m sure others have his or her own way of handling it.
This is pretty useful advice.... Fantastic and I'll see about doing that in the future.
> 
> **Here are some additional things I would like to see done, along with the piping fixed. Anyone is free to do these:**
> 
> * You see those slimes in xenobio? Replace them with grey lifeless cores. Sometimes when we get early wormholes, they nope off station or into other areas, leaving xenobio sometimes impossible. They can be made into living grey slimes via the phoron already sitting around.
Dealing with it as stated above. As for the wormholes event, that has not be re-implemented yet.
> * Put a nanopaste tube in the surgery rooms somewhere for those synthetic organ surgeries.
Easy addition. One for each?

**Comment by TheFurryFeline** [comment]
> > * I’m neutral about the deletion of another row of vents from the airlocks, because I’m not too fond of piping going through the wall like it had neither. Only complaint is try to make them attach to one pipe closer to the vents in a couple of them, like the others.
> 
> Can do the pipe changes easily. Single manifolds leading into them and the vents on a opposite corner basis?
 
Airlock vent pipeworks tweaked as requested. 

> > * In the gym, there is both a disposal and an APC unit on top of each other. It’ll be better to maybe replace the disposal right across from the vendor nearby it.
> 
> Will do.

Removing sortjunction towards the gym and putting a regular junction in going westwards per the loop direction. Disposal bin moved outside gym and put near the SweatMax vendor.
Gym_Disposal_Moved_Out

 
> > * Removal of the AI status near the north escape shuttles was unnecessary.
> 
> I thought I covered all those and just added properly offset'd AI status displays. I'll check again.

It wasn't removed, it was moved over to the side.
AI_Status_Here


> > * One of the disposal shoots in xenobio is going to slam a monkey into a wall at point blank. (It’s facing into a wall.) It may be also better to put them back away from the windows like it was before as it keeps all the slimes away from the windows whenever a monkey shoots out.
 
> Grey cores rather than live slimes? Sounds good to me. Virgo does that as well though they admittedly don't have the wormholes event. As for the ejection, either way the monkey still ends up being at the far wall? Thought I also had all the outlets done, will check.

Slimes replaced with extracts. 
Slimes_Replaced_With_Extracts


> > * I really rather not have those tables replaced with thick windows, and those buttons replaced on a wall behind tanks. (In xenobio) Keep the camera system, I assume you tested it. I also rather not have the symmetry of the vents position ruined in xenobio too, compared to what they were before. Try moving the paper bin and pens to that blank space ontop of that table to the right. It’s better than hoarding it all with a bunch of items in one place.
> 
> Revert the tables removal and such with the windows? I don't really like the buttons being on the tables themselves like slap in the centre of them. At least on the walls they look a bit better. However, granted, with the water tanks in the way, I can see the issue. What'cha think about moving the tanks elsewhere? As for the vent placements, I'll do that stuff and the paper bin, pens, and folders will also be shifted to be more spread out.

Vent Symmetry Restored, Pens, folders, and paper bin shifted. Also fixed the disposal outlet direction.
Xenobio_Fixes


> > * The vent placement and its symmetry in xenoflora should be what it was before.
> 
> Will do.

Done
Vent_Symmetry_Restored

 
> > * Those doors replacing the windows near the south bottom docks may actually be better, but try to remove the decals around them and reconstruct it like it is around the other doors in the map.
> 
> Will do.

Removed decals in front of the doors, but added a bit more to the sides.
Decals_Removed_and_Adjusted2
Decals_Removed_and_Adjusted1


> 
> > * Not sure why there’s four different status screens near each other outside of tech storage now.
> 
> Damn, whoops. Will check that out.

AI and Status displays are in 2 pairs: one inside Tech Storage. The other being outside of it. No issue.

> > * Trash piping (for other z-levels too) is getting a bit ridiculous. If you want to make more disposal units in areas without them, that’s fine, what’s not fine is two disposal pipes traveling down side-by-side one another for a long ways when they could have been connected a lot sooner into one.
> 
> Ah, I see where I went wrong for the hangar 2 and 3. However, uhhhh, it's better this way rather than have the sort junctions be closer to the central part of deck 1. Otherwise, it'd be 3 whole lines of disposals: 2 SortJunctions leading out from the main loop in 2 lines, and a third for the disposal unit at the lift if it's done to, as said, go out from the main loop. Having the loop extend out this way and then double back west is better, imo. If this wasn't what you meant, please clarify.
> 
> > ### southern_cross-1.dmm (z-level 2)
> > 
> > * This medical looks like it’s for long bois. There’s not really much space to the side of the sleepers too. It honestly looks like you just stretched it out in a few places. There’s not much of a benefit to extra space in medical if it’s pinched. The extra space in other rooms are a bit un-needed.
> 
> I'll look into making the new patient rooms/new ETC/exam room be more filled or smaller. Not sure how, though, without.... Hang on... This whole thing was mostly done to accommodate for a bigger room that Resleeving would get, as well as some privacy for it. There... Just might be a way to do it regardless but it would require the southeast corner still be shifted. More like the.... No, I can't really think of a better way to make the resleeving room get some privacy with the space prior to this renovation.

Emergency Treatment Centre changed up aloing with the patient rooms that are nearby. 
ETC_Expansion_Fix
Not real sure on what else ya want for the other rooms.
 
> > * I’m more in favor of the extra-power-security of which the comms and teleporter had via being through two SMEs across z-levels, compared to what it was changed to now.
> 
> Hang on, you want T-comms subgrid to take from Central subgrid again? It drains out Central grid faster that way, IIRC.
> 
> > * You didn’t move the Mining Redemption Vendor, you added another one. It’s fine where it is anyhow for now, even if it isn't the best.
> 
> A'ight, I'll remove the new one. Thought I deleted the old one, though, whoops.

Removed Redemption Machine, re-added locker.

> > ### southern_cross-3.dmm
> > **_I’m going to go ahead and tell you that the outpost may be replaced completely rather soon-ish._** I wouldn’t waste too much time on it. You might end up changing something that will be overwritten completely.
> > 
> > * In the dorm room, the yellow one, you missed a spray vent under the table.
> 
> D'oh. Will fix.

Fixed. 
 
> > * Medical is too cramped via a one tile narrow space up to the sleeper
> 
> Will check this out. Likely requires slight expansion of the room to the east.

Fixed with 
Minor_Expansion_for_FA_Station2
Minor_Expansion_for_FA_Station1


> 
> > * Mostly the same things for xenobio as was on station, but I really wouldn’t bother with it in the first place as the planetside is abandoned and xenobio on station.
> 
> My thinking about changing Sif Xenobio was that it'd be more usable this way if any explorers manage to bring back any live specimens that are deemed too dangerous to be taken up to the main station.
> 
> > * The sauna looks out of place.
> 
> Hmm, should it be moved to the station? Oh, hang on, I could shift it southwards as a more proper expansion, keep it looking nice with symmetry, as ya said previously.
> 

Fixed with 
Sauna_Moved


> > ### southern_cross-4.dmm
> > 
> > * Piping looks mostly fixed but air alarms on windows is a sin.
> 
> Damn, I didn't even notice that air alarm thing. Thanks, will fix.


Fixed with 
Xenoarch_Air_Alarm_Fix

> 
> > * You accidentally deleted a hazard tape decal near the door up north.
> 
> Whoopsie. Re-adding.

Hang on... Which hazard tape do ya mean? Checking with mapeditor and live server but I don't see what got deleted?
> 
> > I also plan on cutting up the z-levels into separate map files sometime in the future so more than one person can work on the station without conflicts so long as they fit together across z-levels, and the changes remain separate across different map files. -plus, mapdiff bot. (It’s mostly mapdiff bot) Until then, anything you’re wanting to do like this, others might feel the need to wait; Hence another reason why I suggest presenting smaller changes.
> 
> Yes, thank you so much for the z-level thing. MapDiffBot screws itself over because it's 3 z-levels on one map file that Polaris had the bright idea to do. As a note, you'll want to rename all the other .dmm files to be 4-11 from 2-9 respectively for each case after ya add two new ones for 2 and 3.
> 
> > I also suggest maybe copying a map file and renamed it something else (like southern_cross-3 – Copy) within the same folder, and ignoring it (from github) and putting the changes there while keeping your files updated, and then copy/pasting your changes over when you’re ready, so you don’t have to wait on the map being updated, or updating yours. You can copy/paste over changes fewer at a time one after the other after the last is either accepted or rejected. You don’t have to do this last suggestion, and I’m sure others have his or her own way of handling it.
> 
> This is pretty useful advice.... Fantastic and I'll see about doing that in the future.
> 
> > **Here are some additional things I would like to see done, along with the piping fixed. Anyone is free to do these:**
> > 
> > * You see those slimes in xenobio? Replace them with grey lifeless cores. Sometimes when we get early wormholes, they nope off station or into other areas, leaving xenobio sometimes impossible. They can be made into living grey slimes via the phoron already sitting around.
> 
> Dealing with it as stated above. As for the wormholes event, that has not be re-implemented yet.
> 
> > * Put a nanopaste tube in the surgery rooms somewhere for those synthetic organ surgeries.
> 
> Easy addition. One for each?

Added.

**Comment by Darlantanis** [comment]
While this is up, please remove the stunstaff from the armory. This is a misleading virgo fluff item which never should have been added to Northern Star. A properly-made variant can be added to the game later (preferably through a _ch file).

**Comment by TheFurryFeline** [comment]
> While this is up, please remove the stunstaff from the armory. This is a misleading virgo fluff item which never should have been added to Northern Star. A properly-made variant can be added to the game later (preferably through a _ch file).

I'll do this as soon as I can. It's been a busy weekend and I haven't had the time to get on my laptop. Also still waiting on further review from DHA.

**Comment by D-H-A** [comment]
### **southern_cross-1.dmm (Medical)**

- The uniform vendor is missing.
- The bioprinter is missing.
- The IVs are too far away from the blood vendor.
- Patient Room D’s area bleeds into other rooms.
- Patient Room C’s area bleeds into other rooms.
- NanoMed Plus vendor in the equipment room was more accessible in the wall (despite it not being the best place for it)
- Patient rooms C and D’s buttons look like they’re on the outside of the room.
- Patient rooms C and D’s buttons look misaligned.
- Patient rooms C and D’s steel decals hanging around the doors are wonky.
- You forgot the light switch when you moved the APC in the medical bay hallway. It’s also still where it was before.
- There’s still some stray area “Medbay Reception” south of the Exam room.
- The lockdown shutters in maintenance doesn’t connect to a wall up north from its row.
- The exam room is still too wide.
- The space outside Patient rooms C and D looks vacant.

-And I sort of stopped there at medical, (there’s a lot more) and decided to do this a better way. We’ll be here all month or longer otherwise –over a type of file that will conflict or overwrite should someone else change something sooner or later no less. Plus some things are still left unchanged as per requested. I’m going to close this, and suggest any changes from here that you want to help with the server be separated between departments, concepts (again, piping is a good example), or unless it’s a new area or building –which should be solely focused on them as well. This is something I suggest for everyone unless they make an exception. It’s about as ridiculous as if I was to change half the code files all at once for various different things and go “Here, check everything”. This just doesn’t work out compared to how we could be doing it.

**Pull request closed without merging**
