### PR TITLE
Shadekin Retreat Changes and Sprite Support for TGMC Angled Doors

### PR DESCRIPTION
**Pull request by FoxglovePurpur**
## About The Pull Request
Adds a locked and opened door sprite to the TGMC angled doors. This PR does not touch the TGMC vault doors. This PR also adds a door lock to the Shadekin Dorms. And finally it fixes and updates all tags and id_tags on said doors.

## Changelog
Adds locks and fixes the dorm rooms in the Shadekin Retreat. Also adds sprites for angled TGMC doors.

:cl:
qol: Adds the ability to lock the Shadekin Dorm Rooms
imageadd: Adds locked open door sprites to TGMC Angled doors.
/:cl:

### CODE REVIEW

**Comment by FoxglovePurpur** [comment]
Tested this on my own private instance. The only "bug" is the thing I have listed as a "quick note".
Less of a bug, more of just, a missing sprite. I should have that ready tomorrow.

**Comment by Raeschen** [comment]
> Tested this on my own private instance. The only "bug" is the thing I have listed as a "quick note". Less of a bug, more of just, a missing sprite. I should have that ready tomorrow.

waiting for that, then.

**Comment by FoxglovePurpur** [comment]
That's fine then. It seems this is an "issue" with all tgmc doors. None of them have "bolted open" sprites. 
For now I'll start with just the door used here. I'll reply again once I've got that done and just push to this branch so it's all in one PR.

I'll also remind myself in this comment to update the CL when I do that.

**Comment by FoxglovePurpur** [comment]
There we go, I tested it and this should work for all TGMC doors that are outside of the vault folder. I haven't added the TGMC/vault sprites because, well- we already don't use TGMC doors that often anyways. However, all doors outside of that subfolder have a new sprite that are applicable. And the code that allows that icon change to happen.

**Pull request merged**
