### PR TITLE
Making tesh medium size

### PR DESCRIPTION
**Pull request by Sharkmare**
There is no reason for tesh to be small sized nobs

### CODE REVIEW

**Comment by Sharkmare** [comment]
This makes them able to use combat mechanics like pushing people down-

Yknow like all other species

**Comment by LunarFleet** [comment]
Finally, tesh drumsticks can squeeze around my head and-

**Comment by Sharkmare** [comment]
Oh yeah also this isnt so much our addition as a revert of a YW change

**Comment by Razgriz1032** [comment]
But you can't pick up tesh anymore afaik :pepehands:

**Comment by LunarFleet** [comment]
Gimmie a day or so

**Comment by Darlantanis** [comment]
If this matches upstream now might as well remove the comments (YW comment included). No point in the comments causing conflicts later if the code is identical.

**Comment by KasparoVy** [comment]
> 
> 
> But you can't pick up tesh anymore afaik :pepehands:

Aww, RIP!

**Comment by Darlantanis** [comment]
If you decide to continue work on this, teshari have been moved from station_vr.dm to teshari_vr.dm in #1698

**Comment by Razgriz1032** [comment]
Closing because old

**Pull request closed without merging**
