### PR TITLE
Map Adjustments. Merging Surface Base Main Structure

### PR DESCRIPTION
**Pull request by Enzo-Leon**
Updates the surface base to connect the main building with the southern building of the Pool with hallways, and adds a small lounge nearby that has frosted windows for privacy. Also fixed the pool temp to no longer be 243 Kelvin and is now 293 along with the rest of the facility.

### CODE REVIEW

**Comment by Enzo-Leon** [comment]
Hello,

Is there any updates to a ETA on this getting merged, or any feedback or questions regarding the PR that is holding it up on getting eyes on?

**Comment by Kazzc** [comment]
Sorry for taking so long on reviewing this.
I see no point in adding such long winding hallways, even more as it just encroaches areas.
With your permission, I will like to work on this design and garnish some of its redundant design.
I do agree that the pool and sauna are cut-off and should have easier access. But simply. . . I suggest this.

image

-Blue-Block: Build a hallway, you can section a small area with a table, chairs, and trashcan.
-Black-Block: Move the abandoned room behind the ATV storage, and turn it into a mechanic's bay.
-Red Block: Move the air-lock system and all of the winter gear to the red arrow.

**Comment by Enzo-Leon** [comment]
Heyo!

Read over and I like the ideas on this. I'll get the adjustments handles and submit a screenshot of the changes here later this week =3

**Comment by VictorZisthus** [comment]
Willing to help with this if ya need! 💛

**Comment by Darlantanis** [comment]
Considering it's been over a year now...

**Pull request closed without merging**
