### PR TITLE
Alt Version Of Deep Wilds POIs

### PR DESCRIPTION
**Pull request by FluffMedic**
Adds some alternate versions of some Deep Wilds POIs. Whether some mobs are swaped out, locations swapped, terrain altered, intended path changed, etc.

### CODE REVIEW

**Comment by KeRSedChaplain** [comment]
won't this mean multiple of the same PoI would spawn

**Comment by FluffMedic** [comment]
No

**Comment by FluffMedic** [comment]
There is a variable that puts POIs in a group and only one of those group can spawn.
Examples
-The radio shacks
-Blueshuttle down and blackshuttle down

**Comment by Kazzc** [comment]
Good stuff! Can always use more POI's!

**Pull request merged**
