### PR TITLE
[Integrated Circuits] Adds new assembly

### PR DESCRIPTION
**Pull request by xnqm8h**
Adds a new assembly to the printer that comes with a built-in reagent storage tank. It's capacity is 600u. It's medium sized so can't hold a ton of other components to make up for the large built-in container. Should help with some projects.

Uses a more generic icon for the assembly. It'd be nice to get a custom one to show off the tank.

### CODE REVIEW

**Comment by Higgs1** [comment]
I hleped :3

**Comment by Raeschen** [comment]
Changes to upstream files need to either be //Chomp EDIT commented (per line or as a START - END block), put in a  _ch.dm file or put in modular_chomp/ dir

**Review by Raeschen — CHANGES_REQUESTED** [review]
You edited upstream files with no //ChompEDIT comments.
Please add ChompEDIT comments on changed lines in upstream-sensitive files, or as a block of ChompEDIT START - ChompEDIT END around your code in said files.

**Comment by Raeschen** [comment]
Closing due to no response. Feel free to reopen if you still want to work on this.

**Comment by xnqm8h** [comment]
Will reopen this in a minute if I can figure out how to. My windows boot drive stopped booting so it's been difficult getting to this.

**Comment by xnqm8h** [comment]
Ah, someone with permission will need to reopen it. Unless you want me to create a new PR.

**Pull request closed without merging**
