### PR TITLE
Backports some event mobs from Torchstation

### PR DESCRIPTION
**Pull request by SilencedMP5A5**
a handful of syndicate themed mobs i made exclusively for an event. Wanted to share. <3

🆑
+ Syndicate oties with a scary pounce attack
+ Syndicate dire doggos
+ A handful of syndicate taurshapes with some variants and different weapons
/:cl:

### CODE REVIEW

**Comment by SilencedMP5A5** [comment]
image
(the event in question)
image
as well as the shapes in question!

**Comment by SilencedMP5A5** [comment]
oh bruh apparently i pushed the separate PR i was trying to make onto this

**Comment by SilencedMP5A5** [comment]
i am still learning have mercy :')

**Comment by Raeschen** [comment]
whats with the order changes in the .dme of unrelated files

**Comment by SilencedMP5A5** [comment]
not sure how that happened, lemme scoot 'em back to where they were

**Comment by Raeschen** [comment]
> not sure how that happened, lemme scoot 'em back to where they were

it might actually be showing us something that's wrong in our codebase unrelated to you, weirdly. Order IS fairly important and seeing it jiggle files around that shouldn't be jiggled can mean several things. Generally best to only touch what you need to touch :)

**Pull request merged**
