### PR TITLE
BUFFIN' PILLS!

### PR DESCRIPTION
**Pull request by VictorZisthus**
Buffs pills to count as Survival Food, allowing them to be eaten through most masks and hardsuit helmets.

Or, in other words...

GRABBING PILLS!

Better grab everything I can!

[Laughter]

https://youtu.be/wOBNrAtIhRo

### CODE REVIEW

**Comment by VictorZisthus** [comment]
Oh GREAT. This wasn't the simple fix I thought it was.

Thiiiis is gonna take awhile...

**Comment by CMDRYouth** [comment]
This will be helpful for all those times where you just want to eat your healing meds in space or breached areas.
Hopefully it doesn't make people in hardsuits _too powerful_ though.  Would be quite silly for someone in a Breacher to just pop a few pills and then solo an entire threat, all while having their full armor and protection.

**Comment by VictorZisthus** [comment]
> This will be helpful for all those times where you just want to eat your healing meds in space or breached areas. Hopefully it doesn't make people in hardsuits _too powerful_ though. Would be quite silly for someone in a Breacher to just pop a few pills and then solo an entire threat, all while having their full armor and protection.

It's just a little QoL. You'll still have to fumble around with the pill bottles. If you do that in combat you're already asking for an electrode or stun baton up your rear without the ability to retaliate.

**Comment by Razgriz1032** [comment]
For the pills PR, Nadyr and I say no because instead of a bottle of 60 u, you can hold a pill bottle full of 60 u pills in the same space and also have the chem effect last twice as long because reagent subsystem.

So a bottle vs a pill bottle is the same storage space. Therefore, for the price of the same amount of storage space in a backpack, you get 14x the amount of reagents.

But on top of that, since the effects last twice as long, you technically get 28x the amount of chems.


Closing this PR. It's too strong for the tradeoff intended by the sealed nature of the suits.

**Comment by VictorZisthus** [comment]
https://www.youtube.com/watch?v=4BySyQ1pu0U

**Pull request closed without merging**
