### PR TITLE
Egg

### PR DESCRIPTION
**Pull request by TheFurryFeline**
:egg:

### CODE REVIEW

**Comment by Razgriz1032** [comment]
The pathing convention for the medals is bad. People with multiple medals would be a mess.
Instead of
/datum/gear/fluff/medalofsilvervalornadyr

Why not
/datum/gear/fluff/nadyr/medal1
/datum/gear/fluff/nadyr/medal2

And I'm serious about just calling it medal1 and medal2. You don't need the name of the medal in the path.

**Comment by Razgriz1032** [comment]
1. You did the opposite of what I said and by leading with the name of the medal instead of leading with a character name.
2. Your file comment says alphabetized by character name when you alphabetized by medal.
3. You should instead alphabetize by ckey because the ckey represents the individual and one individual may have multiple characters. That's  how it was organized before, and that's  just basic database common sense.

**Comment by TheFurryFeline** [comment]
> 1. You did the opposite of what I said and by leading with the name of the medal instead of leading with a character name.
> 2. Your file comment says alphabetized by character name when you alphabetized by medal.
> 3. You should instead alphabetize by ckey because the ckey represents the individual and one individual may have multiple characters. That's  how it was organized before, and that's  just basic database common sense.

I like this naming scheme, though. As for the alphabetisation, it **is** by character name with the medals being from bronze, silver, and to gold.

**Comment by TheFurryFeline** [comment]
In fact, this way, you can have multiple medals for the same char by just adding the same name again with a number 2 and so on.

**Comment by TheFurryFeline** [comment]
It'd also be easier for others to see how to add their own in the future. With the name of the medal in the path as well as the character name after it, it's a simple matter of adding their own listing if they want to make the PR themselves after getting awarded it.

**Comment by Darlantanis** [comment]
Completed by #260.

Please avoid rejecting requested changes twice next time. Getting a PR up 30 minutes after it's requested isn't helpful when 5 days later it still lacks the requested revisions.

**Pull request closed without merging**
