### PR TITLE
Adds *prbt

### PR DESCRIPTION
**Pull request by Raeschen**
Very important.

Just a extra verb *prbt, a sound which i and some others have wanted to make. Purely fluff.
All (Humans, simplemobs) can use.

### CODE REVIEW

**Comment by Darlantanis** [comment]
Any edits to upstream files (pretty much anything that doesn't end in _ch.dm) will need //CHOMPedit comments. This can be line-by-line or at the beginning and end of a modified block of code.

**Comment by Darlantanis** [comment]
Also this doesn't compile, you're missing commas.

**Comment by Raeschen** [comment]
heck, i thought i changed that before i committed it. Fixin' .

**Comment by Raeschen** [comment]
It should be ready now.

**Pull request merged**
