### PR TITLE
[MIRROR] NanoUI Goes To Brazil

### PR DESCRIPTION
**Pull request by CHOMPStation2**
Original PR: https://github.com/VOREStation/VOREStation/pull/9062
--------------------
And may ye burn in hell, NanoUI.

This converts every last remaining template to TGUI, and nukes NanoUI entirely.

<details>
<summary>UIs Converted</summary>

- Accounts Terminal
- Agent Card
- Anesthetic Pump
- Arcade Battle
- Battery Rack
- Fax Machine
- Guest Pass
- Janicart
- pAI Interface
- Photocopier
- portable turrets
- Teleporter
- Telescience
- Turbine
</details>

<details>
<summary>Screenshots</summary>

Accounts Terminal
Agent Card
Anesthetic Pump
Arcade Battle
Battery Rack (all issues already fixed, didn't feel like setting the fucker up again)
Fax Machine
Guest Pass
Janicart
pAI Interface
Photocopier
portable turrets
Teleporter
Telescience
Turbine

</details>

### CODE REVIEW

**Comment by Razgriz1032** [comment]
I am slowly working this

**Comment by Razgriz1032** [comment]
JUST DO IT

**Comment by Raeschen** [comment]
changes made in tgui/packages/tgui need to be mirrored to tgui/packages/tgui_ch

**Comment by Kashargul** [comment]
We've done so many changes on tgui with the 5.0 transition that we really shouldn't try to deconflict that. It'll be easier to axe nano ui out in it's own PR. Keeping it only open as reminder.

**Pull request closed without merging**
