### PR TITLE
Borg access

### PR DESCRIPTION
**Pull request by cadyn**
## About The Pull Request

quick thing I whipped together after seeing discussion in development
## Changelog
:cl:
refactor: borg access is actually checked for many things that weren't checking before
balance: no more drone pod borg full access
balance: station borgs no longer have centcomm or syndi access
balance: borgs can be targeted by turrets
admin: add air_alarm access while ghosting
/:cl:

### CODE REVIEW

**Comment by Kashargul** [comment]
Breaks all station borgs.

**Comment by Kashargul** [comment]
On a closer look might be best to use card.access, the lists are identical and maybe, if needed replace the id card of the lost

**Review by Kashargul — APPROVED** [review]
No longer breaks all borgs.
Debugged and Tested with Cadyn.
Does what it says.

**Comment by Skysteak** [comment]
So what borg access is being changed effectively?

**Comment by User-U-U** [comment]
I now get shot by turrets awesome

**Comment by Kashargul** [comment]
> I now get shot by turrets awesome

Which turrets with which model?

**Review by Kashargul — CHANGES_REQUESTED** [review]
if(!emagged && siliconaccess(L) && check_all == FALSE)

=> if(!emagged && siliconaccess(L) && check_access == FALSE && check_all == FALSE)

**Review by Kashargul — APPROVED** [review]

**Comment by Skysteak** [comment]
Also as a follow up, will stationborgs be able to move into Tcomms/The Teleporter Room/AI Chamber without any fear of being shot at? I assume 'yes'. Hopefully turret settings wont need to be fiddled with.

**Comment by cadyn** [comment]
> Also as a follow up, will stationborgs be able to move into Tcomms/The Teleporter Room/AI Chamber without any fear of being shot at as normal? I assume 'yes'. Hopefully turret settings wont need to be fiddled with.

They should have the correct access, so yeah.

**Comment by cadyn** [comment]
> > > Also as a follow up, will stationborgs be able to move into Tcomms/The Teleporter Room/AI Chamber without any fear of being shot at as normal? I assume 'yes'. Hopefully turret settings wont need to be fiddled with.
> > 
> > 
> > They should have the correct access, so yeah.
> 
> Also just to be sure, I assume all other borg access is maintained? Stuff like all lockers (inc Command), all machines etc. As long as it's on station? I just want to be sure.

Borgs have access that is equal to the captain plus one extra called access_synthetic I believe, which is for AI chamber stuff. So-- if the captain can access it, a station borg will also be able to access it.

**Pull request merged**
