### PR TITLE
sound stuff going on

### PR DESCRIPTION
**Pull request by TheRiverStigs**
yadda yadda sound shit
+lyst, lure, vomva, void talksounds

### CODE REVIEW

**Comment by Kazzc** [comment]
Can you provide a reference link to the sounds in this PR?

**Comment by TheRiverStigs** [comment]
> 
assuming this means what i think it means, uhhhhh
https://kasumata.ee/

otherwise i'm clueless

**Comment by Razgriz1032** [comment]
Is this going to be worked on more soon?

**Comment by TheRiverStigs** [comment]
> Is this going to be worked on more soon?

yup n i think i fixed it

**Comment by Razgriz1032** [comment]
Conflicts

**Comment by Raeschen** [comment]
Nudging this, as it's old. Fix? Or close?

**Comment by TheRiverStigs** [comment]
> Nudging this, as it's old. Fix? Or close?

i don't even know at this point, i really don't have a clue what i'm doing or was doing at the time.
unless i can get a hand in figuring out what to do, do what you think needs to be done

**Comment by Raeschen** [comment]
> > Nudging this, as it's old. Fix? Or close?
> 
> i don't even know at this point, i really don't have a clue what i'm doing or was doing at the time. unless i can get a hand in figuring out what to do, do what you think needs to be done

No rush, i just wanted to make sure it wasn't forgotten. If you want some time, that's fine.
Currently there's a conflict that needs to be resolved, shown in the tests window.
Beyond that, i guess as long as you tested this locally, it's good

**Pull request closed without merging**
