### PR TITLE
[TestMerge ONLY] InputFix Attempt

### PR DESCRIPTION
**Pull request by Kashargul**
An attempt to fix the TG Number inputs, do NOT merge this, this is for test merging only. If it works, this will be done upstream

### CODE REVIEW

**Comment by ItsSelis** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: e465f07de84266e4a42f727f3e4a00aac5b303ba
Pull Request: e9c8080ccf1009945bd4dd39152406028929e01f
Server: b32aa58c169e5ce238271591ab5e531b1bd811d4

##### Comment

</details>

**Comment by ItsSelis** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: e74e05cf27e4e5931ad333efa1f2e3f9927cfbe1
Pull Request: e9c8080ccf1009945bd4dd39152406028929e01f
Server: 76732b59143f0f4e095bc5068b667980488c6260

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: 1aad47a8e960e7bb6644adad3f0c21564f77cdea
Pull Request: e9c8080ccf1009945bd4dd39152406028929e01f
Server: de2b61600656a4a0d67406185ad1a1b7452cb122

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: e276e65f17eba77caf86b3edc8d904d90b35b701
Pull Request: e9c8080ccf1009945bd4dd39152406028929e01f
Server: fd3b46b7e17165296bebfd852de6d91013d9e0cc

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: 27f60c19052a0d1de22c906439190a5604d5bd81
Pull Request: e9c8080ccf1009945bd4dd39152406028929e01f
Server: 24814fdc00ec2bd48884c24bc189ff65557242c6

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: a9a5bdf6f0638e8a360f8f2def45d7ae8cc11587
Pull Request: e9c8080ccf1009945bd4dd39152406028929e01f
Server: a4b3b03e8d6e6801a2a9d49d0a2a9f4ee9002066

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: 4f565d652643c697b19b73b5dcc4bf9f7c3433fe
Pull Request: e9c8080ccf1009945bd4dd39152406028929e01f
Server: 9a73283c2d30b1475365ac57181c2c64cbf2d003

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: a0b89744da685ca403291ffbe2228b165a924e53
Pull Request: 255268661ca002800d477adb3567dc86d5b9b803
Server: 76af991e7e2900e830480f57165a67ca95af00ea

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: c399857a93a0fae0d1e58f1c5f63228709fa3c54
Pull Request: 255268661ca002800d477adb3567dc86d5b9b803
Server: fec549007a4b211b62f36011362236da301a180d

##### Comment

</details>

**Comment by Kashargul** [comment]
Remove from TM before merging #7768

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: 0382c1247d7031dcb620aee306077cc42708d54e
Pull Request: 255268661ca002800d477adb3567dc86d5b9b803
Server: 6e1152b431c231e42ff2bc3bd11d71681f9ed68c

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Removed

**Pull request closed without merging**
