### PR TITLE
Cinnamon stuff!

### PR DESCRIPTION
**Pull request by KotetsuRedwood**
I want to be able to have people eat the ~~funny undertale~~ butterscotch and cinnamon pie, cause it's a cute food.

And honestly? Cinnamon seems like a fun thing to add for other recipes, like french toast, powdered with cinnamon, or cinnamon sweetrolls.

This pull's a WIP right now, and I would appreciate the help from people more knowledgeable with hydroponics and/or food code.

### CODE REVIEW

**Comment by KotetsuRedwood** [comment]
Iiiii just realized that part of the recipes I'd want for this involves stuff from the aurora cooking port. Still, having the stuff ready for when that's properly merged into the parent branch wouldn't hurt! Sprites are very, very obviously WIP

**Comment by KotetsuRedwood** [comment]
If anyone knows how to make a food make you cough when you eat it, that'd be appreciated!

**Comment by KotetsuRedwood** [comment]
Don't merge this until the cooking update's out! I should've said that earlier. Going to keep working on foods to add so cinnamon isn't JUST for undertale food, but I won't have recipes until I have access to the different cooking machines. Sprites are horridly WIP, too!

**Comment by Razgriz1032** [comment]
Things are calming down. I'll finally have some time to look at this and see what it's about. Aurora cooking has been full merged finally

**Comment by Rykka-Stormheart** [comment]
> If anyone knows how to make a food make you cough when you eat it, that'd be appreciated!
> 
> Because, y'know. Cinnamon challenge. Don't eat raw cinnamon.

You'd want to modify raw Cinnamon's affect_ingest call and have it call parent while making them cough every, say, prob(25) for a chance at coughing. If you're interested I can take a look and help you out with it later.

**Comment by KotetsuRedwood** [comment]
> > If anyone knows how to make a food make you cough when you eat it, that'd be appreciated!
> > Because, y'know. Cinnamon challenge. Don't eat raw cinnamon.
> 
> You'd want to modify raw Cinnamon's affect_ingest call and have it call parent while making them cough every, say, prob(25) for a chance at coughing. If you're interested I can take a look and help you out with it later.

That'd be nice! I'd like for it to be like "only if there's over so much" so you don't have people like coughing and sputtering because they put a sprinkle of cinnamon on their toast or something

**Comment by Razgriz1032** [comment]
Looks good to me

**Comment by Dinnel** [comment]
I helped!~

**Comment by Darlantanis** [comment]
Is this still being worked on? It's almost been 3 months.

**Comment by Razgriz1032** [comment]
I will be closing this tomorrow if there are no updates.

**Pull request merged**
