### PR TITLE
[MIRROR] Phoron Dragon Catalogue Data 

### PR DESCRIPTION
**Pull request by CHOMPStationBot**
Original PR: https://github.com/VOREStation/VOREStation/pull/10582
--------------------
Adds a catalogue entry for the Phoron Dragon

### CODE REVIEW

**Comment by JesusChristItsJasonBourne** [comment]
if you merge this I will stab someone

**Comment by Razgriz1032** [comment]
Whoever wrote this didn't spell check either. "A rare site to see"
It's SIGHT, please.

**Comment by JesusChristItsJasonBourne** [comment]
Lore draft written and spell checked, if approval is granted it'll be edited in.

**Comment by Razgriz1032** [comment]
Yes?

**Comment by JesusChristItsJasonBourne** [comment]
yes

**Pull request merged**
