### PR TITLE
update to the deck 2 south bar.

### PR DESCRIPTION
**Pull request by Asher-42**
https://i.imgur.com/gwPQsyx.png
image

## Changelog
added dispensers to the main room of the south bar to be more inline with bar standard, and more enjoyable. 
:cl:
maptweak: added dispensers behind the counter and removed them from the chef area. displaced things were moved to bartenders personal room and chef area.

/:cl:

### CODE REVIEW

**Comment by Kazzc** [comment]
There are now 2 drink dispensers in the bar. Forgot to remove the other one.
The goal was to have the bartender head in to the kitchen to prepare stuff, do note that is inconvenient.
Did want to add a difference of items between Bar and Dinner, Bar having all the alcohol while the Dinner has all the food.

**Comment by Asher-42** [comment]
removing the one in the kitchen, but i dont know what you mean by the second part, part of bartending is making drinks infront of people, in game and in real life. id rather make drinks personally as a bartender inside the bar and not the kitchen. kitchen things was always a cafe players thing, not the bartender

**Comment by Asher-42** [comment]
removed

**Comment by Kazzc** [comment]
I'll make a fix myself, still got a few thing wrong on this edit.
-3 tube lights setting next to each other.
-missing the beer keg
-Disposal chute is in the wall.

I like your feedback, I'll make me a fix and make sure the drink dispensers are in the bar reception. I'll move all the food in the kitchen instead.

**Pull request closed without merging**
