### PR TITLE
Redo of Mapfix Palooza Round One

### LINKED ISSUE #23: No body design consoles
Title. Not sure what else I can say.

### LINKED ISSUE #24: Chief Engineer does not have access to telecoms
#### Brief description of the issue
Poke airlock as CE

#### What you expected to happen
Airlock opens

#### What actually happened
Airlock calls you gay (no not really it just doesn't open)

#### Steps to reproduce
1. Be CE
2. Try to open telecoms airlock

####Extra Info
The front door has the wrong access of vault and telecomms. It should be maintenance and telecomms.

#### Code Revision
d1ade01fbbc6501d5a76f93789d94b0e9eac11fd 
https://github.com/CHOMPStation2/CHOMPStation2/commit/d1ade01fbbc6501d5a76f93789d94b0e9eac11fd

### LINKED ISSUE #28: No Mining redemption machine on planet
There is no Mining Redemption machine on planetside mining, making them take the shuttle up to cargo to get any rewards from mining. Not to mention it is also outside in the cargo lobby for some reason as well.

### LINKED ISSUE #60: Add one Umbrella inside of each explorer locker, and medical explorer locker.
#### Brief description
A umbrella is a life saver both in the snow environment, and in the wilderness. If a hailstorm arrives it is the only way to prevent oneself from getting hurt, excluding running for cover. It would make more sense if every explorer and medical explorer locker had one umbrella inside of it, as it would prevent explorers from having to search the entire outpost for a single umbrella to prevent potential hail based death.

### LINKED ISSUE #80: Holodeck's Electrochromic windows don't all tint.
The two groups of windows here just don't tint.
image

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Redoing Mapfix Palooza with notable changes being the re-removal of the NSFW gun with comment for YW's removal. Keeping the dorm additions undone pending a followup PR.

Changelog Notes:

- Removes random SMES in maints mapped in for Research.

- Chemistry shutter switches moved to removed entertainment monitor's place.

- Material stacks condensed into 1 obj with amount vars adjusted appropriately. Vault, Chemistry, etc. Switches Engineering's full stacks to fiftyspawners.

- Rearranges items in HOS Office and adds gear closet with weapon power cell.

- Add AR-B glasses to CD Office and plain AR glasses to HOP.

- Add missing shortwave radios to the bridge.

- OR rooms rearranged.

- - Anasthetic wall pumps added.

- - Anasthetic wall closets removed.

- - Surgery tools, table, monitor, IV drips moved.

- - Add anesthetic floor-based closets as a reserve.

- - Minor increase in area size.

- - Shifts Surgery Storage and Patient Rooms to the east and adds roofing on Deck 3 to account for the move.

- Exploration rewards vendor moved to explorer areas on outpost. Deletes the one in Research wall. Also rearranges spawnpoints for explorers on the surface.

- Add Mining redemption vendor. Resolves #28

- Moves lights in several places to not be in the same spot as cameras.

- Fixes APCs at Xenoresearch being turned off as well as access into the sub-department. Also removes exploration vendor.

- Internal second button added in engine room for going in and out of the SMES room.

- Mech Bay shutter name fix. Was labelled Mining Storage.

- Fixes blindspots for cameras.

- Drop-nom spots added. Remove windows and railings at your own risk. 
Drop_Nom_Spots

- Door access fixes.

- - Remove access restrictions on FA Stations.

- - Fix access for Blue Armoury preventing HOS entry.

- - Fix access for surface teleporter room preventing RD entry.

- - Fix access for CE into T-comms. Resolves #24 Also fixes turret control access.

- - Removes bridge access to main Teleporter Room, restrict to usual Teleporter access.

- - Same as above for all defense turrets' manual access.

- - Also does the same for west door of E.V.A. Bridge access removed, gives E.V.A. access.

- - Access fix for Cargo Substation, first deck.

- - Removes Xenoarch, Engineer, Miner access to Surface T-Comms room, gives T-comms access to the door.

- - Medical access to Field Medic gear room doors.

- - Removes Research access to Mining Outpost, Command and Central Substations. Also fixes a door name.

- - Removes mining access restrictions to unused Hangar 3. (Really? Why do only they get access to this one?)

- - Fixes access to Secure Tech Storage requiring vault access. (Why are there so many places that have this? Reee)

- Gives Armoury what it had for Northern Star.

- Dorm tweaks.

- - Locks added to heads' bedrooms on deck 3 as well as visitor rooms on deck 2.

- Increases main power SMES energy amount.

- Remove extra AI Status Display Monitor in QM Office.

- Add a bunch of brollies to hangar bays, explorer lockers, and field medic lockers. Resolves #60

- Add Body Designer to Medbay Lobby. Also adds the box that goes with it. Resolves #23

- Adds Erik's Lungs back. Rejoice, you food pupper! 

- Adds Timeclocks for switching on/off duty.

- Adds a bino to each exploration locker for FMs and Explorers. 

- Gives QM a fax machine and adds 1 more public one. One at the library.

- Add Mining Suit Cycler.

- Mining Tug Train connected.

- Fixes Holodeck tint button's range. Resolves #80 

- Random wall turned into plating turf for a set of windows.

- Add tinyfans for Cryo Pod and Shutters for the doors leading out into the hallway. Tinyfans also added to arrival shuttle spawn to prevent death on spawning in.

- Adds firedoors for the lifts so people don't get automatically vented to space if a deck is, well, vented to space. Slight adjustments to some locations for scrubbers, air alarm placements, et cetera.

- Door name fixes for Utility Accesses on Deck 1.

- Spare light frame fixes. They were half constructed on nothing.

- Fixes pixel placement of med intercom in an escape pod.

- Overlooked Shield Diffusers added.

- Brig and Toxins Scrubber Control consoles replaced with correct ones. Tags added appropriately to respective large scrubbers.

### CODE REVIEW

**Comment by Darlantanis** [comment]
Remove the railings from around the shuttles. Aside from looking silly, there's no purpose to roping off where the shuttles land as they do not gib people. They just shove people out of the way.

**Comment by TheFurryFeline** [comment]
They didn't do that in the past, as I recall. This was a suggested idea for
safety reasons. I'll do the requested changes in the morning.

On Jan 4, 2020 19:49, "Nadyr" <notifications@github.com> wrote:

Remove the railings from around the shuttles. Aside from looking silly,
there's no purpose to roping off where the shuttles land as they do not gib
people. They just shove people out of the way.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CHOMPStation2/CHOMPStation2/pull/75?email_source=notifications&email_token=AJGMTYZUDS4D3K4HU5VIM2TQ4EVBDA5CNFSM4KCFDX32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIDDUSY#issuecomment-570833483>,
or unsubscribe

**Comment by Darlantanis** [comment]
I've had some time to test each change mentioned in your changelog.

Further comments
-Dream maker shows no additional exploration vendor has been added to the outposts, I'm only finding the extra one which already exists in surface xenobio. Did you forget to add it?

-The change to the OR rooms is unacceptable. Tools need to be close to the operating table for ease of operation, you've moved the table farther away. Additionally the anesthetic pump is visually too far from the table, this is going to confuse new players. The scrubber is also now hidden under a table. Our standard is to keep vents and scrubbers visible.

-Dream maker shows no mining vendor added to the outposts. Did you forget to add it?

-The vendor you said you removed from outpost xenoresearch still exists.

-Please re-add the decals you removed from your 1st floor drop noms spot. Aesthetically these hallways no longer fit with the port/starboard central hallways now.

**Comment by TheFurryFeline** [comment]
> I've had some time to test each change mentioned in your changelog.
> 
> Further comments
> -Dream maker shows no additional exploration vendor has been added to the outposts, I'm only finding the extra one which already exists in surface xenobio. Did you forget to add it?
> 
> -The change to the OR rooms is unacceptable. Tools need to be close to the operating table for ease of operation, you've moved the table farther away. Additionally the anesthetic pump is visually too far from the table, this is going to confuse new players. The scrubber is also now hidden under a table. Our standard is to keep vents and scrubbers visible.
> 
> -Dream maker shows no mining vendor added to the outposts. Did you forget to add it?
> 
> -The vendor you said you removed from outpost xenoresearch still exists.
> 
> -Please re-add the decals you removed from your 1st floor drop noms spot. Aesthetically these hallways no longer fit with the port/starboard central hallways now.

I had copied all the map changes I'd map and transferred the work to a new branch. In the process, I had to deal with a whole slew of conflicts where I manually overrode them to favour the new changes over what was on the master branch. I apparently missed a few tidbits in the process with regards to the vendors, strangely enough. 

I'll be fixing those shortly and will see about changing the OR rooms a bit more to resemble what's used on Virgo. Unless just having a surgery kit toolbox on the table will be fine? As for the decals, can do.

**Comment by Razgriz1032** [comment]
Hey, this is your local inflationist here to say that this PR is getting too bloated with all these commits. There is actually a line of people waiting to do their own things to the map as well. Wrap it up now, please.

**Comment by TheFurryFeline** [comment]
I keep finding things, weh. Sorry, I'll stop with this one.

**Comment by Razgriz1032** [comment]
OK, so this is good to merge now?

**Pull request merged**
