### PR TITLE
Shadekin nerfs (again)

### PR DESCRIPTION
**Pull request by Raeschen**
Okay lets try this again

HP reduced across the board.
Introduced an anti-phasing mechanic:
- Bluespace crystals (Artificial and normal) now mess with phase
- Stepping on them is like stepping on a mine - it will drag a shadekin out of phase. Avoid tcomms!
- Throwing a bluespace crystal will dephase all shadekins (in valid dephasing positions) in a 3-tile radius. 
- A crystal attempting to dephase a shadekin (thrown or stepped on) will shatter
- Shadekin must be in a valid position to be force-dephased (They can hide inside walls and be unaffected) 
- Hiding crystals in walls or other unphaseable spots will lead to them shattering, but no dephased shadekin (Punished for cheek)
- A crystal must be on the floor to be used as a mine. They will not have an effect held, stored, or put in lockers. 
- Crystals still do their original mechanics (They randomly tp a creature they hit somewhere and shatter) as well
- A very large, visible ADMIN LOG will show every time a shade is dephased forcefully:
`ADMIN LOG: CKEY/(Character Name) was stunned out of phase at 131,83,2 by bluespace crystal, last touched by CKEY. (JMP)`

NOTHING ELSE. No energy regen/capacity changes. Just HP and a way to unphase them. 

https://cdn.discordapp.com/attachments/829622522215530506/1205306067085692938/dreamseeker_2024-02-09_01-05-02.mp4

:cl:
balance: Shadekin HP nerfs (Per eye color)
balance: Bluespace crystals dephase shadekin that step on them
balance: Bluespace crystals will dephase shadekin in a 3 tile radius when thrown.
/:cl:

### CODE REVIEW

**Comment by theXDkidoflol** [comment]
ive been waiting for this moment my entire life

but really, excellent balance PR, and kudos to the team on this one. they had a bad idea, found out it was bad, and rather than saying 'fuck you this is good merge it anyways', they changed it and made it better.

bless ya.

**Comment by cadyn** [comment]
if this is to become a mechanic, then perhaps lore-wise this could be extended to NT using these to protect secure areas? I think the preferable implementation there would just be to add some area check to prevent them from phasing into or out of secure areas, have the boundaries act as walls basically.

**Comment by KotetsuRedwood** [comment]
Suggestion: Thrown bluespace crystals should make lights flicker like shadekin phasing in

**Comment by Skysteak** [comment]
Absolutely disagree with this, even as someone who doesn't play shadekin. It'll only encourage people to seek out those mechanics and grief/troll -- something that has had a history of happening in SS13 no matter how niche or hard to get the species countering item is.

**Comment by Raeschen** [comment]
> Absolutely disagree with this, even as someone who doesn't play shadekin. It'll only encourage people to seek out those mechanics and grief/troll -- something that has had a history of happening in SS13 no matter how niche or hard to get the species countering item is.

This is a moderation issue, not a code issue. You can just as easily take a taser and zap a player repeatedly. Some clarification will be added in the rules that abusing these on shade who don't deserve it will be treated as such

**Comment by Raeschen** [comment]
> if this is to become a mechanic, then perhaps lore-wise this could be extended to NT using these to protect secure areas? I think the preferable implementation there would just be to add some area check to prevent them from phasing into or out of secure areas, have the boundaries act as walls basically.

for sure! this is just sort of 'attempt one' to implement it and see how things go ingame
We will be writing guidelines, and these crystals will be treated like taseers (Or lethals since they still teleport a hit player)

**Comment by Kazzc** [comment]
Fun stuff, can't wait to lay down on a bluespace crystal.

**Pull request merged**
