### PR TITLE
Adds loadout capture crystals!

### PR DESCRIPTION
**Pull request by TheGreatKitsune**
Loadout capture crystals! They cannot be used to capture things, and must be joined from character setup using Item TF spawnpoint. (I.e. they behave as if they already have a mob in them)

This includes the ability to spawn as a simplemob inside of a loadout capture crystal, with choices similar to the metamorphosis ray.
image

### CODE REVIEW

**Comment by Darlantanis** [comment]
Missing comments in job_controller.dm, rest is good.

**Comment by Kazzc** [comment]
@.-.@
Holy shit this is amazing. :O

**Comment by Razgriz1032** [comment]
See CONTRIBUTING.md. Also conflicts.

**Comment by TheGreatKitsune** [comment]
Conflicts fixed, all code that needs it is already within chompedit comments though?

**Pull request merged**
