### PR TITLE
[MIRROR] Space Whale Tweaks

### PR DESCRIPTION
**Pull request by CHOMPStation2**
Original PR: https://github.com/VOREStation/VOREStation/pull/11953
--------------------
I forgot to write a scanner description for it. (Also I made it slightly easier to land on)

### CODE REVIEW

**Comment by CHOMPStation2** [comment]
remirror

**Comment by CHOMPStation2** [comment]
what if I do this

**Comment by CHOMPStation2** [comment]
remirror

**Comment by CHOMPStation2** [comment]
domirror 11953

**Comment by CHOMPStation2** [comment]
Nah, this PR is just fucked. Needs manual implementation

**Comment by CHOMPStation2** [comment]
remirror

**Comment by CHOMPStation2** [comment]
remirror

**Comment by CHOMPStation2** [comment]
remirror

**Comment by CHOMPStation2** [comment]
remirror

**Comment by Razgriz1032** [comment]
remirror

**Pull request closed without merging**
