### PR TITLE
Re-Maps a big chunk of the Medical department

### PR DESCRIPTION
**Pull request by TheCaramelion**
## About The Pull Request

Raise geneticists and virologists, your time has come. We all go back to Medical.

image
image

## Changelog
:cl:
maptweak: Revamped Chemistry
maptweak: Revamped Patient rooms
maptweak: Revamped Destillery room
maptweak: Revamped Medical storage
maptweak: Virology is now on Deck 2
maptweak: Genetics is now on Deck 2
maptweak: Morgue is now on Deck 1
maptweak: Cryo has been expanded
maptweak: Medical has now two scanners and two sleepers
/:cl:

### CODE REVIEW

**Comment by Kazzc** [comment]
Just by glance, you are missing so many markings. . .
-Miss placed markings.
-Missing markings
-Resleeving room is no longer private (This was a huge request from players to have an option to be private)
-Missing cameras in medical hall between morgue/resleeving.
-Camera in morgue doesn't have full view of the morgue. (range of 7, morgue is 8 tiles long)
-Missing AI screens in the morgue.
-Clothing machine on wall will still block pathing. (assuming is pixel shifted into the wall, if its placed in the wall can see and have access on the other side)
-Missing wall comms in the morgue. 
-Missing tools in the morgue.
-Morgue could use some windows into space.
-Miss matching colors in Virology
-Missing emergency fire alarm in Virology.
-Random chute pipe in resleeving that's not connected anywhere.
-

I like the idea but its poorly executed, unsure how to feel about the general pathing and the morgue location, requiring to walk into med-bay/resleeving to access it. Else heading down stairs.
Same that resleeving is no longer a private area, naked players getting resleeved in a sensitive traffic area where doctors need space to use sleepers.
A lot of missing markings and various missing wall machines, this further butchers Medical layout. Honestly needs a much larger redesign if you want to fit everything properly.

**Comment by TheCaramelion** [comment]
The screenshot is a little bit outdated, but most of the marking issues have been solved. I'll send you how it currently looks in a minute in case I've missed some others.
The clothing machine is the same one that is currently placed on live, same with the tools in the morgue and colours in Virology.

I'll update in a while with the other stuff in a minute

**Comment by CEO-Of-Dogborg-Corp** [comment]
Re run map merge, it didnt run right.

**Comment by TheCaramelion** [comment]
Update

imagen
imagen

**Comment by Kazzc** [comment]
-Bathroom. Fire extinguisher facing the wrong direction. Or its in the wall?
-Missing fire alarm inside Virology airlock cycle.
-Missing AI & Status screens inside Virology.
-Virology no longer has an atmos Bypass.
image
-Genetics isolation room has a wall comms. (remove it)
-Genetics isolation room. Has a fire alarm placed on a window. (Remove it)
-2 light switches inside chemistry distillery. One overlapping the fire alarm.
-I still think you need a few windows for medbay equipment storage. Kinda weird for CMO to have full view of the storage? Maybe a window or two. 
image
-Nanomed could be placed somewhere better. Place it in the wall facing south.
image
-Could use chromatic windows.
image
-Missing smoking signs inside Viro and Genetics.
-Missing Biohazard signs inside Viro. /obj/structure/sign/warning/biohazard
-Missing wall nanomed inside Viro
-Missing virus food dispenser inside Viro. /obj/structure/reagent_dispensers/virusfood
-Missing biohazard suit inside Viro. /obj/structure/closet/l3closet/virology
-Morgue missing AI & Status displays.
-Morgue stairs missing railings on the side. (First deck stairs, without it. It can cause some weird clipping. Tesh can probably run upstairs by walking straight south.)
-Morgue, switch these. (Fire alarms should always be placed near exit points.)
image
-Chemistry missing AI & Status displays.
-Chemistry missing wall buttons. Chem counter & chem window.
image


I think that's everything I can spot so far. Like the better pathing you have going on for cryo/resleeving. I'm sure this will still cause some traffic jams.

**Comment by Kazzc** [comment]
See if nothing breaks! Good stuff so far.

**Pull request merged**
