### PR TITLE
[MIRROR] Chopped up the wideborg files.

### PR DESCRIPTION
**Pull request by CHOMPStationBot**
Original PR: https://github.com/VOREStation/VOREStation/pull/9609
--------------------
I divided the dogborg sprite files by department and made the code use those. This should fix the cache jank.

### CODE REVIEW

**Comment by cadyn** [comment]
do we even need or want this

**Comment by Darlantanis** [comment]
Unsure. Conflicts may be tricky though due to yw borgs.

**Comment by Sharkmare** [comment]
Why would anyone want wideborgs to be across multiple files, this just boggles my mind

**Comment by Darlantanis** [comment]
Apparently having them all in one file causes crashing for some clients.

**Comment by Razgriz1032** [comment]
I think we can accept these, I don't think we're missing out on anything. I will test regardless.

**Pull request merged**
