### PR TITLE
[MIRROR] Fixes 0 RGBs breaking character colors on resleeve

### PR DESCRIPTION
**Pull request by CHOMPStationBot**
Original PR: https://github.com/VOREStation/VOREStation/pull/9258
--------------------
math is hard

### CODE REVIEW

**Comment by cadyn** [comment]
WHAT THE FUCK VERKISTER

**Comment by cadyn** [comment]
DO NOT MERGE THIS

**Comment by cadyn** [comment]
This is the awful virgo fix for this issue, we have an actual greater than 2 IQ fix for this already with a chompedit.

**Comment by Darlantanis** [comment]
I kinda wish I understood what's bad about this

**Comment by Razgriz1032** [comment]
> ## Original PR: [VOREStation/VOREStation#9258](https://github.com/VOREStation/VOREStation/pull/9258)
> math is hard

No truer words have been said in light of this fix

**Pull request closed without merging**
