### PR TITLE
Adding an ID slot to the Communicator

### PR DESCRIPTION
**Pull request by Sharkmare**
Allows you to slot your scanned ID into your communicator

### CODE REVIEW

**Comment by Sharkmare** [comment]
vorestation.dmb - 0 errors, 0 warnings (3/17/23 11:00 pm)
The good text

**Comment by Sharkmare** [comment]
image
Alt click communicator to remove ID

**Comment by Darlantanis** [comment]
Will this also apply to the communicator watch?

**Comment by Sharkmare** [comment]
> Will this also apply to the communicator watch?

Yup it should! as the Communicator watch is simply just a reskinned communicator!

**Pull request merged**
