### PR TITLE
Fixs issue 1171

### PR DESCRIPTION
**Pull request by Armyguy**
https://github.com/CHOMPStation2/CHOMPStation2/issues/1171

Namely by pointing it NOT to the in hand.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
This is wrong. What you are changing is for the object before you put it on, not the worn sprite.

**Comment by Armyguy** [comment]
I Think? that will fix it, I'm not 100% on icon_overrides. but its this or editing the .DMI

**Comment by Sharkmare** [comment]
> I Think? that will fix it, I'm not 100% on icon_overrides. but its this or editing the .DMI

You could always launch up a test server and look if it fixed it, if ya need help doing so i can provide

**Comment by Razgriz1032** [comment]
I tested it myself, it works.

**Comment by Darlantanis** [comment]
Will note icon_override may break species-specific icons, if they exist.

**Pull request merged**
