### PR TITLE
Nerfs free guns from POI

### PR DESCRIPTION
**Pull request by tacoguy7765093**
## About The Pull Request
One wilderness gateway is a free locus and 8+ guns. You get 2 broken guns and a small pistol now.  Too much of a meta POI. More POIs will be added soon
## Changelog
:cl:
maptweak: Reduced loot amounts in a POI.
/:cl:

### CODE REVIEW

**Comment by TheCaramelion** [comment]
I don't really see the point of removing the free locus. It's just a chill PoI, not everything has to be murderzone. I do agree there's quite a few guns thrown around, maybe could be changed for something else more thematic.

**Comment by tacoguy7765093** [comment]
It's hardly a "vibe" poi if it gives off free things. It's mostly used as the "of hey, look free loot poi"

**Comment by Raeschen** [comment]
I don't think this is very necessary

**Comment by tacoguy7765093** [comment]
Which part? The locus or the gun nerfs

**Comment by Raeschen** [comment]
> Which part? The locus or the gun nerfs

Kind of both. i'm unsure. Should perhaps be discussed

**Comment by Kazzc** [comment]
This POI needs a nerf, as is all POI's need a nerf as is.
image
For a simple POI that has melee 9 mobs and one elite one giving out 8+ guns and a alien locus is, eh-.
We need less gun rewards for explo content as is.

**Comment by tacoguy7765093** [comment]
I got better ways to nerf overpowered easy access guns in the future.

**Pull request closed without merging**
