### PR TITLE
POIS II

### PR DESCRIPTION
**Pull request by EveryStepYouTake**
Now with 100% less laziness

- Adds location indicators in areas for Caves and Wilderness. (i.e. POI _Caves_ - Crystalline Cave). This is only currently in the game for Plains. Fixes a few grammar errors too.

- Adds areas for Oregrub Deposit and Rat Den. These had none so they'd spawn in but wouldn't come up in the area menu.

- Rocky Crevice can spawn in both Plains and Wilderness and had the same area. Plains version now has a new area so Plains Rocky Crevice and Wilderness Rocky Crevice are distinct in the area menu.

(This will all help death alarms too)

- Deletes some useless backup POI dmms. This won't cause conflicts

- 'Empty Explorer's Home' Plains POI now feels more like the functioning frontier home it's supposed to be, some cool one-off lore items, and adds a cool new secrets. Still balanced, no meaningful loot added. Bookcase door sprite edit by yours truly.

https://user-images.githubusercontent.com/99452569/161547199-eaf82728-87fb-4386-b92e-00bd6e692fb1.mp4

### CODE REVIEW

**Comment by Razgriz1032** [comment]
Door_control, blast_door, and signs are all missing comments that they are new additions, as mentioned in contributing dm
https://github.com/CHOMPStation2/CHOMPStation2/blob/master/.github/CONTRIBUTING.md


I would recommend commenting //CHOMP Addition Start  and //CHOMP Addition End at the end of your code blocks

**Comment by Kazzc** [comment]
Aside of taking this long. . .
Now that I got to see them and test them, pretty good content. 
Just note on what Raz said on adding //CHOMP edit. Will love these on our exploration content.

**Comment by Razgriz1032** [comment]
https://thumbs.gfycat.com/BogusForsakenAsianlion-size_restricted.gif

**Comment by Razgriz1032** [comment]
A manual compilation and test server worked. I'm merging.

**Pull request merged**
