### PR TITLE
Adds a Hippo Snout body marking!

### PR DESCRIPTION
**Pull request by Hunter-Dovetail**
## Changelog
:cl:
add: "hippo snout"/"hippo_snout-head"
/:cl:

### CODE REVIEW

**Comment by Kashargul** [comment]
Not having used the latest file, merging this would delete existing icons.

**Comment by Hunter-Dovetail** [comment]
> Not having used the latest file, merging this would delete existing icons.

Was following Nadys directions since this was my first time doing this - ill reach out to them to ask what went wrong.

**Comment by Kashargul** [comment]
> > Not having used the latest file, merging this would delete existing icons.
> 
> Was following Nadyrs directions since this was my first time doing this - ill reach out to them to ask what went wrong. Could you also elaborate on what it means to use the latest file? Just so I know for next time.

The latest file is the current file on the active master branch. If you are behind on your fork, you need to update the branch and make sure to add a new icon only to the latest version of the file.

**Comment by Hunter-Dovetail** [comment]
> > > Not having used the latest file, merging this would delete existing icons.
> > 
> > 
> > Was following Nadyrs directions since this was my first time doing this - ill reach out to them to ask what went wrong. Could you also elaborate on what it means to use the latest file? Just so I know for next time.
> 
> The latest file is the current file on the active master branch. If you are behind on your fork, you need to update the branch and make sure to add a new icon only to the latest version of the file.
> 
> To fix it in the easiest way, get the DMI file from the active master branch directly, add your new icon and add the file back here.
> 
> https://github.com/CHOMPStation2/CHOMPStation2/tree/master

Yeeesh I dont know what any of this means, I use Gitkraken but Nadyr guided me through this on Github - how do I get the DMI file from the active master branch directly? (I got the DMI file from my Dream Maker)

**Comment by Kashargul** [comment]
> > > > Not having used the latest file, merging this would delete existing icons.
> > > 
> > > 
> > > Was following Nadyrs directions since this was my first time doing this - ill reach out to them to ask what went wrong. Could you also elaborate on what it means to use the latest file? Just so I know for next time.
> > 
> > 
> > The latest file is the current file on the active master branch. If you are behind on your fork, you need to update the branch and make sure to add a new icon only to the latest version of the file.
> > To fix it in the easiest way, get the DMI file from the active master branch directly, add your new icon and add the file back here.
> > https://github.com/CHOMPStation2/CHOMPStation2/tree/master
> 
> Yeeesh I dont know what any of this means, I use Gitkraken but Nadyr guided me through this on Github - how do I get the DMI file from the active master branch directly? (I got the DMI file from my Dream Maker)

Either sync your master branch and pull it from there afterwards. (Sync master branch, Fetch origin, Checkout origin/master)

Add the Fork's origin as upstream in git. (Fetch upstream, checkout upstream/master)

Or download it from it manually.

**Pull request closed without merging**
