### PR TITLE
Vox security rigsuit

### PR DESCRIPTION
**Pull request by crabcube**
Bugfix mode, the supply pack cannot call on the rig for a reason i must find

### CODE REVIEW

**Comment by LordSaladin** [comment]
what's so different about the voxxy rig vs a regular suit?

**Comment by crabcube** [comment]
> what's so different about the voxxy rig vs a regular suit?

It has a functional sprite, which you will learn, vox are lacking in

**Comment by Razgriz1032** [comment]
Merged by accident.
Please read https://github.com/CHOMPStation2/CHOMPStation2/blob/master/.github/CONTRIBUTING.md

And make your changes and additions to the modular_chomp folders.

Also, are you aware that your new hardsuit will have the same sprites as another suit based on pathname inheritance?

**Comment by crabcube** [comment]
I gave up on my sprite editing effort so I called on an existing one intentionally! No new sprites were added to anything, and okie dokie.

**Pull request merged**
