### PR TITLE
Massive Broad Scope Changes

### LINKED ISSUE #4072: Crew Monitor Computer in the Search and Rescue bay should be moved
#### Brief overview of the feature
Patient data is available to the public so the console should be moved into a more secure location.

#### What you want to happen
The crew monitoring computer should be moved into the medical restricted area of the same room. It contains patient data that should only be available to medical staff.
 
#### Anything else you may wish to add:
image

### PR DESCRIPTION
**Pull request by VictorZisthus**
**RUNTIME ERROR FIX(S):**
Chainsaws will no longer cause runtimes by trying to call on the regnant system before the regnant system loads up.

**NEW STUFF**
Added in a custom thermal regulator for the wilderness shelter.

Southern Cross now has a Bluespace Radio!

Added a subspace radio, and allowed it to be made in the autolathe.

**ALL MAPS:**
Added lighting to dark areas. Did not touch lighting in maintenance areas.

**Snowfield**
Fixed the detective's door.

**POI - Chapel**
Fixed powernet issue.

**POI - Borg Lab**
Set the fire alarms to not report status to consoles.

**POI - Demon Pool**
Fixed broken loot spawns.

**POI - Empty Cabin**
Fixed broken loot spawns.

**POI - Syndicate Sniper**
Replaced broken bluespace handset radio with proper bluespace pack.

**DECK ONE:**
Adjusted exterior lattice network.

Adjusted some stuff in telecoms storage. Added relay boards, teleporter boards, and Artificial bluespace crystals for teleporter building.

B-shift have received additional training. The Auxiliary grid will now start at 100% charge.

**DECK TWO:**
Fixed a bug with Shieldgen.

Moved a button in engine.

Moved the Engine SMES powernet sensor off of a pump.

Removed the second freezer air alarm to prevent pressure alarms from going off every shift. (I got my revenge on the laws of thermodynamics with the new custom regulator, don't worry.)

Completely redid the Engine Pipe network to allow post engine startups to all aspects of the network for the most common edits.

Put a new subspace radio in the bar.

Adjusted exterior lattice network.

**DECK THREE:**
Removed a duplicate shower curtain in one of the dorm rooms.

Site manager will now properly spawn in their office.

**SURFACE OUTPOST:**
This PR will cause a conflict with #4061 but I am willing to help Enzo with the project as needed~

A friend and boy waits for the miners every shift.

Moved some stuff around at surface S&R per a reported issue. FIXES #4072

Fixed a bug with the hunting lockers and doors. Security should have access to them now.

Fixed a bug with the Hunting Pen shield generators.

**CAVES:**
Cleared the rock around the outpost, added a new door to allow moving around the exterior.

**EXPLO CARRIER:**
Put the new Bluespace Radio on the table in the gateway prep room.

**WILDERNESS + SKY ISLANDS:**
Overhauled the wilderness shelter! It now has a crew quarters room, First Aid, a second floor, and a utility room. It's only powered by a single advanced RTG that's barely able to keep up with power demand when the place is abandoned, so be sure to bring resources from mining and science to get the other RTG's up and running!

### CODE REVIEW

**Comment by VictorZisthus** [comment]
Chalking up these CI errors to the same issue as with #4255. Joy.

It should be good to merge.

**Comment by Darlantanis** [comment]
Assigning Kassc for map stuff. For code:

Any new _ch.dm files should be placed in the modular_chomp folder unless you intent to send it upstream. 

walltypes.dm and walltypes_vr.dm are missing comments.

What is the purpose of making a new bluespace radio over using the pre-existing bluespaceradio pack?

Making a bluespace radio printable in an autolathe is a firm no by me. That trivializes tcomm issues.

**Comment by VictorZisthus** [comment]
> 

I'd be ok with sending it upstream, but I can move them if you wish!

Whoop. Adding that TODO.

The current one will not connect to our station network by default.

Not BLUESPACE. SUBSPACE. No different from a radio headset. More specifically, this functions as a miner's headset with the downsides of being LOUD and unable to be placed in your ear.

**Comment by Darlantanis** [comment]
Up to you if you want to send any of this upstream, I only push for that whenever it's a bug fix likely to cause conflicts if not sent upstream. Best to move new _ch files to the modularity folder otherwise, we're transitioning to organizing our unique code within said folder to better differentiate our content from upstream and to require less digging should we pursue any module reworks.

Radio should be fine if it's just a standard radio with tcomms connection (assuming there are no clever ways to get around access reqs which I'm unaware of).

**Comment by VictorZisthus** [comment]
It works. Yay.

**Pull request merged**
