### PR TITLE
Fixes Issue#5353

### PR DESCRIPTION
**Pull request by Gittsyyy**
simple fix, misnamed sprite (was p08-e, changed to p08b-e) caused it to not get called when the pistol was unloaded

sorry if this is a sloppy PR, i just saw the issue and thought "hey maybe i could do that"

### CODE REVIEW

**Comment by CHOMPStation2** [comment]
This is an upstream file, so you would want to instead make this PR upstream at Virgo to avoid future conflicts.

**Comment by Gittsyyy** [comment]
good to know, ty. that being said, not at all familiar with virgo, and i dont want to get near their stuff for fear of breaking things

**Comment by Razgriz1032** [comment]
Just make the same PR up there. Our base icon files are exactly the same as their icon files.

**Comment by Razgriz1032** [comment]
Whyyyy did you touch the jukeboxxx

**Comment by Gittsyyy** [comment]
closing bc idk why it added a change to the jukebox even though i very clearly remember not including those changes in this pr

**Pull request closed without merging**
