### PR TITLE
Gateway Update - MoL

### PR DESCRIPTION
**Pull request by FluffMedic**
Gateway update
--Candy mobs have somewhat more proper sprites. Still need to work on proper shading(?) and distinct characteristics.
--VR and Candy mobs have a lore cataloguer tidbit now. Both worth medium points.
--The VR loot armor can now hold oxy tanks
--Engineering room added
--More chambers/fluff has been added near the Vistor section.
--Imperion boss fight altered.
---Phase 3 the mecha tries to fully blitz you in melee, and it gets quite cheesy for this phase and this phase alone. Rather simple but need to make sure you can get out of melee range. (Pretty much took the concept of you're on a time limit and cannot rest in a way that actually functions)
---Phase 4 has had it's attacks altered somewhat, mixing attacks from previous phases...this one may change again.
---Phase 5 same concept as previous iteration, different execution. Increases the reward and possibility of meleeing it. Dodging skills will need to be on point. Have fun with the missile, should hopefully be more fun then the fuel rod.
--Why do I feel like I am forgetting a change I did?

## Changelog

:cl:
remap: The Lab gateway and contents has been tweaked. One of many
/:cl:

### CODE REVIEW

**Comment by FluffMedic** [comment]
Removed the extra period on the nom text.
Fixed biology for the cataloguer for the candy critters, and presence.
VR critters seem fine?
Is prometheans spelled differently plurally?

**Comment by FluffMedic** [comment]
And I have realized I may have made a mistake coding wise, well balancing wise. Time to double check. It is not game breaking.
Aplogizes about the review ping, but since I felt like I fixed the typos, thought it was approritte?

**Review by Raeschen — COMMENTED** [review]
a bunch of 'tour's should probably be 'your's but that's it i think

**Comment by FluffMedic** [comment]
Oh I am an idiot

**Comment by Raeschen** [comment]
'Preadtor' as well.

**Pull request merged**
