### PR TITLE
Ooc panel overhaul (redone)

### PR DESCRIPTION
**Pull request by Kashargul**
## About The Pull Request
Panel:
grafik
grafik

Chatprint:
grafik
grafik

Character Directory:
grafik
grafik

## Changelog

:cl:
qol: allows the ooc panel to be used in field / list mode and adds two more categories for more detailed information
/:cl:

### CODE REVIEW

**Comment by Kazzc** [comment]
Fancy~, hopefully this helps players line up prefs.

**Comment by ItsSelis** [comment]
#### Test Merge Deployed

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: e465f07de84266e4a42f727f3e4a00aac5b303ba
Pull Request: 7d129320b9db494debf2dcb23933d3fe22f6d9d6
Server: b32aa58c169e5ce238271591ab5e531b1bd811d4

##### Comment

</details>

**Comment by ItsSelis** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: e74e05cf27e4e5931ad333efa1f2e3f9927cfbe1
Pull Request: 7d129320b9db494debf2dcb23933d3fe22f6d9d6
Server: 76732b59143f0f4e095bc5068b667980488c6260

##### Comment

</details>

**Comment by ItsSelis** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: 5cf5086241c3b5522b2f9f2dd69c17715a53c470
Pull Request: 7d129320b9db494debf2dcb23933d3fe22f6d9d6
Server: 0b58e8df4e462727d5c418b5db1cd7bf2f36ac98

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: 1aad47a8e960e7bb6644adad3f0c21564f77cdea
Pull Request: 7d129320b9db494debf2dcb23933d3fe22f6d9d6
Server: de2b61600656a4a0d67406185ad1a1b7452cb122

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: e276e65f17eba77caf86b3edc8d904d90b35b701
Pull Request: 7d129320b9db494debf2dcb23933d3fe22f6d9d6
Server: fd3b46b7e17165296bebfd852de6d91013d9e0cc

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: 27f60c19052a0d1de22c906439190a5604d5bd81
Pull Request: 7d129320b9db494debf2dcb23933d3fe22f6d9d6
Server: 24814fdc00ec2bd48884c24bc189ff65557242c6

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: a9a5bdf6f0638e8a360f8f2def45d7ae8cc11587
Pull Request: 7d129320b9db494debf2dcb23933d3fe22f6d9d6
Server: a4b3b03e8d6e6801a2a9d49d0a2a9f4ee9002066

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Updated

<details><summary>Details</summary>

##### Server Instance
CHOMP2

##### Revision
Origin: 4f565d652643c697b19b73b5dcc4bf9f7c3433fe
Pull Request: 7d129320b9db494debf2dcb23933d3fe22f6d9d6
Server: 9a73283c2d30b1475365ac57181c2c64cbf2d003

##### Comment

</details>

**Comment by CHOMPStation2** [comment]
#### Test Merge Removed

**Pull request closed without merging**
