### PR TITLE
Rewiring SC (and other misc fixes) - Deck 0/1/2/3 as well as SifPlains and Centcom zlevels

### LINKED ISSUE #7774: [MAPPING] Trading Ship shelter airlock will not cycle
#### Brief description of the bug
The southern airlock on the trading ship shelter pod does not cycle air. I recently fixed the airlock so the buttons and such work but I could not get the airlock to fully function in my PR, only half function.

#### What you expected to happen
You hit cycle to exterior. The internal doors shut and the air gets vented out of the airlock, then exterior doors open. Vice versa when cycling to interior (filling with air).

#### What actually happened
Currently when hitting a cycle button, the doors shut and you hear the cycle process start. About one second of air cycling happens (usually lowering the pressure to about 80-90kPa) and then the vents make a "shutting off sound" and just stop cycling the air. This leaves the airlock stuck in the cycling process and would need manually aborting and overriding. This isn't a major issue while in round as there are field projectors on this airlock for some reason, but I like it when the airlocks actually work y'know?

### LINKED ISSUE #8233: [MAP] Bridge office and dorms sorting junctions incorrectly tagged
#### Brief description of the bug
Some junctions incorrectly tagged as CMO office

#### What you expected to happen
Tagged package comes out at CMO office

#### What actually happened
Package comes out at dorms

#### Steps to reproduce
- Head to mailroom and use wrapping paper to wrap a random item
- Use the tagger and tag for CMO office
- Throw into disposals

### PR DESCRIPTION
**Pull request by Missile597**
## About The Pull Request
Okay so, this was a crazy thing. Lotta changes, a big rewiring project for the whole station as well as a ton of misc fixes across a few zlevels.

I've drastically reduced the number of APCs directly connected to the mains grid. This should give engineers a lot more control over where the power goes as well as making a lot less areas with 2MW filled doors/vending machines. I've added a new subgrid, complete with its own colour wire to help distinguish it. I gave this change a bit of round stress testing and everything seems to work! Due to the... limited space in SC maintenance, I did have to move a few things around though, however nothing too major was lost/changed. This was a big project but despite having to get a big creative at times, I think it looks alright. I also aimed to prevent running wires through walls or trash piles for ease of access to the cables.

This PR also fixes quite a few map issues that have been plaguing rounds. Most notably the solars issues, some airlock fixes, fixing deck 0 APCs and areas and fixing the disposals sorting junctions. There are a few other small fixes and tweaks too, full list in the changelog.

This PR should resolve issue #7774 and issue #8233 as well.

fixes #7774
fixes #8233

## Changelog
:cl:
add: Added a colourmate to the shadekin hideout
add: Added air alarms to deck three maintenance areas that were missing them, including drop nom spots
add: Added antibody scanners to the relocated virology that had previously been missing
add: Added a new substation for maintenance areas. This substation is for maintenance APCs and the subgrid has a unique pink wire to help differentiate from other subgrids (green) and mains (red)
add: Adds two rusty old breakers to the rage cage for ease of electrifying the arena. One breaker connects to the maintenance subgrid for tame shocks, the other connects to mains for flashy zaps!
add: Added diffusors to some of the deck 0 PD turrets that were missing them to allow them to fire unobstructed
del: Deleted a cable that mistakenly hotwired the command subgrid to mains
qol: Created working prefabs for the new pink wires and added them to the mapping template in case other mappers want to use them
balance: rebalanced something
fix: Fixed some missing atmos pipes on deck 3
fix: Fixed a disposal junction facing the wrong way in the outpost reactor area
fix: Fixed the eastern solars - They now have cable coils placed underneath and work again
fix: Fixed a broken airlock on deck 0
fix: Fixed a broken airlock on the trading ship shelter capsule
fix: Fixed two sorting junctions having incorrect sorting tags, causing items to be missing from the tagger list and causing the CMO tag to be broken
fix: Moved the outpost reactor powernet sensor to be connected to the correct grid (Was previously connected to an "empty" grid)
fix: Fixed the engine room powernet not being correctly wired to the grid
maptweak: Tweaked the northeast solars to be matching and more in line with the other new solar arrays, minus the start of shift wiring of course
maptweak: Added diffusors on lattices in the gaps on the solar arrays so the gaps don't get filled with power wasting shields
maptweak: Rerouted lost and found disposals to take a more logical route so it doesn't go down a zlevel in the middle of the tunnel. Autoresleeving and maintenance adjusted slightly to compensate for space needed (maints got bigger, autoresleeving got a little smaller. No key items removed or lost though)
maptweak: Replaced a few reinforced walls on deck 0 with basic walls to allow for easier locations for building projects in-round. Hazardous (eg space/elevator) and secure (eg grav gen) areas remain encased in reinforced walls for obvious reasons.
maptweak: Rewired deck 1 medical and connected the APCs to the medical subgrid from above instead of the mains grid
maptweak: Rewired (nearly) all corridor APCs to draw power from the central subgrid instead of the mains grid. Docking areas and the vault were left wired to mains for now.
maptweak: Rewired all maintenance APCs to draw power from the new maintenance subgrid instead of mains
maptweak: Added new areas for deck zero and re-assigned these areas to the deck zero maints due to areas being doubled up, causing APC issues with some other maints areas. Removed some excess APCs.
maptweak: Slightly nudges the xenobotany gas vent to space to the side with its diffuser, so that the diffuser doesn't leave a vulnerable gap in the shields by the lab's window for meteors
maptweak: Extended the viro disposal chute and ended it with an outlet and a diffuser - to stop shields from blocking the disposal, and to control its direction of exit. Chute extended to make sure xenobio remains shielded
maptweak: Moved and re-hid the button...
/:cl:

### CODE REVIEW

**Comment by Kashargul** [comment]
## UNIT_TEST: --------------- Port Maintenance(/area/maintenance/port) lacks an APC. (X113|Y135) - Z1)
## UNIT_TEST: !! FAILURE !! [MAP: Area Test APC / Scrubbers / Vents (Defined Z-Levels)]: [1/34]Some areas lacked APCs, Air Scrubbers, or Air vents.

**Comment by Missile597** [comment]
> ## UNIT_TEST: --------------- Port Maintenance(/area/maintenance/port) lacks an APC. (X113|Y135) - Z1)
> ## UNIT_TEST: !! FAILURE !! [MAP: Area Test APC / Scrubbers / Vents (Defined Z-Levels)]: [1/34]Some areas lacked APCs, Air Scrubbers, or Air vents.

Aughhh, taking a look now but I don't think I touched that APC. One moment

**Comment by Missile597** [comment]
Should be fixed now

**Comment by Missile597** [comment]
Substation was deemed too complicated and not wanted. Closing this PR as it's too much of my free time to undo four deck's worth of wiring to keep everything else. The other fixes can be fixed by other mappers and I'll log them accordingly

**Pull request closed without merging**
