### PR TITLE
optimizations

### PR DESCRIPTION
**Pull request by cadyn**
Stole TG's Garbage collector and imported their extools.dll, updated our own rust_g with something that may or may not get added upstream: https://github.com/tgstation/rust-g/pull/60 made widelists faster, also made turfs use widelists for footstep sounds, etc.

### CODE REVIEW

**Comment by cadyn** [comment]
Gonna actually add more to this, so don't merge just yet

**Comment by Novacat** [comment]
This is definably something that should go upstream.

**Comment by cadyn** [comment]
> This is definably something that should go upstream.

I never even finished this, i think there was something fucky with the garbage collector. Only thing that was functional was the widelist for footsteps, which i either moved to a different pr or gave up on, my xxhash function got accepted to the official rust-g repo though if curious, not sure whether they made any new releases since then though

**Comment by Razgriz1032** [comment]
Closing because old

**Pull request closed without merging**
