### PR TITLE
Add a craftable, two-handed sledgehammer.

### PR DESCRIPTION
**Pull request by lbnesquik**
- Can be made out of plasteel, rods and metal.
- Relatively high damage but less than the fireaxe.
- Special sound.
- Inhand sprite
- Mjolnir version for admin abuse.

### CODE REVIEW

**Comment by Ketrai** [comment]
Feels rather weak. Does it have any special functionality?

**Comment by TheFurryFeline** [comment]
Hmm, maybe rename the sound file to smash1_ch.ogg.

**Comment by lbnesquik** [comment]
It is intentionally way under the fireaxe because it is craft able. I could make it closer however.

**Comment by Razgriz1032** [comment]
How do you manage to make the hammer head to start construction?

Also, would you consider slowing down the rate of attack? Just curious.

**Comment by lbnesquik** [comment]
@Razgriz1032 You use plasteel to make the head. Expensive to make it not too common, but not a requirement. 
As for attack speed, sure, if you tell me what variable that is and if it doesn't make the weapon completely underpowered.

**Comment by Razgriz1032** [comment]
I think it'll be fine for now. I'll go ahead and merge.

**Pull request merged**
