### PR TITLE
Infraupgrade

### PR DESCRIPTION
**Pull request by cadyn**
## About The Pull Request
Upgrading a good chunk of the behinds the scene stuffs.

I have not tested this yet! Mainly because I don't have a development database currently setup. Anybody who wishes to test this is welcome, elsewise I will likely get around to it eventually.

## Changelog

:cl:

fix: Fix floating bullets
refactor: DBCore updated to match TGStation
server: TGS DMAPI Updated
server: RUST-G Updated alongwith its DMAPI
/:cl:

### CODE REVIEW

**Comment by ItsSelis** [comment]
[TGS Update](https://trello.com/c/aZFelM9J/39-tgs-update)

**Comment by ItsSelis** [comment]
[rust-g Update](https://trello.com/c/e9pjskrP/40-rust-g-update)

**Comment by cadyn** [comment]
I realized the batch I included did not do the same things as the linux script so I went through the painstaking process of making them do the same thing. Also got rid of dependencies.sh in favor of using _build_dependencies.sh

**Comment by cadyn** [comment]
Okay. This is officially tested and ready for review. I booted up a server with a test database and did a lot of shooting.
image

These 5000 attack logs were generated within the span of a few minutes of me going ham with spam firing infinite buckshot. Using SDQL I'm able to fairly confidently say that there were 0 floating bullets generated during my testing.

Needless to say we need to see this go to live. If it works as well in live as it does in testing, I recommending using spawn() to also detach insert queries for other high volume needs such as dialogue logging.

**Comment by cadyn** [comment]
pain

**Pull request merged**
