### PR TITLE
[TEST] Automated Backup Removal, More Sleevemates

### PR DESCRIPTION
**Pull request by Aroliacue**
Currently, automated backups in the transcore system appear to be enormously detrimental to its performance. This PR is a test to see if the removal of automated backup implants and instead relying on one-time backups from medical kiosks and sleevemates will help with the performance of the server.

WHAT THIS PR DOES:

+ Removes all traces that could be found of automated backups.
+ Removes spawning with an automated backup.
+ Adds in a new medical kiosk to the medbay lobby that allows you to perform one-time backups and medical scans.
+ Adds in more sleevemate devices around the station.
+ Adds sleevemate devices to first-aid vendors.

Mechanically, you only need to be scanned once to have a mind backup, but you may wish to interpret the mind backup's age as a period of memory loss should you be resleeved.

Please leave any outstanding issues with this change in the comments.

### CODE REVIEW

**Comment by BlackMajor** [comment]
Non-chalant reminder that the Transcore subsystem's localised process time is not indicative of its server performance impact.

However, that said, I approve this PR anyway because I hate the narrative impact of remote updating mind scans.

**Comment by Aroliacue** [comment]
Bumping this PR, been about two weeks and I'd still like to see it testmerged if only to confirm that Transcore isn't immensely performance-impacting.

**Comment by Aroliacue** [comment]
For me to revise later:

Crew using resleevers still causes backups to spawn in them post-resleeve.

Setup option to start with a mind backup.

AR glasses should be able to see if someone has a mind backup.

**Comment by Raeschen** [comment]
Remove the [TEST] if this is moving on to fully ready (or nudge me if you need a TM)

**Pull request closed without merging**
