### PR TITLE
Give HoS and CMO Teleport Access

### PR DESCRIPTION
**Pull request by cadyn**
I can understand why RD and CE have teleport access, but I feel like if we're gonna give it to two heads we might as well just give it to all of them. Would make a lot of people's jobs easier as well, especially CMO for surface rescues.

### CODE REVIEW

**Comment by Holdelta** [comment]
As something I've noticed, might want to make sure the turrets inside the teleporter stop targeting heads in general if this goes through.

**Comment by cadyn** [comment]
> As something I've noticed, might want to make sure the turrets inside the teleporter stop targeting heads in general if this goes through.

Giving them access to the teleporter usually makes the teleporter not target them

**Comment by Razgriz1032** [comment]
But have you tested it

**Comment by cadyn** [comment]
> But have you tested it

Yea, ofcourse I did. When I used it, the turrets didn't fire at the CMO or HoS, and both could open the door.

**Comment by Darlantanis** [comment]
Personally not in favor of this. CE/RD are granted teleporter access as part of telecomms access. CMO/HoS/HoP lack access as it is not granted for being Command.

**Comment by cadyn** [comment]
> Personally not in favor of this. CE/RD are granted teleporter access as part of telecomms access. CMO/HoS/HoP lack access as it is not granted for being Command.

I don't really see what the teleporter has to do with telecomms other than having the prefix "-tele". And yeah, I kinda feel like It should be granted for being command, especially CMO would get some really good use out of it.

**Comment by LunarFleet** [comment]
I wondered why this isn't merged yet, so, I'm here now. I want to mention that CMO is **easily** the head of staff who needs teleporter access the most. Rapid responses to the surface are very very useful when dealing with IB, organ failure, etc. CE/RD may have it because of telecomms access, but CMO has just as much reason to have it _due to it shaving a nice threeish minutes off a medical response time_

I make no argument for HoS

**Comment by Razgriz1032** [comment]
I want to say yes

**Comment by LunarFleet** [comment]
Have you considered making your dream something more than a meme, and saying yes? Do not live in the realm of fantasies, do not let reality stop you, you can do it, you can say yes.

**Comment by Razgriz1032** [comment]
I just realized that the turret in the teleporter might aggro if the HoS and CMO aren't on the turret's IFF list. IDK where that list is.

**Comment by cadyn** [comment]
> I just realized that the turret in the teleporter might aggro if the HoS and CMO aren't on the turret's IFF list. IDK where that list is. It might be embedded in the map?

The turrets have a list of access requirements(which is currently just set to access_teleporter) which they check against humans to see if they should or shouldn't be there. Since we gave the CMO and HoS teleporter access with this PR, it'll also make the turrets not aggro them

**Comment by Razgriz1032** [comment]
I'm merging this and we'll see how it goes :P

**Pull request merged**
