### PR TITLE
[WIP] Add the heavy duty drill to the game.

### PR DESCRIPTION
**Pull request by lbnesquik**
This is a fuel powered drill meant to be an alternative to other things. You can upgrade it using parts from R&D or cargo. It needs welding fuel to run. 
I wouldn't mind a code review on this feature. It was a relatively hard thing to make.

It is missing proper inhand and on mob sprites but those are not mandatory, i believe.

### CODE REVIEW

**Comment by Darlantanis** [comment]
You mentioned not needing in-hand and mob sprites. Did you test if this is the case?

Not trying to be rude, we just often get PR's which the creator doesn't test.

**Comment by lbnesquik** [comment]
It uses Chainsaw sprites as of now, so it is sort of okay. The bigger issue is that it doesn't have sprites for the parts.

**Comment by ExabyteDiscord** [comment]
Is this still a WIP? There hasn't been any updates in a while, figured I'd check.

**Comment by Razgriz1032** [comment]
Gonna close this real soon due to lack of progress on the WIP status.

**Pull request closed without merging**
