### PR TITLE
Adds fox, fox2, and syndifox sprites to the AI hologram list

### PR DESCRIPTION
**Pull request by FoxglovePurpur**
<CL>Adds fox, fox2, syndifox sprites to AI holo list</CL>

### CODE REVIEW

**Comment by Darlantanis** [comment]
Code is fine, but as this touches an upstream file either each changed line needs a "// CHOMPedit" comment or a chanced block needs to start with "// CHOMPedit start" and end with "// CHOMPedit end",

Guidelines on our commenting policy can be found here: https://github.com/CHOMPStation2/CHOMPStation2/blob/master/.github/CONTRIBUTING.md

**Comment by FoxglovePurpur** [comment]
Sorry that took me so long! Life n' stuffs! Thank you for you patience <3

**Comment by Darlantanis** [comment]
No worries, though unfortunately this file now has conflicts. Upstream reworked AI holograms a couple days ago, not sure the code here is compatible with the rework. 

PR is here in case it helps figuring out how to tweak the code: https://github.com/CHOMPStation2/CHOMPStation2/pull/5945

**Comment by FoxglovePurpur** [comment]
> No worries, though unfortunately this file now has conflicts. Upstream reworked AI holograms a couple days ago, not sure the code here is compatible with the rework.
> 
> PR is here in case it helps figuring out how to tweak the code: #5945

Everything is fixed now! Sorry that took so long, dear!

**Review by Rykka-Stormheart — APPROVED** [review]
Seems good to go. Walked them through fixing it and confirmed it's working.

**Pull request merged**
