### PR TITLE
[MIRROR] Remove the Exploration Department JK not actually removed

### PR DESCRIPTION
**Pull request by CHOMPStation2**
Original PR: https://github.com/VOREStation/VOREStation/pull/14220
--------------------
https://discord.com/channels/173831852602294272/173896171666931712/971159023263035492

>Removes explorer, field medic, pathfinder
>Renamed 'Explorer' radio channel to 'Away Team'
>changed Away Team radio key to A, changed Talon radio key to Y.
>decreased pilot slots to 2
>increased paramedic slots to 3
>renamed 'access_explorer' to 'access_awayteam'
>various access requirement tweaks relating to exploration removal, and access renaming
>various items renamed relating to exploration removal

>map edits relating to exploration department removal
>added second shuttle to RP
>revised explo shuttle

Map stuff still being worked on.

### CODE REVIEW

**Comment by CMDRYouth** [comment]
They actually removed the Exploration department.
It's merged on Virgo.

**Comment by SlaysInCode** [comment]
Someone could easily start a war by merging this.

**Comment by Razgriz1032** [comment]
Needs chomp comments to show we're keeping it, or we could move it to modular_chomp depending on how integrated this is.

**Comment by Razgriz1032** [comment]
This is such bullshit

**Comment by Razgriz1032** [comment]
Nadyr, I am working on it

**Comment by CMDRYouth** [comment]
Amazing, Exploration is finally gone
At last, the Station will be at peace

**Pull request merged**
