### PR TITLE
Fix #1564

### LINKED ISSUE #1564: RUST Core, Gyrotron, and Injectors Unlinked
All the RUST components are unlinked from the terminals roundstart requiring you to manually enter them in on each respective terminal. This is a bit of an issue if you don't know what each is already pre tagged with.

### PR DESCRIPTION
**Pull request by TheFurryFeline**
Fix #1564

### CODE REVIEW

**Comment by Razgriz1032** [comment]
Oops, actually this already got fixed by https://github.com/CHOMPStation2/CHOMPStation2/pull/1672 when Polaris decided to turbo fuck the R-UUST and I posted it to them.

**Comment by TheFurryFeline** [comment]
No, the tag on the console on the map doesn't have anything set and this is what addresses it. Apologies for not being specific

**Comment by TheFurryFeline** [comment]
It was not fixed with the mentioned PR as that did not edit the map's control console instance, which does not have a tag set.

**Comment by Razgriz1032** [comment]
Oooohhhhh, ok. Got it. Merging this then, thank you.

**Pull request merged**
