### PR TITLE
Adds a living stuffed fox animal to the mob list.

### PR DESCRIPTION
**Pull request by FoxglovePurpur**
## Changelog

:cl:
add: Added more things
imageadd: added some icons or images
code_imp: changed some code
/:cl:

### CODE REVIEW

**Comment by Raeschen** [comment]
Hmm. Can you greyscale this and facilitate color selection? then it can be easily colored

**Comment by FoxglovePurpur** [comment]
I suppose I could try to do that but as it stands right now I'm not sure how to handle the colour selection. Especially considering it's a simple mob. Are there any simple mobs that do that?

**Comment by FoxglovePurpur** [comment]
Are you okay with merging this for now as I try to figure out how to make it recolourable?

**Comment by Raeschen** [comment]
The reason i say is the link between the code and your character. It's better to facilitate an item that can be used/customised by all whilst still being customised to you, instead of hardcoded to you. Kassc has experience greyscaling this stuff and a customise color verb i think is already available.

Also, your changelog entries are still the defaults.
And, you're missing a closing tag for the CHOMP edit block in an upstream file.
Please wrap edits with both
//ChompEDIT START
... code ...
//ChompEDIT END

**Comment by FoxglovePurpur** [comment]
Fair (also there is literally a "Rykka" dire wolf, smh). And ah! I had no clue how the changelog worked. I assumed it was purely for tagging so I didn't change anything out of risk of it breaking somehow.
I was going to see about adding the other coloured fox stuffies, but I have no clue how to make it work "colourless" for you to pick your own colour.

**Comment by Raeschen** [comment]
> Fair (also there is literally a "Rykka" dire wolf, smh). And ah! I had no clue how the changelog worked. I assumed it was purely for tagging so I didn't change anything out of risk of it breaking somehow. I was going to see about adding the other coloured fox stuffies, but I have no clue how to make it work "colourless" for you to pick your own colour.

that should probably be removed. No self inserts or special treatment is a pretty strong rule here. Again, ask Kassc. all you do is greyscale the sprites and then give it this proc; 

https://github.com/CHOMPStation2/CHOMPStation2/blob/393409766f3f7d202ef5e6d03070ad9bc7ca3701/modular_chomp/code/modules/mob/living/simple_mob/subtypes/vore/wolf.dm#L3C5-L3C52

**Comment by FoxglovePurpur** [comment]
I'll close this PR and see about fixing it before reopening it. Or would it be better to open a brand new PR?

**Comment by Raeschen** [comment]
> I'll close this PR and see about fixing it before reopening it. Or would it be better to open a brand new PR?

You can leave it open, set it to draft, or close it. up to you. Setting it to draft is perhaps the easiest. I don't mind.

**Comment by FoxglovePurpur** [comment]
I have other projects I'll work on first. Such as adding more teshi outfit sprites. Adding a few requested borg sprites. ETC. Thank you for pointing out these flaws and giving me suggestions and resources to change n' fix this, Rae! It means a ton~ <3

**Pull request closed without merging**
