### PR TITLE
[MIRROR] Updates Traveller's Guide with new species lore

### PR DESCRIPTION
**Pull request by CHOMPStation2**
Original PR: https://github.com/VOREStation/VOREStation/pull/14172
--------------------
Replaces blurbs with cataloguer information when able.

Otherwise, using wikipedia blurbs.

Added Rapala and Altevians and Drones and Cyborgs.

Edited positronic lifespan to follow Synthetic lore on wiki

Wrote custom text for drones and cyborgs, in spirit of the Synthetic Page.

Deleted ancient "TODO" commented out lore as that will never be relevant again. We'll just use the wiki where needed.

Government, locations etc untouched for now. They're on the TODO list.

Also TODO: potentially edit language so it is consistent across blurbs.

Also added an OOC note on the main page to warn that this book contains IC bias, and to consult the wikipedia's backstory entry for objective lore.

### CODE REVIEW

**Comment by tacoguy7765093** [comment]
teshari lore on strike

**Comment by Raeschen** [comment]
do we really wanna axe all the etshari lore stuff...?

**Comment by tacoguy7765093** [comment]
I asked upstream, they said is to normalize the content to other species

**Comment by Raeschen** [comment]
Hardly seems "normalised" given the relative scale of what's left of teshari to what's present in other species.

This is also a note for our codebase only.

**Comment by Darlantanis** [comment]
nah

**Pull request closed without merging**
