### PR TITLE
[MIRROR] Taurloafs Expansion

### PR DESCRIPTION
**Pull request by CHOMPStation2**
Original PR: https://github.com/VOREStation/VOREStation/pull/14781
--------------------
Ports up some loaf expansion from downstream. It is time to become 🍞.

Yeah I got a little lazy with it but resolving dmi merge conflicts is a particular kind of hell I don't wish on anybody. This way feels easier.

### CODE REVIEW

**Comment by Verkister** [comment]
Upstream PR has 8 files. Mirrorbot done a fucky wucky.

**Comment by Verkister** [comment]
Unless they just ported the entire files without any edits, which may be the case considering they ported all the chompedit comments along the stuff :v

**Comment by Verkister** [comment]
yeah nothing worth merging here

**Comment by Darlantanis** [comment]
KEK

**Pull request closed without merging**
