### PR TITLE
Updating POIs

### PR DESCRIPTION
**Pull request by FluffMedic**
Attempting to update my POIs. To make them bearable to look at, up the difficultly, but also to increase the shinnies.

Ambush Base
Lore: After finding some strange artifacts in the water, a smaller company hired out contractors to try and salvage as much useful loot as they can, preferably undetected, but not witnesses. Changes
-Added more foes, including a mercenary trained giant fish. -Swapped the cafe for a 'diving' room, changed the old living quarters to a 'xenoarch' room, shifted the location of the 'leader' room, putting the armory between it and the new living quarters area. -Made it so the mercenaries are trying to fish out artifacts from the lack. -Added 3rd sniper spot, but the APC is much easier to access. The person who built the base was shortly fired. -A team of 4 can be equipped with armor and weaponry.

Cult Bar
-The demons and cultists shouldn't fight now. At least this POI's demons. So also added more of them. -Made the 'boss' room quite a bit rougher, but two new goodies lay within. -There is now a large table of random items they took from their previous victims...although their body is sprawled throughout most of the facility. -The bar is now split up into further sections. Well, the 'gambling' area is now properly separated. -Added creepy grass, and some plant life.
-Theoretically a team of 4 could roleplay as cultists. -Kitchen has food.

Mech Bunker
-Made the bunker more carved into a cave.
-Added a 3rd mech.
-Made the some wrecked mechs loot piles.
-Changed the loot inside the small room.

Now, in the high likely hood I messed something up, I'll try to fix it as soon as I can. And if needed, do feel free to close this one if it gets in the way.

### CODE REVIEW

**Comment by Verkister** [comment]
The previous version of mech bunker had wrong air mix on the tiles that are open to sif atmosphere and that causes roundstart active edge issues.

Sif atmos for reference:
temperature = 243.15
nitrogen = 93.7835
oxygen = 20.7263

Also for maintainers: Once you're done sitting on this PR, make sure to merge this PR https://github.com/CHOMPStation2/CHOMPStation2/pull/5184 before merging this one because I ended up touching the previous version of the POI on it and don't want it to revert the updated version here.

**Comment by FluffMedic** [comment]
Sorry about the delay to this comment.
Is this still an issue, or related to the issue that you fixed the other day?

**Comment by Verkister** [comment]
Hmm maybe, maybe not. The open entrance between the hangar and the outside still does connect a zone of standard air and a zone of sif air, but looks like the active edge alert had ignored that spot when it had caught the zonedivider+openspace edge the poi had randomly landed on, so it might be okay.

**Comment by Kazzc** [comment]
Thank you, pretty good stuff.

**Comment by FluffMedic** [comment]
Could this get unmerged?
I just realized I made a mistake, putting the files in the wrong places.
I will make a new PR to fix things if that is an easier action.

**Pull request merged**
