### PR TITLE
Teshari's have a sound on *scream now.

### PR DESCRIPTION
**Pull request by BlackMajor**
Areli mused about it so I did it.

Sound taken from a Cockatoo screaming, edited to be a little less jarring on the ears.

### CODE REVIEW

**Comment by Darlantanis** [comment]
Unless you've submitted this upstream, you'll need CHOMPedit comments to avoid upstream conflicts.

**Comment by BlackMajor** [comment]
> Unless you've submitted this upstream, you'll need CHOMPedit comments to avoid upstream conflicts.

Bet

**Comment by Darlantanis** [comment]
This includes emote.dm

**Comment by BlackMajor** [comment]
> This includes emote.dm

Fug

**Comment by Darlantanis** [comment]
Doof

**Pull request merged**
