### PR TITLE
[READY TO MERGE] Public Sheet Storage, Timeclock Changes

### PR DESCRIPTION
**Pull request by Aroliacue**
:cl:
qol: Timeclock cooldown down to 1 minute, everyone can set anyone else to off-duty.
maptweak: Moved science's sheet storage to lobby to make it publicly accessible. Changed it to persistent lossy, which means stored sheets will transfer between rounds at a loss.
/:cl:

### CODE REVIEW

**Comment by Aroliacue** [comment]
image

**Comment by CMDRYouth** [comment]
Now miners can use all those Sheet Snatchers themselves, and they won't need Science to be present to drop off materials.
Similarly, now people can withdraw materials (IE Medical with Phoron) for their own wants and needs.

**Comment by CMDRYouth** [comment]
Downside:  Scientists will lose that specific spot as a popular Battery Charger location.  They might have to start using the other window.

**Comment by Aroliacue** [comment]
image
The sheet storage has been moved to cargo instead. It'll still retain its public access, though cargo has more oversight over it now.

**Comment by Kazzc** [comment]
Think you can make an admin-log anytime the timeclock is used? location/ckey/item logs will be helpful.

**Comment by Aroliacue** [comment]
This PR is finished and ready to be merged (once feature freeze is over)

**Comment by Raeschen** [comment]
this one gets a pass due to being a TM before the freeze

**Pull request merged**
