### PR TITLE
Adds a VR room and a functioning VR map for all your sandbox needs.

### PR DESCRIPTION
**Pull request by tacoguy7765093**
The VR sleepers were a great concept but I was disappointed to find out it was broken polaris code with its last commit being back in 2019, so I decided to use some really jank ass code to fix it, I would have re-written the code but I have none of that skill just yet.

VR is a way to get to a virtual world as YOU, with all the tools, guns, and toys at your disposal, all without the risk of death!
Dying in VR sends you back into the real world with none of the injuries (But the pain still persists!). Ghosting or using the exit-virtual-reality verb will send you back to the station instantly too!

dreamseeker_G19LV4pqaf
An image of one of our crewmembers curiously looking among the room. (Thank Kassc for mapping this in SC)

The current map is sc_excess_construct, with various areas to roleplay, shoot, build, and do anything one can wish with all of the fun stuff, all in the safety of VR! From a nice warm beach to a cozy forest, the epic battles of ship to ship combat to the blood filled corridors of demons. There are many little secrets to look around in that isnt included in the screenshots!

Images will be in the comments below

CONCERNS:
The map downloaded into the VR pods are currently and beta and are placeholders, expect bugs!
Someone can technically kill themselves as many times as they want causing corpses to pile up,  Nanotrasen dev team might need a trash cleanup system.
This map was unable to be lateloaded similar to gateways, so it loads on world start, (This might need to be fixed!!!) -FIXED-,

Due to concerns, this does not trigger crew's existing backup implanters, (at least getting in VR, and aghosting for 15 minutes)

Do scream at me for any bugs, I early merged #4742 on my end to see if things got fixed to no avail, shouldn't affect things.

### CODE REVIEW

**Comment by tacoguy7765093** [comment]
Also that unrelated commit of conveyor belts was removed.

**Comment by tacoguy7765093** [comment]
what the hell was I thinking yestarday?

**Comment by Kazzc** [comment]
I'm not working on this until I finish the desert planet tiles.
I am fine with the current WIP map, I'll make something more substantial later on.

**Comment by tacoguy7765093** [comment]
#4909 is open which has just the barebones fix without the map, will adjust later to prevent conflicts, but the base code will exist for the map now.

**Comment by tacoguy7765093** [comment]
conflicts fixed

**Comment by tacoguy7765093** [comment]
Thanks to Kassc, we have completely redone the map from the small construction area to a fully fledged areas for roleplay, deathmatch, building, and more, with various themes your local space faring spessman can go to without having to leave Southern Cross!

The full map

dreamseeker_dYWh6WvWdK
Construct

dreamseeker_yxqTcUrB1E
Lava Geyser


StrongDMM_jobJlHDhwx
Forest

StrongDMM_gRybMPWb0O
Beach

StrongDMM_q567Cbfn9e
3 Ship Spawnpoints are an option


StrongDMM_7D6vt9tKbS
Spooky Cult place


Good thing this is all a video game, with no chance of anything to get on station.

...also
dreamseeker_Sewz698zNw

**Comment by Kazzc** [comment]
This was fun to fuck around with, I can't think of anything else I can do to help this project. Now lets see how it runs on the server!

**Comment by tacoguy7765093** [comment]
Alright: Day 1 of feedback and here is the changelog
-Dead bodies get removed after 5 minutes for antilag, any gear will drop on the ground
-9 Black Duffels on construct spawn
-Matchboxes and more candle packs in the buildings without em
-Adds a basics vendor in spawnroom for construct
-Removed Resleeve console in cult base that wasn't supposed ot be there
-Holokits given out in construct spawn for specific clothing choices
-Adds spawnpoint for cultist base
-Suit Cycler in space entrance
-Populates tables in beach with a few beers and stuffs

**Comment by tacoguy7765093** [comment]
-Replace space tiles to work with momentum
-Add lights in mech factory and a suit dispenser
-Rename mech factory spawnpoint with abandoned in it
-Cultist Base Medbay has surgery table
-Nudity Permit given 
-Decor
-Every spawnpoint has clothing now

**Comment by tacoguy7765093** [comment]
Vox and Zaddat now spawn with their gear


I also removed the arbitrary sleep so vox dont drop their can

**Comment by tacoguy7765093** [comment]
There is a seperate fix Verki is working on  for false transcores

-Remove crash consoles that break the MC
-Remove access reqs on robotics and RD equipment there
-Tiny Fans
-Fixed a few misplaced airless tiles
-Added a few things for sci ship
-More funny secret guns, go get your inner gamer

**Comment by tacoguy7765093** [comment]
Oh yeah I removed the RD labs because of people starting to go out of their way and leave VR

Research also syncs between realities, and I tried to finnagle with the sync variable and the id variable but the RD can just resync the machines right back.

**Pull request merged**
