### PR TITLE
[MIRROR] Vore transform overhaul

### PR DESCRIPTION
**Pull request by CHOMPStationBot**
Original PR: https://github.com/VOREStation/VOREStation/pull/9191
--------------------

Instead of the derpy, broken ass transform modes, you can just now open a damn appearance changer panel. For feature parity, the appearance changer (in all instances including mirrors... don't question how a spider taur can look in the mirror and become a fat wolftaur, it's *fine* >.>) is now able to style ears, tail, and wings.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
This looks great. We need a bundle rebuild.

**Comment by Darlantanis** [comment]
Very good. When do I get the perms in mirror bot which will let me commit new bundles (though not sure that'll fix the github conflict).

The conflict in bellymodes_datum_vr.dm looks tricky to resolve. I can take a crack at it when less exhausted.

Questioning the large swathe of code deleted in transforming_vr.dm instead of, you know, just commenting out.

**Comment by Razgriz1032** [comment]
Bellymodes has been resolved.

I poked Cadyn about it and you have access invite in your email now

**Comment by Darlantanis** [comment]
I've made a mess of the commit logs figuring out how to resolve github conflicts on the tgui bundle but everything EXCEPT the bundle is fine now. Bundle fix incoming...

**Comment by Darlantanis** [comment]
bundle fixed

**Pull request merged**
