### PR TITLE
Capture Capsules

### PR DESCRIPTION
**Pull request by Sharkmare**
Prototype capture capsules.
Currently can capture any simple mob and release it, nothing more.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
Gonna close this real soon due to lack of progress on the draft status. Also it'd need a refresh for travis.

**Comment by Razgriz1032** [comment]
It doesn't seem to capture. It just bonks mobs and they turn passive. Throwing the object again at the passive mob deletes the object.

**Comment by TheFurryFeline** [comment]
Isn't this what the stasis cage does?

**Comment by Sharkmare** [comment]
> Isn't this what the stasis cage does?
> https://github.com/CHOMPStation2/CHOMPStation2/blob/f914803532654806fc0004d85a937c6c5c86bcc3/code/game/objects/structures/stasis_cage.dm

Guess that's a feature then now on our current base and doesnt need adding.

**Pull request closed without merging**
