### PR TITLE
Metamorphic Pint Glass (CHOMP re-addition)

### PR DESCRIPTION
**Pull request by Darlantanis**
Re-addition of a CHOMPstation feature. This PR has also been submitted upstream. 

So you don't need to choose between aesthetics and volume.
-Adds a metamorphic pint glass, a 60 unit version of the metamorphic glass.
-Adds 10 metamorphic pint glasses to the booze-o-mat.
-Adds an icon for the metamorphic pint glass to drinks.dmi
-Fixes metaglass sprites for mojitos and goldschlager.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
This PR is currently unacceptable. Please observe that we are now putting custom chomp-created drink icons in drinks_ch.dmi. This file is currently in the github repo and already includes the mojito you are trying to add.

You can also separate out code from metaglass.dm. The following two blocks of code can be chucked into a new file called metaglass_ch.dm, straight-up. You will also need to include a new environment file with this metaglass_ch.dm enabled.

`/obj/item/weapon/reagent_containers/food/drinks/metaglass/metapint
	name = "metamorphic pint glass"
	desc = "This glass changes shape and form depending on the drink inside... fancy!"
	icon_state = "pglass_empty"
	volume = 60
`
`/datum/reagent/ethanol/mojito
	glass_icon_state = "mojito"`

**Comment by Darlantanis** [comment]
This has been rebased to prevent conflict and merged upstream. https://github.com/PolarisSS13/Polaris/pull/6659/files

**Comment by JesusChristItsJasonBourne** [comment]
nothing in here looks broken to me

**Comment by Razgriz1032** [comment]
This has been merged upstream
https://github.com/PolarisSS13/Polaris/pull/6659

Approved.

**Pull request merged**
