### PR TITLE
adds some new bodysprites

### PR DESCRIPTION
**Pull request by zeskorion**
## About The Pull Request

adds new sprites:
-soft belly fuzz, a more round belly color sprite. Comes in male and female variants, and also has navel and navel-less
-chitin bellies, in male and female variants, with transparent scutes that you can put color underneath
-big chest fuzz
-extra eyes, just two pixels aligned to hit the corner of anime eyes
-cloaklike wings with separately colorable eyespots
-a different antenna shape, and a variant with cat ears

Yea, this is mostly just self indulgence, but i'm sure these will come in handy for general use, hence all the variants and greyscale

## Changelog
:cl:
add: adds new bodymarkings, "ears", and wings.
/:cl:

### CODE REVIEW

**Comment by zeskorion** [comment]
think i have a fix

**Comment by zeskorion** [comment]
alright, everything is work and good 2 go

**Comment by Darlantanis** [comment]
Hey there. ears.dmi is an upstream file which cannot be edited on our end; you will need to use either a _ch.dmi file or a .dmi file in the modular_chomp folder.

sprite_accessories_ear.dm is also an upstream file, so any edits there will need to be marked with //CHOMPedit comments.

Rest looks good.

**Comment by zeskorion** [comment]
> Hey there. ears.dmi is an upstream file which cannot be edited on our end; you will need to use either a _ch.dmi file or a .dmi file in the modular_chomp folder.
> 
> sprite_accessories_ear.dm is also an upstream file, so any edits there will need to be marked with //CHOMPedit comments.
> 
> Rest looks good.

alright, wasnt sure about how modular stuff was. not very experienced with modular code

**Comment by zeskorion** [comment]
> Hey there. ears.dmi is an upstream file which cannot be edited on our end; you will need to use either a _ch.dmi file or a .dmi file in the modular_chomp folder.
> 
> sprite_accessories_ear.dm is also an upstream file, so any edits there will need to be marked with //CHOMPedit comments.
> 
> Rest looks good.

alright, done!

**Pull request merged**
