### PR TITLE
Makes certain scening NIF programs have less wear

### PR DESCRIPTION
**Pull request by theXDkidoflol**
## About The Pull Request
Server priority is vore, then roleplay, then gameplay. As it stands, the six point durability loss from getting size changing makes it an absolute pain in the ass to use consistently. This should fix that.

## Changelog
Makes the size changing NIF app do less damage to your NIF.
Makes the Compliance NIF app do less damage to your NIF.

:cl:
balance: Size and compliance NIFs drain durability much less.
/:cl:

### CODE REVIEW

**Comment by theXDkidoflol** [comment]
ignore my commit garbage this is my first time putting out a pull request in like a year

**Comment by theXDkidoflol** [comment]
oh what the hell why is it changing 195 files

**Comment by theXDkidoflol** [comment]
the enigmatic beast is appeased

**Comment by Aroliacue** [comment]
Very cool

**Pull request merged**
