### PR TITLE
Cadyn's ballistics overhauls part 1

### PR DESCRIPTION
**Pull request by cadyn**
So, despite the number of lines changed here, the mechanical changes are actually pretty simple. Most ballistic guns now have mechanics for bolts and chambers, so you have to chamber a round to get automatic guns going, and pulling out the magazine will still leave a bullet in the chamber, etc. There is a differentiation between closed and open bolt guns as well, with what you are able to do with each being quite different. 

These changes did not affect the following guns: Pump shotguns, revolvers and revolver type guns, breach loaded guns, or any of the current bolt action guns we have. (Although, there's room for new bolt action guns to be added with the system I created.)

### CODE REVIEW

**Comment by Razgriz1032** [comment]
BRRRRRRRRRRRUH...


I bet Yawn would love these.
I'll have to test this to be sure. Or a test merge on live could do!

**Comment by cadyn** [comment]
> BRRRRRRRRRRRUH...
> 
> I bet Yawn would love these.
> I'll have to test this to be sure. Or a test merge on live could do!

Yawn should have gotten a mirror bot and maybe I would have shared :p
Somebody 'ought to ping me if they yoink it though, I've been waiting for one of our upstreams to steal some of our cool stuff.

Also, me and Blitz did some testing of this already, ofcourse. I'm sure there's still a bug here and there, but it's probably gonna be better to test this on live and iron out the bugs from there (Plus, I'm usually pretty quick to iron bugs for my own content)

**Comment by Shadow-Quill** [comment]
Yawn will get it whenever this gets ported to Virgo, and they do their monthly downstream -- though from what I've heard, YW is fairly dead.

**Comment by Darlantanis** [comment]
Assuming virgo (or polaris) takes it. I could see polaris being interested, little unsure about virgo.

**Comment by r4d6** [comment]
Quick Question : Will this PR add a check for the 'put gun in mouth' action to check for the lethality of the weapon? Because currently even if you use the size gun it kills you.

**Comment by cadyn** [comment]
> Quick Question : Will this PR add a check for the 'put gun in mouth' action to check for the lethality of the weapon? Because currently even if you use the size gun it kills you.

I thought this was already fixed, but no, this PR has nothing to do with that.

**Comment by r4d6** [comment]
> > Quick Question : Will this PR add a check for the 'put gun in mouth' action to check for the lethality of the weapon? Because currently even if you use the size gun it kills you.
> 
> I thought this was already fixed, but no, this PR has nothing to do with that.

Alright, thanks anyway.

**Pull request merged**
