### PR TITLE
Science PA

### PR DESCRIPTION
**Pull request by VictorZisthus**
Gives science a PA at roundstart.

### CODE REVIEW

**Comment by VictorZisthus** [comment]
CI random generation induced check failure, yay.

**Comment by VictorZisthus** [comment]
Drafted until Kazzc Gives the green light to merge, then I'll absolve merge conflicts.

Waiting on #4870 to get merged first.

**Comment by Razgriz1032** [comment]
Conflicts. Also this time I will merge it myself since Kassc hasn't reviewed

**Comment by VictorZisthus** [comment]
Closing to open a new PR to absolve conflicts. See #5455 now.

**Pull request closed without merging**
