### PR TITLE
Fruit TRUE/FALSE

### PR DESCRIPTION
**Pull request by Shadow-Quill**
because using `TRUE`/`FALSE` for bools is Good

### CODE REVIEW

**Comment by cadyn** [comment]
using 1/0 is more space-efficient

**Comment by cadyn** [comment]
`ShadowQuill.in_balls = 1`

**Comment by Shadow-Quill** [comment]
> using 1/0 is more space-efficient
Coding standards.
We can use `#define tiles_per_tile 1`, but we don't because standards. We use `#define TILES_PER_TILE` instead to make it clear that it's a macro. same thing with TRUE/FALSE, takes a quick glance to tell that's it's actually a boolean.

**Comment by Shadow-Quill** [comment]
> `ShadowQuill.in_balls = 1`

We'll talk later~

**Pull request merged**
