### PR TITLE
4 new VBOS (second attempt)

### PR DESCRIPTION
**Pull request by Hunter-Dovetail**
## About The Pull Request

SECOND attempt, thanks Kash for letting me know, I think I know what my mistake was.

## Changelog
:cl:
add: VBO_maw23
add: VBOanim_belly8
add: VBOanim_belly9
add: VBOanim_belly10
/:cl:

### CODE REVIEW

**Comment by Kashargul** [comment]
The asset sizes we are reaching here is worrying me some. 15MB files are massive for a single asset.  Have those been tested not to impact stability?

**Comment by Hunter-Dovetail** [comment]
> The asset sizes we are reaching here is worrying me some. 15MB files are massive for a single asset. Have those been tested not to impact stability?

I made larger ones with Kasssc before and they were fine, all, (except the pixelated gifs) I put in myself, and they're apparently ok.

**Comment by Hunter-Dovetail** [comment]
> > The asset sizes we are reaching here is worrying me some. 15MB files are massive for a single asset. Have those been tested not to impact stability?
> 
> I made larger ones with Kasssc before and they were fine, all, (except the pixelated gifs) I put in myself, and they're apparently ok.

Also, I've been asked to let you know not to worry as idb won't render out a large file and it has to be verified manually

**Comment by Drulikar** [comment]
Currently modular_chomp/icons/mob/vore_fullscreens/VBOanim_belly10.dmi, modular_chomp/icons/mob/vore_fullscreens/VBOanim_belly9.dmi, and modular_chomp/icons/mob/vore_fullscreens/VBOanim_belly8.dmi

appear to be animated in VSC dmi preview (just takes it a bit to render)

As far as size compared to other files: 
image

So I don't know as far as stability what its like, but if thats an issue, its not something unique with this PR.

**Comment by Verkister** [comment]
belly9 and belly10 have incorrect resolution 120x120. Should be 480x480

**Pull request merged**
