### PR TITLE
maintexpansion

### PR DESCRIPTION
**Pull request by miniusAreas**
This PR adds three new rooms to the deck three (top floor) tunnels. These are - 

A Teshari Den (Has clothes, nests, nice plush carpet floor for pack-based group activites ((v)orgies) or whatever you wana do as tesh.

image

A tunnel dorms and strip club - perfect for that kinky non-con you wana do, or being a professional slut for everyone while off duty. (kinky clothing, stripper outfits and pole included)

image

Lastly, a rather dingy and bland trading spot for those of you keen on selling your (il)legal maint loot.

image

All of these have been tested for power / lighting and other things. Everythings in order.

### CODE REVIEW

**Comment by miniusAreas** [comment]
haha I can't remember to give my PRs funny names

**Comment by Kazzc** [comment]
H-hrrrmmffff. . .
It's somewhat tasteful but I may need to consider a few things, I am not against the idea of adding abandoned rooms for the sake of RP but I may get around modifying and sprucing them up a bit more.
There are a few things you want to consider in regards of making secret rooms is that they have to be secret at best. The design is interesting but just to obvious as it literally has doors to access said secret areas.
between either being an abandoned room or a built in secret room needs to have a design of being under-construction or an abandoned project. If its a secret room then it must be hidden enough that one can't just walk in by accident.
If you can send me the map files I can probably work around with it, but I will say just cause of how easily they are to access (As it literally has a door to get in them).

**Comment by miniusAreas** [comment]
I can make the changes myself. Still have the file up in FDMM2. Will get to another commit shortly.

**Comment by Kazzc** [comment]
https://cdn.discordapp.com/attachments/528973352728264714/814733568303300638/unknown.png
https://cdn.discordapp.com/attachments/528973352728264714/814733618600738826/unknown.png
https://cdn.discordapp.com/attachments/528973352728264714/814733738822598676/unknown.png
https://cdn.discordapp.com/attachments/528973352728264714/814733800122744842/unknown.png

**Comment by miniusAreas** [comment]
@Kazzc Looks okay to me with one sidenote - the door into the room with the single softwall is locked behind Engineering access, hence why I made a tiny passage along the side of it. Any ideas?

**Comment by Kazzc** [comment]
It's bulging out, reason it bothers me greatly as if you try to go up from a floor behind you will get a prompt that you can't. The mindset of it being a secret room is that it has to fit with the contour of the station shape.
Reasoning I added weakspots instead. You can make secret entrances by welding the wall, unwrenching the girder and apply steal to make a fake wall.

**Pull request merged**
