### PR TITLE
Hypothermia!

### PR DESCRIPTION
**Pull request by cadyn**
Added hypothermia with a variety of symptoms that develop slowly over time. Makes dying from the cold a bit more interesting, and also adds negative effects for some temperatures that previously you would be able to get away fine in. No more stripping naked in -30 degree weather!

Also, yeah, sent this way upstream to polaris.

### CODE REVIEW

**Comment by cadyn** [comment]
Also closes #423

**Comment by Somememeguy** [comment]
Just a quick question- have you made sure that synths aren't effected by this?

**Comment by cadyn** [comment]
> Just a quick question- have you made sure that synths aren't effected by this? Same for teshari, tajaran, etc, at least to an extent anyways, since they all are known to survive reaallly cold temperatures.

Yeah, if you check the code the temperature at which it affects you is based on your species.

**Comment by cadyn** [comment]
Converting to draft because of the shenanigans going on over on the polaris repo. Will re-open it with the final changes once I get the polaris PR merged.

**Comment by Shadow-Quill** [comment]
Stale PR is stale-

**Comment by cadyn** [comment]
> Stale PR is stale-

Yell at Atermonera for not getting around to re-reviewing my PR Lol

**Pull request closed without merging**
