### PR TITLE
[MIRROR] Changes wall damage from being (usually) 25 brute to 12 and doesnt add a stun to it

### PR DESCRIPTION
**Pull request by CHOMPStation2**
Original PR: https://github.com/VOREStation/VOREStation/pull/15950
--------------------
25 damage for a wallthrow is pretty extremely high. That's higher than some low calibre bullets! It also turns bones into powder because your bones are made of glass. This makes the damage lower but it has a stun when you hit wall because oof ouchy. I dont think "speed" is ever passed in so the default value of 5 was always used. Consistency is also nice

### CODE REVIEW

**Comment by cadyn** [comment]
boo womp

**Comment by TheCaramelion** [comment]
25 is funny because you can get a teshari in crit in only two throws

**Comment by ReoDaProtovali** [comment]
> I don't like this personally because generally it's intentionally pretty tough to throw someone at a wall (you have to blue grapple them, and wait a bit iirc) and also murdering someone by throwing them at a wall is hilarious

Actually you can throw people the moment you reinforce to blue, tabling is waiting for blue to fully charge

**Comment by SilencedMP5A5** [comment]
another CQC nerf... 😔

**Comment by Kashargul** [comment]
Don't just close, we need to mark the changed section

**Pull request merged**
