### PR TITLE
Warrants can only get authorized by people with HoS access now

### PR DESCRIPTION
**Pull request by Shadow-Quill**
Via Warrant Assistant. Minor change to capitalization on the search warrant, and no edit comments as this'll be ported upstream.

Tested & working without runtimes.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
How far upstream and when?

**Comment by Shadow-Quill** [comment]
Polaris upstream and https://github.com/PolarisSS13/Polaris/pull/6681

**Comment by TheFurryFeline** [comment]
Map conflict.

**Comment by Shadow-Quill** [comment]
Will fix conflict later, Polaris nixed the PR so it's now going to Virgo, tomorrow.

**Comment by Shadow-Quill** [comment]
Conflicts fixed, plus instead just put a warrant device in each locker & spare box in the small tech storage

**Comment by TheFurryFeline** [comment]
Since MapDiffBot is currently broken and doesn't really work for map files with multiple z-levels, which will get changed somewhere down the line, maybe a screenshot or some of what's changed? The filediff seems like it's more than adding a warrant device per locker and a box in the tech storage.

**Comment by Razgriz1032** [comment]
Hmm. This will need another map tweak since the casino edit. I'm mostly holding off on this update until Virgo merges. But we have decided to go ahead and accept this. Can you make a map edit one more time with the newest version of the map?

**Comment by Shadow-Quill** [comment]
Virgo merged, and I'll get the map update done when I have some time. May
be a bit, though.

**Comment by TheFurryFeline** [comment]
Conflicts to be resolved, still.

**Comment by Razgriz1032** [comment]
I think we have this now, now that we have done a pull from upstream.

**Comment by TheFurryFeline** [comment]
Ah yes, so we do.  Still need to be mapped in, I think. Will add to the mini-fixes, if that's alright

**Pull request closed without merging**
