### PR TITLE
Adds event pref to character directory at Kassc's request

### PR DESCRIPTION
**Pull request by BlackMajor**
Title.

Can't put //chompedit comments in the tgui script, btw.

### CODE REVIEW

**Comment by BlackMajor** [comment]
kek, all those commits. This is what I get for PR'ing on master.
Remember to squash commits when merging.

**Comment by Razgriz1032** [comment]
How do I squash commits when merging :seensomeshit:

**Comment by BlackMajor** [comment]
> How do I squash commits when merging :seensomeshit:

image

**Comment by Darlantanis** [comment]
Usually we add a descriptive comment block in .js files instead of in-line. Refer to VorePanel.js for an example.

**Pull request merged**
