### PR TITLE
Casino prizes!

### PR DESCRIPTION
**Pull request by Shadowfire117**
title

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Conflicts, probably from not being updated after the main PR was merged in.

**Comment by Shadowfire117** [comment]
I know, but I dont have permission to resolve conflicts!

**Comment by TheFurryFeline** [comment]
It's... Your own PR? Should be able to click the button

**Comment by Razgriz1032** [comment]
This issue is caused by you not working with an up to date repo. Download a new clone, repeat your work, and make a new PR.

**Comment by TheFurryFeline** [comment]
He could also just as easily update from his master branch, not download a new clone entirely?

**Comment by Shadowfire117** [comment]
that storage_ch.dmi I have just made with casino commit

**Comment by Shadowfire117** [comment]
Closing this pull request and making a new one, even though it was up to date compared to the files it was changing, making a new pull with older branch updated to origin and then applied the files changed.

**Pull request closed without merging**
