### PR TITLE
[MIRROR] Move like every clothing icon file

### PR DESCRIPTION
**Pull request by CHOMPStationBot**
Original PR: https://github.com/VOREStation/VOREStation/pull/11002
--------------------
MMMMMM. That was fun.

Note to downstreams: This removes the `_s` required at the end of every uniform-slot-clothing icon state. You might need to just rename some states in your dmis. Shouldn't need any code changes. If this DOES mean you need to do code changes, then you were probably unnecessarily specifying what icons clothes use when they could have inherited it.

image

I think this will be easier for people to understand. Glasses in eyes/item.dmi for the items, eyes/mob.dmi for the mob, etc.
No more "Well it's icons/obj/glasses.dmi for the item and icons/mob/eyes.dmi for the mob sprites" or just having zany names.

I'm sure uh, I broke a thing or two, it was a lot of lines changed. I tested some 'sensitive' stuff like teshari sprites, and fixed up a few backpack state names while I was in there, and merged some of their needlessly separate files.

### CODE REVIEW

**Comment by Verkister** [comment]
icons/obj/clothing/species/teshari/suits.dmi
icons/mob/species/teshari/uniform.dmi
icons/mob/species/teshari/teshari_cloak.dmi
icons/mob/species/teshari/deptjacket.dmi
icons/mob/spacesuit.dmi

**Comment by Darlantanis** [comment]
so like a bunch of these .dmi's were modified on this branch but seem to be outright removed upstream on master. Am I missing something?

**Comment by Darlantanis** [comment]
oh it's just github having an aneurysm

**Comment by CHOMPStation2** [comment]
I need to test this because I am betting it will break nullsuits and maybe some others

**Pull request merged**
