### PR TITLE
Get rid of auto transfer vote

### PR DESCRIPTION
**Pull request by cadyn**
Comments out auto transfer vote lines (with Chompedit tags)

I think we can all agree, that it's time for autotransfer votes to go. Most of the time when autotransfer votes are successful, it's just bored people ruining other people's scenes. Shuttle can still be called early ofcourse by admins, but these just have to go imo, the amount of scenes this has destroyed by now is really unacceptable.

### CODE REVIEW

**Comment by LunarFleet** [comment]
Fucking praise

**Comment by T-E-R-A** [comment]
You got my vote.

**Comment by LunarFleet** [comment]
Just click the thumbs up under his post, robo-boy

**Comment by LunarFleet** [comment]
This has 5 yes votes to 1 no vote on the github, and 11 yes votes to 4 no votes on the discord. Unga unga merge PR unga unga.

**Comment by Darlantanis** [comment]
This is much too major of a change to pass with a github/#ss13-development vote. As per staff discussion this will require a formal vote in #ss13-announcements with 70% majority support.

**Comment by Razgriz1032** [comment]
I am going to close this PR. There's a much simpler way of changing the vote than editing 3 files, plus we need to consider the results of the poll.

**Pull request closed without merging**
