### PR TITLE
Allow Crowbaring Depowered Windoors [First PR]

### PR DESCRIPTION
**Pull request by Karaum**
Windoors can now be crowbarred when without power.
Windoors can no longer be opened when depowered, even with valid ID.

This change is to bring them similar to how Airlocks operate

### CODE REVIEW

**Comment by Karaum** [comment]
> Please block-comment large chompedits at the start/end with //ChompEDIT START //ChompEDIT END to more easily see the full edited block.

Done on Line 218 to 255 of windowdoor.dm

**Comment by Raeschen** [comment]
Tested this locally and it seems to be broken. Windoors get stuck open when powered and can be crowbarred open immediately (after opening).

Please ensure you test this locally (in all cases of operation) before PRing.

**Review by Raeschen — CHANGES_REQUESTED** [review]
Test locally and fix bugs

**Comment by Raeschen** [comment]
Closing due to no response. Feel free to reopen if you still want to work on this.

**Pull request closed without merging**
