### PR TITLE
Point defense control no longer named deluxe microwave

### PR DESCRIPTION
**Pull request by cadyn**

### CODE REVIEW

**Comment by cadyn** [comment]
Closes #537

**Comment by Darlantanis** [comment]
Have you submitted this fix upstream? If not it'll need a CHOMPedit comment.

**Comment by cadyn** [comment]
> Have you submitted this fix upstream? If not it'll need a CHOMPedit comment.

I checked the upstream and this isn't a problem. I'm not even sure why this is exclusively a problem for us, to be honest.

**Comment by Darlantanis** [comment]
What about YW?

**Comment by cadyn** [comment]
> What about YW?

https://github.com/Yawn-Wider/YWPolarisVore/pull/1002

**Comment by cadyn** [comment]
This should be ready to merge now that all upstream are consistent with it.

**Pull request merged**
