### PR TITLE
Remove hand tele 5% chance to space

### PR DESCRIPTION
**Pull request by Raeschen**
Hand tele is supposed to be a reasonably powerful sensitive item for heads.

Removes the 5% chance to just space you

### CODE REVIEW

**Comment by Razgriz1032** [comment]
No. This doesn't make sense to make it perfect because it is a hand teleporter, not like a full teleportation station or a big quantum teleporter. Hand tele is also a special contraband item. The 5% makes sense as a risk factor.

**Comment by Raeschen** [comment]
> No. This doesn't make sense to make it perfect because it is a hand teleporter, not like a full teleportation station or a big quantum teleporter. Hand tele is also a special contraband item. The 5% makes sense as a risk factor.

changed it to instead do the same action as the "None (Dangerous)" option instead of teleporting you to a random pos on the space Z layer.

None (dangerous) places you in a random space 10 tiles from origin. The '10 tile' can be increased for more risk if you'd like, or i can yet make it even more riskier.

**Comment by Darlantanis** [comment]
Not sure why the hand tele even has a fail chance, it's an annoyance feature not present in other servers. At the very least it shouldn't proc when the destination is a vore belly.

**Comment by Raeschen** [comment]
> 

That's... why i wanted to remove it but Raz said no!

**Pull request merged**
