### PR TITLE
Support for silicons displaying more than one voresprite

### PR DESCRIPTION
**Pull request by ReoDaProtovali**
## About The Pull Request

I completely reworked the code that determined how voresprites were overlayed onto borgs, as they previously didn't support multiple belly sizes or more than one vore belly. Now silicons can have multiple bellies, though the default should be named "sleeper", as naming it that indicates that it should interact with the borg's vore sleeper equipment... This does have the side-effect of not being cross compatable with other vore bellies which are set to use the "Stomach" sprite to determine vore sprite, but it'd only require manually setting the sprite to affect, though I could change the system to use "stomach" as the default, if people really want. Though this would require renaming all the borg's icon states again. Also, if any borgs were missed in the naming convention change, please let me know so I can fix that!

## Changelog

:cl:
add: Added support for multiple borg bellies and associated vore sprites
fix: Supposedly fixed a few of chomp's MEKA borg sprites which weren't touched in the Virgo dogborg removal
code_imp: Completely redid how borg's bellies are shown. old format of "[sprite name]-sleeper" should now be "[sprite name]-[belly name]-[level of fullness]"
/:cl:

### CODE REVIEW

**Review by Raeschen — COMMENTED** [review]
Please //ChompEDIT mark each line or indicate a block with;
//ChompEDIT START
...
//ChompEDIT END

**Review by Raeschen — CHANGES_REQUESTED** [review]
1. Upstream sprite files shouldn't be touched. They don't delta well / you can't "//ChompEDIT" comment a sprite file.
2. Support for the old method as a fallback would be good, incase upstream adds new borgs.

**Comment by Darlantanis** [comment]
Has this been fully added by the upstream mirror?

**Comment by Kashargul** [comment]
> Has this been fully added by the upstream mirror?

It has not, but do not merge as it is. It still lacks an entire section. Leave it open for now (Tag it with do not merge). Talked with Reo and will likely pull it over to the borg fixes branch I'm currently working on. 

Also talked with him that the original Virgo borgs should not be touched, so that they run through a fallback method to prevent issues in case upstream adds new borgs.

**Comment by Verkister** [comment]
Any news on this? Kinda getting all sick and tired of the upstream code still only allowing a belly sprite to show on the currently selected belly and deleting the bulge the moment you select a different vorgan.

**Comment by Kashargul** [comment]
It's all ready, I'm only waiting on 2 other PRs to be merged right now. You can take a look here:
https://github.com/CHOMPStation2/CHOMPStation2/compare/master...Kashargul:CHOMPStation2:reosborgmultibellyWorkingBranch

**Pull request closed without merging**
