### PR TITLE
If the fixes the lag I will cry

### PR DESCRIPTION
**Pull request by cadyn**
If this fixes it I'm gonna cry. This is undoing a tiny change I made ages ago that was supposed to make this run faster, and has no reason to cause problems, but BYOND will be BYOND.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
We'll merge this in 2 rounds. Next round will be a Byond rollback.

**Comment by cadyn** [comment]
> We'll merge this in 2 rounds. Next round will be a Byond rollback.

nah let's do shotgun changes fuck the scientific method

**Comment by cadyn** [comment]
> > We'll merge this in 2 rounds. Next round will be a Byond rollback.
> 
> nah let's do shotgun changes fuck the scientific method

That and I have some serious doubts as to whether a BYOND rollback will help

**Comment by Razgriz1032** [comment]
Byond rollback did not change anything. Merging.

**Pull request merged**
