### PR TITLE
SM Lighter Rework, Loadout Addition, and Experimental Lighter 

### PR DESCRIPTION
**Pull request by FoxglovePurpur**
This commit is my personal largest attempt at coding- anything. If there's bugs, please say so to me (foxglovepur) whenever you have the chance! However...

- Changes the safesmzippo and syndismzippo to simply smzippo parents, making the safesmzippo the "base" "supermatter/lighter" (Seeing as it will forever be the most basic one on feedback (use), I thought it or syndi would be the safest ones to make parent.
- Adds safe and syndi smzippos to the loadout menu using a "Supermatter Lighter Selection" prompt on the character prefs screen. 
- Ensures the Experimental SM Lighter will [b]NOT[/b] be shown on the loadout.
- Added a comment of both SM Lighters outside of the selection prompt in case we want an easy way to change it back to just one or the other in the future.
- Makes the chance of you fumbling a straight 5% on both loadout lighters.

[u]The rest is all related to the Experimental Supermatter Zippo Lighter[/u]

When opening/lighting the expsm zippo a random number between 1 and 100 will be chosen... based on that result...

[01 - 22](https://streamable.com/asewia)
[23 - 33](https://streamable.com/5udoqy)
[34 - 44](https://streamable.com/10u3xh)
[45 - 55](https://streamable.com/xftwgh)
[56 - 66](https://streamable.com/76wsn6)
[67 - 77](https://streamable.com/wdnvtb)
[78 - 88](https://streamable.com/z1cfan)
[89 - 99](https://streamable.com/xshah4)
[100](https://streamable.com/xrspty)

- As of right now, this lighter has no additional benefits and is simply an all-negative "Dare Button", eventually it will be given attack values and a "grenade" mechanic when thrown (while lit). Think "delamination grenade" :)

In the future all three SM Lighters will deal a SMALL amount of damage but ignore armour. The Experimental SM lighter will be given mechanics to "overheat" if left open too long (in player hands) and will shatter if left open (not in player hands). The Experimental SM lighter will be event/admin/POI spawn only. Unless something changes, another alternative is adding it as an illegal high price order from Cargonia. :3

### CODE REVIEW

**Comment by FoxglovePurpur** [comment]
One moment, I am fixing. I forgot a closing tag.

**Comment by FoxglovePurpur** [comment]
Luckily it looks like 
> ## UNIT_TEST: !! FAILURE !! [MAP: Active edges (all maps)]: Maps contained 1 active edges at round-start.
is the only "issue", which... isn't really an issue that this PR causes, touches, changes, or fixes.

**Comment by Raeschen** [comment]
could you detail carefully what all "freely available (non adminspawn only" objects are and what they do?

I see the diceroll list but a text summary helps too, i don't want to be forced to extrapolate functionality by watching videos.

**Comment by FoxglovePurpur** [comment]
Like in game or in comments? And only the experimental is admin only. The other ones are loadout items.

**Comment by FoxglovePurpur** [comment]
- Hardlight Supermatter Zippo is the safest SM Zippo. If you "fumble" it, you get a tiny shock and that's basically it.
- Phoron Supermatter Zippo is safe for station use but its effects are worse, at least on the pain side of things as fumbling it can cause a stun and if you have low health already can crit you. Though neither should really be capable of killing, just like the base cheap lighters. These are just "a tiny bit more dangerous".

- The EXPERIMENTAL SM LIGHTER is ADMIN ONLY (for use in events and special POIs atm only)
> You have a 22/100 change to use it safely. All effects give a small amount of radiation (1 irradiate, it's literally nothing and goes away basically instantly). 
> You have a 1/10 chance to burn and shock yourself.
> You have a 1/10 chance to major burn yourself.
> You have a 1/10 chance to emag/EMP yourself.
> You have a 1/10 chance to dust your hand.
> You have a 1/10 chance to burn and tox yourself, as well as putting yourself in a fake crit state due to pain and stutter procs.
> You have a 1/10 chance to pinch yourself, dealing a "pain" damage of, basically nothing. But this does do one point of genetic damage. Again, shouldn't really do anything.
You have a 1/10 chance to look at the supermatter, causing you go to weak, get put into a blind state for a second. Nothing actually lethal though, and you'll get up soon after. (I also had to fix an issue, I accidentally typed 505 agony, not 50 agony, at least when you're holding it in y our left hand. Oops.
> Finally,  you have a 1/100 chance to heavily irradiate the area you're in and insta dust yourself, just as if you touched the station's supermatter crystal.

**Pull request merged**
