### PR TITLE
Ballistics v4

### PR DESCRIPTION
**Pull request by cadyn**
The time has come for another ballistics update my children!

This time we actually got a metric fuckton of guns thanks to our boy serdy! go give 'em hugs and stuff. Serdy was super helpful, gave me all these sprites, gave me names and descriptions for all of them, and helped point me in the direction for putting their own WKHM guns in the game (The new WKHM brand is their own little lore-piece!)

In addition to this, I've managed to get bolt action guns actually working (mostly) on this, there's a still weird sort-of bug thing that I need to fix with them and a little thing I want to tweak later but I need to just get this PR out there since I've been working on it for 16 hours straight now.

Oh yeah, in addition to those things I added even more stuff: Simple_mobs now have proper ballistic variables set-up, you should find that certain simple mobs interact differently with bullets now. The changes were mostly buffing the effectiveness against simple_mobs, since they don't have organs the bullets can work with.

IN ADDITION TO ALL THAT I have devised the almighty widelist (insert wide putin meme here) to hopefully save memory, pretty much it uses MD5 hashing to make sure each unique list is only stored once in memory and only referenced from other objects, I used this on my ballistics variables, but it should work with whatever else too, although it only works with primitives right now. If you try to feed it a datum inside of a list, it will definitely break.

OH YEAH ALSO THANKS A TON TO CMDR YOUTH FOR HELPING ME TEST STUFF. Was exhausted by the time I got done with code, so having some company to assist me with the testing was just what I needed to get through the rest of it.

### CODE REVIEW

**Comment by Zeldazackman** [comment]
Serd a nerd, but they make amazing sprites

**Comment by Razgriz1032** [comment]
This shotgun is huge
image
https://www.youtube.com/watch?v=EzwbcVbE9rw&ab_channel=Field%26Stream


It is voreing my HUD.
image

**Comment by cadyn** [comment]
> This shotgun is huge
> image
> https://www.youtube.com/watch?v=EzwbcVbE9rw&ab_channel=Field%26Stream
> 
> It is voreing my HUD.
> image

fixed hud vore, now have diagonal icons when in hud

**Comment by Razgriz1032** [comment]
Test merge refreshed.

**Comment by Razgriz1032** [comment]
Test merge refreshed.

**Pull request merged**
