### PR TITLE
Ports the animal clinic from tgstation as a superimposed pod

### PR DESCRIPTION
**Pull request by tacoguy7765093**
TLDR: Low tech hospital with very limited resources.

The animal hospital from tgstation has been remade from scratch for our codebase, complete with LESS stuff then a medbay would normally have, you will have to make do with your limited resources to help people. 

With very limited amounts of health scanners, you have to make due with using stethoscopes, penlights, grab-examines, and more.
dreamseeker_tpYPSoVrxA

Tried to follow superpose guidelines to my best, all variable change documentation sent to Kassc.

### CODE REVIEW

**Comment by tacoguy7765093** [comment]
[animal_hospital.txt](https://github.com/CHOMPStation2/CHOMPStation2/files/9639150/animal_hospital.txt)

Variables and weapon loctations here

**Comment by tacoguy7765093** [comment]
Also that file change for the teshari hats is something I cant manage to get rid of, its already merged on live already so it shouldnt affect anything, but if you can help me remove it please tell me how.

**Comment by Kazzc** [comment]
-Could use more windows by the long hall
-Could use some emergency shutters
-Could slap some folders by the front desk.
-Could use more decals/furniture.
-Could use more wall mount items. Fire extinguishers, 1 or 2 entertainment screens, wall nano-meds, posters, wall lockers, no smoking sign, etc.

Besides these suggestions. . . Pretty good map.

**Comment by tacoguy7765093** [comment]
Is direct port of existing map, I'll add windows and stuff soon

**Pull request merged**
