### PR TITLE
(WIP) null rod rework aka "Why is he buffing himself?"

### PR DESCRIPTION
**Pull request by KeRSedChaplain**
Makes the null rod function the way it does on TG code, letting chaplains pick from a selection of holy weapons.

### CODE REVIEW

**Comment by KeRSedChaplain** [comment]
think I need pointed in the right direction about what to do about the defines and is_holy mind status thing, I'm wanting the PR to be mostly contained to the modularity folder but I don't think those will work without being in the main server folder

**Comment by Darlantanis** [comment]
Not sure this fits our server, this is much more fitting for an LRP/gameplay-focused community.

**Comment by KeRSedChaplain** [comment]
For the most part this is as a prelude PR to reworking the occult mobs and porting over various things related to the clockwork cult mode (but not the full mode just to be clear), to have some more variety in gateway maps and the more gameplay-focused events when they get voted on.

**Comment by VictorZisthus** [comment]
I'm all for this~

**Comment by KeRSedChaplain** [comment]
there we go I was wondering why it said nothing was wrong here but also wouldn't compile

**Comment by Darlantanis** [comment]
After further thought, this is a firm "no" by me. This is too much of a nonsensical LRP feature to fit the purpose of this server, nevermind the drama which will follow a chaplain brandishing a claymore.

**Comment by KeRSedChaplain** [comment]
Lame but now I have an excuse to do all the things with the clockwork cult mobs/gateway/POIs sooner rather than later I guess

**Pull request closed without merging**
