### PR TITLE
Misc loadout clothing additions

### PR DESCRIPTION
**Pull request by RinPin**
## About The Pull Request
adds a few new clothes to the loadout
A new cyberpunk jacket reskin
a new pair of jeans
two new duty gloves reskins

## Changelog

:cl:

add: adds a few new clothes to the loadout.

/:cl:

### CODE REVIEW

**Comment by Raeschen** [comment]
Clothing with armor values in the loadout?

No.

**Review by Raeschen — CHANGES_REQUESTED** [review]
Loadout items cannot have armor values

**Comment by RinPin** [comment]
But we have items in the loadout that have armor? These are a child of said items, the duty gloves and the cyberpunk vest both have armor and both are avaliable in the loadout for 2 - 3 points each, though the armor itself is negligible

**Comment by Raeschen** [comment]
Are they job-specific? It can be ok if job-specific. If not, we need to review them and possibly change them.

You also haven't //ChompEDIT commented chomp-specific code in upstream files.

**Comment by RinPin** [comment]
The items in question aren't job specific, anyone can grab the cyberpunk jacket and duty gloves from the loadout, which makes me confused as to what the issue is, since my PR is effectively just reskins of thoses.
as for the chomp specific edits, i'm unaware of what those would be, these are just a child of the original base item.

**Comment by Raeschen** [comment]
See https://github.com/CHOMPStation2/CHOMPStation2/blob/master/.github/CONTRIBUTING.md

**Comment by Raeschen** [comment]
> The items in question aren't job specific, anyone can grab the cyberpunk jacket and duty gloves from the loadout, which makes me confused as to what the issue is, since my PR is effectively just reskins of thoses. as for the chomp specific edits, i'm unaware of what those would be, these are just a child of the original base item.

Just because items currently exist that have armor, doesn't make it ok for you to add more. We'll deal with these in time. For now, this won't be accepted until the items are made non-mechanically advantageous, and that Chomp-EDIT specific code tagging practices are used.

**Comment by RinPin** [comment]
Does any of that applies to this? the chomp edit things,  could you explain to me what exactly here warrants the comment, since the base items already have it?

**Comment by RinPin** [comment]
they should be cosmetic only now, and i hope the comments are what was asked for.

**Review by Raeschen — CHANGES_REQUESTED** [review]
Editing upstream sprite files is also not really preferred. This kind of change is probably something that should be done in modular_chomp, since edits of the same already exist there.

**Pull request closed without merging**
