### PR TITLE
Makes Winged Flight a Neutral Trait

### PR DESCRIPTION
**Pull request by FoxglovePurpur**
We aren't DELTA airlines, let us fly for free. /j

- Commented out Positive Trait Winged Flight 0 point 1 trait
- Added in Neutral Trait Winged Flight 0 point 0 trait

### CODE REVIEW

**Comment by Aroliacue** [comment]
Sexy update

**Comment by Raeschen** [comment]
maybe do the same to the xenochimera flight trait too, that's the same i think

**Comment by Kazzc** [comment]
Flight has mechanical advantages, don't change the cost.

**Comment by FluffMedic** [comment]
The mechanical advantages are so slim though.
You fly over like 5 things, and all five of those things are rare to some extent.

**Comment by Aroliacue** [comment]
Most locations don't get much use out of flight as-is, and the benefits of using it for an advantage also come with negatives (flying into any solid object will knock you over, more nutrition use, can't cross water or lava tiles any faster than usual unless there's an open z-level above you). There's also vore options for flight, which is handy for scening or accidental vore as it triggers on bump with no extra steps. It's also restricted to wings, and while you can equip any accessory in the 'wings' tab to gain those effects, it's still easy to tell who really shouldn't be flying, and who should.

I think that in its current state, flight is absolutely just a flavour trait and should be relegated to the neutral trait category. If it could allow you to pass lava and water tiles or didn't cause you to get stunned by moving into any dense turf, I'd consider it a positive.

**Comment by FoxglovePurpur** [comment]
Flight has a technical positive impact in the same a lot of the neutrals do I feel. Seeing as how flight is something rarely used for "robust gameplay", and is often more used as an excuse for funny scenes and such, I feel as though it should be an option of "if you have a character with wings, you should be able to use them".
This is an MRP vore server and a lot of folk seemed to be excited about this chance on Discord (and the few here), is there any way I could add a limitation to the neutral version that'd make you okay with having it for the fun of players?

**Comment by Raeschen** [comment]
i think i agree with kassc. I see it being used in explo for certain advantages at times. i'd err on the side of keep posi/one-cost, buut i'm not holding a huge opinion on it.

**Comment by SpadesNeil** [comment]
I can nyoom over all danger in the wilderness because there is a little known flight level above it.

But even so, I think it would be nice to have it be made free. I can't get _indoors_ to anyplace using flight trait, although it would be super nice if POIs had a second Z level to play with.

**Comment by Raeschen** [comment]
negative feedback from heads, so this one's a no i guess

**Comment by SpadesNeil** [comment]
Eh it's probably for the best.

**Pull request closed without merging**
