### PR TITLE
NSB Forbearance [New Station Map] (Serdy made this)

### PR DESCRIPTION
**Pull request by Rykka-Stormheart**
Welcome to a project Serdy has been hard at work on for several months!

The NSB Forbearance. A station on the moon Thor, in the vicinity of Sif (this lore is still WIP, so just assume moon for now).

Three PRIMARY station levels:
Ground Floor. This houses Medical, Engineering, Research, etc. Dorms are to the SOUTH, now named Apartments. Venture beyond the fence carefully, and don't piss off the local wildlife.
Underground. This area has hostile mobs outside the warning-marked signage. Xenobiology, the cold room, Red Armory, etc can be found here.
Upper Levels - R-UST, TComms, Solars, Xenobotany, Exploration reside on this level.

I'd have made an entire album of screenshots, but most folks interested in reading this anyhow have already been faithfully helping Serdy + I test this out.

Thank you to all the patience you've shown us in fixing teething issues with the map.
As always, [feedback can still be left here](https://docs.google.com/document/d/1VxwbtZzswNqCy4oZ7TmMbRtRe03m7KqMnVpMBqlf2VQ/edit?usp=sharing), or **on this PR (preferred)** and we hope you enjoy the map.

As a reminder, **Serdy made the map. I just helped bugfix + adjust things so it worked.**

### CODE REVIEW

**Comment by Holdelta** [comment]
As your casual Civilian Botany enjoyer, the improvements from the test to live are greatly appreciated.  Details that still need to be addressed:
- No sink to refill on water on either level of Hydroponics
- No roundstart buckets/only one backpack water tank from the vendor
- No Bee crates to produce honey

The only opinion that I'll drop is that the main "advantage" of Civilian Botany versus Xenobotany(Sci variation) is that most Civilian departments are open to be seen in public for ease of talking with people while working through transparent windows.  The main loop of normal Botany(plant and grow) is in a very secluded part that basically functions as Xenobotany without the fun tools that come with Science.  If this is on purpose, that's fine, but this is the main reason why I play normal Botany.

**Comment by R3dtail** [comment]
https://puu.sh/IUcnB/6b7905b81e.png This little area significantly dampens the flow of security .  Ladders are...more cumbersome to use than stairs.  Swapping the ladder to the briefing room and the staircase to the firing range would vastly improve the flow of the department compared to how it is now.    Also, security is the one department without its own cyborg recharging stationfor synthetic players or cyborgs to recharge in.  Additionally, the warden's office lacking their own personal recharger is kind of meh.    Lack of wall chargers in the armoury also feels like a bit of a downgrade, which sure is admittedly balanced out by the 11 rechargers spread out across the department.  https://puu.sh/IUcvH/5dcbdf89aa.png Here would make an excellent location for two rechargers in the armoury for emergency situations.  


https://puu.sh/IUcpn/473838b349.png  Also, might want to consider the disposal unit here, as funny as it would be for security players to accidentally  dump their guns in the trash, I can imagine it leading to frustrations...considering there's a disposal unit literally 11 tiles to the right, this feels like a bitm ore crowded than necessary.  

The fact that processing and the cells themselves are now on completely opposite ends of the department feel really...peculiar , too.   It made more sense when they were close by eachother to improve flow considering it would be moving in a steady direction, instead of having to criss cross across the entire department on the off chance someone needed to be brigged.  The previous design flowed significantly better and made significantly more sense design wise.  How it is now does nothing but break up the  normal footwork of the department in an exceedingly poor manner.

**Comment by Enzo-Leon** [comment]
Science needs a few more blue toolboxes, at least 1 or 2 for robotics along with a yellow toolbox for wires. Xenobio  needs to have the slimes be slime cores round start to keep from waste and a random new player getting owned.

**Comment by LordSaladin** [comment]
weh

**Comment by Pixydidnothingwrong** [comment]
Next test merge when?

**Pull request closed without merging**
