### PR TITLE
Clear Skies Ahead!

### PR DESCRIPTION
**Pull request by ExabyteDiscord**
Clears up a hell of a lot of clutter with all of the pre-defined areas of shuttles to properly use the landmarks system. Now there's a ton of free room to build and/or allow larger shuttles to dock with the station, as well as allowing overmap shuttles to dock at the docks.

### CODE REVIEW

**Comment by ExabyteDiscord** [comment]
Well, travis gave me a different error this time. **Progress.**

**Comment by ExabyteDiscord** [comment]
This is finished and in a working state, but could use a bit of final touch ups. Not entirely necessary though.

**Comment by Darlantanis** [comment]
You need CHOMPedit comments on any non-ch files.

**Comment by ExabyteDiscord** [comment]
Last 2 commits add the needed edits to non-map files and non-CH files, then fixes at least one access issue, and adds compact cataloguers to pilot/FM lockers, plus the pathfinder variant to the pathfinder's locker. Also fixes the cryogenics windoors, because why not.

**Pull request merged**
