### PR TITLE
Frontier Weapon Removal

### PR DESCRIPTION
**Pull request by VictorZisthus**
Limited ammo time, oh no.

**ALSO CONTAINS:**
Bugfix for Checkpoint flasher and doors.

Bugfix for cash registers.

Added privacy shutters and tint controls for warden, moves APC to accommodate new buttons.

### CODE REVIEW

**Comment by VictorZisthus** [comment]
To clarify, this is just removing round-start placements. The guns still exist in the game.

**Comment by CMDRYouth** [comment]
After this, Explorers are going to have to Catalogue things now to get Frontier weapons from their vendors, or have them printed at Science.

**Comment by VictorZisthus** [comment]
Oh right, this is working off of stuff for #5579 as well.

**Comment by CMDRYouth** [comment]
It’s probably more likely that Explorers will just start using Ballistics after Frontiers stop being commonly available.
Hopefully all the inevitable bullet casings and empty magazines everywhere don’t lag up the server.

**Comment by VictorZisthus** [comment]
> It’s probably more likely that Explorers will just start using Ballistics after Frontiers stop being commonly available. Hopefully all the inevitable bullet casings and empty magazines everywhere don’t lag up the server.

I... Should probably port over a casing bag from an old code-base to solve this issue.

**Pull request merged**
