### PR TITLE
Adds Point Defence Turrets

### PR DESCRIPTION
**Pull request by Shadow-Quill**
There are a few gaps in the protection, but they'd need a precise hit to take them out.

The PD Control Mainframe is in the AI's side room (with the messaging server & blackbox)
image

Currently uses 5 KW from the Equipment channel for that APC. If the APC is turn off, or the equipment channel loses power, all turrets will stop working.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
I will need to test their functionality tomorrow

**Comment by Shadow-Quill** [comment]
Rerunning checks

**Comment by Razgriz1032** [comment]
Is point defense control commented out somewhere?

I seem to recall some time at the beginning of chomp 2 that point defense was giving me compile errors and I forget what I did to fix..

**Comment by Razgriz1032** [comment]
Is this good to go?

**Comment by Shadow-Quill** [comment]
> Is this good to go?

Yeah, not sure why Cadyn didn't remove the DNM tag xP

**Pull request merged**
