### PR TITLE
Add cigar cases to the loadout

### PR DESCRIPTION
**Pull request by r4d6**
This add Cigar Cases to the loadout, for when you want more than 1 cigar at the start of the shift. You even have the option between the normal cigars, the cohiban cigars and the havanian cigars.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
This PR is currently unacceptable. These changes need to go into new _ch.dm files and enabled within the .dme

**Comment by r4d6** [comment]
> This PR is currently unacceptable. These changes need to go into new _ch.dm files and enabled within the .dme

What about adding the chomp edits comments ?
And should I create two new _ch file just for one item?

**Comment by r4d6** [comment]
Done, both have been moved to a brand new file, even the four line change.

**Comment by Razgriz1032** [comment]
Needs an updated vorestation.dme.

Activate the files in dream maker, then grab the .dme and upload that too

**Comment by r4d6** [comment]
Done

**Pull request merged**
