### PR TITLE
Hippo Head remake-fix

### PR DESCRIPTION
**Pull request by Hunter-Dovetail**
Thank you so much to Drathek, I cannot thank them enough for their patience and time on sorting out my Gitkraken mess!

This redoes the hippo_head Sprite and code
## Changelog
:cl:
add: hippo_head
/:cl:

### CODE REVIEW

**Comment by Kashargul** [comment]
There's no need for this. The previous PR worked, it will just not be available until the next deployment.

**Comment by Hunter-Dovetail** [comment]
> There's no need for this. The previous PR worked, it will just not be available until the next deployment.

Are you sure? I'm pretty sure the code for it was deleted, until I made this PR

**Comment by Kashargul** [comment]
> > There's no need for this. The previous PR worked, it will just not be available until the next deployment.
> 
> Are you sure? I'm pretty sure the code for it was deleted, until I made this PR

No, I moved it to the right place and out of the xeno section.

**Comment by Hunter-Dovetail** [comment]
> > > There's no need for this. The previous PR worked, it will just not be available until the next deployment.
> > 
> > 
> > Are you sure? I'm pretty sure the code for it was deleted, until I made this PR
> 
> No, I moved it to the right place and out of the xeno section.

Ahh okay! Thank you very much! Well, this was still a great lesson from Drathek anyway, Thanks for moving it!

**Comment by Hunter-Dovetail** [comment]
> > > There's no need for this. The previous PR worked, it will just not be available until the next deployment.
> > 
> > 
> > Are you sure? I'm pretty sure the code for it was deleted, until I made this PR
> 
> No, I moved it to the right place and out of the xeno section.

Could you possible let me know where you moved it to? So I know where the right place to put code is, for future reference?

**Comment by Kashargul** [comment]
> > > > There's no need for this. The previous PR worked, it will just not be available until the next deployment.
> > > 
> > > 
> > > Are you sure? I'm pretty sure the code for it was deleted, until I made this PR
> > 
> > 
> > No, I moved it to the right place and out of the xeno section.
> 
> Could you possible let me know where you moved it to? So I know where the right place to put code is, for future reference?
https://github.com/CHOMPStation2/CHOMPStation2/blob/e1221476ab9457a99ea5ade3f428510c4f74d6a2/modular_chomp/code/modules/mob/new_player/sprite_accessories_extra.dm#L217-L221

**Comment by Hunter-Dovetail** [comment]
> > > > > There's no need for this. The previous PR worked, it will just not be available until the next deployment.
> > > > 
> > > > 
> > > > Are you sure? I'm pretty sure the code for it was deleted, until I made this PR
> > > 
> > > 
> > > No, I moved it to the right place and out of the xeno section.
> > 
> > 
> > Could you possible let me know where you moved it to? So I know where the right place to put code is, for future reference?
> > https://github.com/CHOMPStation2/CHOMPStation2/blob/e1221476ab9457a99ea5ade3f428510c4f74d6a2/modular_chomp/code/modules/mob/new_player/sprite_accessories_extra.dm#L217-L221

Thank you very much!

**Pull request closed without merging**
