### PR TITLE
This should fix everything.

### PR DESCRIPTION
**Pull request by cadyn**
Stopped getting any runtime errors or performance issues after making these changes.

Please don't actually merge this lol

### CODE REVIEW

**Comment by LunarFleet** [comment]
I have never so whole heartedly supported a PR. If this doesn't get merged, I'm rioting.

**Comment by Darlantanis** [comment]
CONFLICTS

**Review by Shadow-Quill — APPROVED** [review]
LGTM. We can finally nuke the issues section once this is merged.

**Comment by Razgriz1032** [comment]
LGTM

**Comment by Sharkmare** [comment]
image

**Comment by LordSaladin** [comment]
honk

**Comment by Little-119** [comment]
code can't have bugs if there is no code

**Comment by VictorZisthus** [comment]
Brilliant. Genius, even!

The bugs are no more.

**Comment by Raeschen** [comment]
The meme lived a long time, but due to how procariously close to the top TGS places this in the TM list, i sadly gotta close it. Don't wanna misclick and kill the serb

**Pull request closed without merging**
