### PR TITLE
New Event

### PR DESCRIPTION
**Pull request by FluffMedic**
-Adds a new event
-Adds 3 new mobs similiar to solar moth, tied with the event. -The weight of the event is -60, getting +15 per engi, +5 per sci, and +1 per person.
-Changes our event container to Event_Container_CH and disabled the VR due to conflicts.

## About The Pull Request

-Adds a new event
-Adds 3 new mobs similiar to solar moth, tied with the event. -The weight of the event is -60, getting +15 per engi, +5 per sci, and +1 per person.

Solar Ray - Firey thing, half the heat of solar moth. Dies to spray bottle
Living Ice - Frosty, dies to warmth and lasers
Radiation Crab - Kick it

## Changelog

:cl:
-adds: a new event
-adds: 3 new mobs similiar to solar moth, tied with the event
-adds: Event_container_CH, disabled the VR version
/:cl:

### CODE REVIEW

**Comment by CMDRYouth** [comment]
I like how you detailed the exact ways these creatures are killed, predicting how much people would whine about them otherwise.

**Comment by FluffMedic** [comment]
Okay this headache is for tomorrow morning.

**Comment by Aroliacue** [comment]
Make sure to edit and correct the Changelog

**Comment by FluffMedic** [comment]
BYOND I went onto the live server and copy and pasted the area zone.
Why are you telling me it's wrong?
Because I am guessing that is the issue.

**Pull request merged**
