### PR TITLE
Update automatic nanomap generator

### PR DESCRIPTION
**Pull request by Razgriz1032**
Swapped Tether references for Chompstation references. I hope this works to automatically generate our own nanomaps.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
Apparently we need these four files to actually exist.
code/modules/asset_cache/asset_list_items.dm:500:error: 'icons/_nanomaps/southern_cross_nanomap_z7.png': cannot find file
code/modules/asset_cache/asset_list_items.dm:501:error: 'icons/_nanomaps/southern_cross_nanomap_z8.png': cannot find file
code/modules/asset_cache/asset_list_items.dm:502:error: 'icons/_nanomaps/southern_cross_nanomap_z9.png': cannot find file
code/modules/asset_cache/asset_list_items.dm:504:error: 'icons/_nanomaps/southern_cross_nanomap_z11.png': cannot find file

**Comment by Darlantanis** [comment]
y tho

**Comment by Razgriz1032** [comment]
why

**Comment by Razgriz1032** [comment]
Gorgeous Freeman stop

**Comment by Razgriz1032** [comment]
WHAT CONFLICT. THERE LITERALLY IS NO FILE NAMED THAT. IT'S COMPLETELY FUCKING NEW. FUCK YOU AND YOUR COW.

**Comment by Razgriz1032** [comment]
NOW THAT I HAVE MADE A NEW PR IN https://github.com/CHOMPStation2/CHOMPStation2/pull/1703, YOU ARE SUDDENLY OK WITH Z10. FUCK OFF YOU MOIST BINT

**Pull request closed without merging**
