### PR TITLE
Makes masks use their original, opaque sprite and properly implements polaris clear gasmask subtypes

### PR DESCRIPTION
**Pull request by ReoDaProtovali**
## About The Pull Request
Holy shit this started out as a simple Icon change and quickly grew to a much larger thing beyond that. Makes normal gas masks `obj/item/clothing/mask/gas` use the original gasmask icon. Also makes it opaque to reflect this. Since the clear sprite was removed from the original gas mask, I also went to re-implement the polaris upport of virgo's clear mask, which they did as a subtype and they did it properly. I have gone through a few objects that originally used gasmasks and have given them either normal or clear gas masks, and added clear gas masks to loot tables that should have both. Notably: Biohazard lockers and supply crates now have clear masks. I was going to have fire closets be 50/50, but im not going to implement a new randomizer item unless there's a lot of push for that. Until then, this PR should be mostly complete unless I missed something. Please notify me if something's fucked because it's most likely unintentional. 

Also moves mask icons into modular_chomp because virgo changed icon_state names and I had to change it back to not have an otherwise disgusting work around. Oops.
## Changelog
:cl:
add: Properly implemented clear gas masks
add: Readded the original gasmask icon
add: added both clear and not clear gasmasks to loadout for 3 points. Happy tiding!
add: replaced the normal gas masks in biohazard lockers with clear ones
add: secretly adds on-mob icons for mouth-held grenades for teshari because I was bored
del: Removed the `obj/item/clothing/mask/gas/wwii` subtype of the mask since the base subtype fills it's role. 
qol: Makes greytide AI carbon mobs have a bit more variation.
image: Added all of the mob_vr_mask.dmi and associated species files to the modularity folder
code: Removed the check for base gas masks to remove their face-consealing abilities because they're no longer clear. Subtypes that are clear can now just use the /clear subtype since it's properly in now
/:cl:

### CODE REVIEW

**Comment by Kashargul** [comment]
maps/southern_cross/overmap/planets/thor/thor.dmm:2377:error: undefined type: /obj/item/clothing/mask/gas/wwii

**Comment by ReoDaProtovali** [comment]
augh. I dont know how to change maps, but that's due to the type removal. Could I get some help with that maybe?-

**Comment by Kashargul** [comment]
@tacoguy7765093 something for you to maybe help out with

**Comment by tacoguy7765093** [comment]
I'll finish it by end of the day

**Pull request merged**
