### PR TITLE
fixes char directory gender, sexuality and event tag buttons

### PR DESCRIPTION
**Pull request by Seris02**
somehow I missed that when I fixed it up from the last PR

### CODE REVIEW

**Comment by Darlantanis** [comment]
Does this need an updated bundle?

**Comment by Seris02** [comment]
> Does this need an updated bundle?

uhhh yes but afaik from all the other times I've done prs involving tgui the deployment does it by itself

**Comment by Darlantanis** [comment]
I'm not aware of anything here which will regenerate the bundle on master. TGUI .js tweaks typically need to come with an updated bundle.

**Comment by Seris02** [comment]
could merge it without the bundle update just to check anyway, not like it's exactly an urgent thing, can be done with an updated bundle in whichever PR does it afterwards if it actually doesn't

...but again as far as I've seen, the prs I've done that touch tgui without touching the bundle work just fine the in the next deployment

**Comment by Razgriz1032** [comment]
Just run the bundle update to be safe.

**Comment by Seris02** [comment]
you guys are right btw, checked it all, there's nothing to auto-update the bundle here, unfortunately it's a tg thing

**Comment by Razgriz1032** [comment]
Master will need to be pulled into this PR's branch and then the bundle will need to be generated.

**Pull request merged**
