### PR TITLE
Yummy bugfixes

### PR DESCRIPTION
**Pull request by cadyn**
Fixes:

- Loneliness people detection issues
- Language number not properly updating
- Phoron bore can get infinite materials from 1 piece of phoron.
- Lights don't work with wearable circuits
- Putting more than 5 items into a candle pack results in missing sprite

### CODE REVIEW

**Comment by Darlantanis** [comment]
Might be better to send the non-CHOMP specific bug fixes upstream.

**Comment by cadyn** [comment]
> Might be better to send the non-CHOMP specific bug fixes upstream.

Probably is better, but I'm a bit pissed at virgo for some of the steaming shit they've sent downstream lately, and not feeling like waiting a week or whatever for a basic PR to get merged, so not really caring for sending these upstream atm tbh.

**Comment by Darlantanis** [comment]
Relatable, though sending fixes upstream can prevent headaches from upstream conflicts later (or upstream implementing a "fix").

**Comment by Razgriz1032** [comment]
Will the phoron bore changes affect or override or change nothing compared to #759

**Comment by cadyn** [comment]
> Will the phoron bore changes affect or override or change nothing compared to #759

Bah, will need manual conflict resolution but it should override it since the stuff Virgo sent us still has the bug it seems

**Comment by cadyn** [comment]
> Relatable, though sending fixes upstream can prevent headaches from upstream conflicts later (or upstream implementing a "fix").

Yea, and I get that, which is why I say that it generally is the better thing to do, but I feel justified with not sending this specific one upstream since most of these fixes are minor things that virgo may not even ever get around to fixing

**Pull request merged**
