### PR TITLE
Unity Hound Module

### PR DESCRIPTION
**Pull request by LunarFleet**
Here we are, two weeks of working and adding onto an old concept, and we are finally here. 
The Unity Hound is a clerical hound, for all intents and purposes. It has all of the clerical borg's tools, plus one extra, a new tool which I made from scratch; the 'task manager'. 

The task manager is a tool which gives a reason to do paperwork. It can best be explained by writing out the process in which it operates.
1. Select a department with the tool
2. Scan 3-9 department related objects (Chem dispensers for medical, ovens for service, etc)
3. When you have scanned the correct amount of objects, some instructions, data, and form will appear in the chat. 
4. Copy the form, write it on a piece of paper, fill out the X's, scan the paper
5. The paper is consumed, and a surplus voucher is printed. 

There are six kinds of surplus voucher, and each one can be printed by the task manager. These departmental based voucher types include; command, engineering, medical, service, security, and science. 

Surplus vouchers are similar to pizza vouchers. You pick one up, click one in your hand, and it will make an item appear. Unlike a pizza voucher, surplus vouchers use teleporter sounds, and choose an item from a list to spawn. These lists have different probabilities for each item in the list.
To give an idea of what the surplus vouchers spawn, here are the three highest probability items from each department, excluding command because I will explain that later.

Engineering; 1. fire extinguisher 2. industrial welder 3. screwdriver (A lot of other basic tools also have the same probability)
Medical; 1. Regular first aid kit 2. Fire first aid kit 3. Toxin first aid kit (Like the ones in the medical storage room, by the medivender)
Science; 1. Monkey cube box 2. Xeno taser 3. Singular sobaka/saru/sparra/wolpin cube
Security; 1. donut box 2. box of spare handcuffs 3. pepper spray
Service; 1. gallon of milk 2. gallon of soymilk 3. Flour

Command vouchers are special, as they are 'reward' vouchers, meant to be given to good employees. The reward voucher gives things like burgers, alcohol, and toys. The reward vouchers are meant to be an RP tool used to encourage good work. 

The purpose of the Unity hound is exactly what the name would suggest; it uses its borg access and reward vouchers to help encourage effective work, reward good employees, and supply departments with small tidbits of extra supplies when needed. _**Note that the task manager has a five minute cooldown on successful uses, preventing one from acquiring immense amounts of low tier supplies with it. This cooldown can be increased if requested.**_

I have spent two weeks sufferin-Imean, sorting this out, getting the tool to work, and piecing it all together. I have tested it a good bit, and it should be safe to merge. I've also tried my best to add // CH edit comments where necessary, following // YW edit examples. If there is anything that needs to be changed, I would be happy to do so.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
Gonna rouse the staff for discussion

**Comment by Razgriz1032** [comment]
Here was some quick notes from Nadyr. I definitely agree with security section.

For engineering,
Really unsure about having RCD/RMS. Those are both pretty powerful and take a buttload of steel or mining materials to make.

For medical,
Surgery kit, combat medkit, and combat pill bottles are definite no's. I'm unsure about allowing medkits period.

For security,
Any guns are a no. I am similarly unsure about any sec weapons and emp/smoke/teargas boxes.

**Comment by LunarFleet** [comment]
Very well, though all of those things had the lowest probability, and the guns were only things you could find in security, NOT including the big armory. Regardless, I will remove what has been requested, though I am going to have many complaints if medkits in general are not acceptable; thoses kits are overall pretty simple, only containing chemicals and injectors that you can make in the chemlab by itself, I don't even think there is anything in them that needs phoron.

**Comment by LunarFleet** [comment]
It has been done, my lords. Though I did add normal weapon cells to the list of things it can spawn for security, cause it can spawn other types of common, non lethal ammo anyway. I did remove all of the guns and all of the grenades, excluding the flashbang box because I don't really know if you meant those too.

**Comment by Darlantanis** [comment]
I am satisfied with the loot pool now. One final tweak I forgot to mention is the borg should not be able to understand Gutter, the point of Gutter is it's a black market language which translators/AI shouldn't be able to translate. I am uncertain why upstream gave the clerical module the ability to understand Gutter.

**Comment by LunarFleet** [comment]
Very well, I simply copied over the languages and such from the clerical borg, as you can probably tell. As you seem to be against the normal clerical module speaking it as well, I'll remove it from that too, and mark it with a // CH edit

**Comment by LunarFleet** [comment]
It has been done, gutter is no more :crab:

**Comment by Razgriz1032** [comment]
Did you add the comments and separate stuff into _ch files like I asked? We're tying to keep things organized and make sure of our changes.

**Comment by LunarFleet** [comment]
I'm stupid and forgot.

**Pull request merged**
