### PR TITLE
adds three new fat synth taurs, fat synthlizards, fat synthfelines, and fat synthwolfs, to the customization menu

### PR DESCRIPTION
**Pull request by KeRSedChaplain**
As it says on the tin. Screenshots will come later. Probably.

### CODE REVIEW

**Comment by Darlantanis** [comment]
Why does this delete two example config files?

**Comment by KeRSedChaplain** [comment]
what the hell why _does_ it delete those

**Comment by KeRSedChaplain** [comment]
those weren't even touched on this branch, it was probably left over commit junk

**Comment by Darlantanis** [comment]
Perhaps github weirdness. It's easy to prompt a gitaneurysm.

**Pull request merged**
