### PR TITLE
Improves botany, Puts library in place of gym, adds art gallery, gym in place of public garden

### PR DESCRIPTION
**Pull request by tacoguy7765093**
This might be a more controversial change as it completely moves entire departments around.

CHANGES: 
Botany is much larger now, gardeners don't have to get crammed in 1 tile walk ways in their dark barely lit botany rooms.

The trays are intentionally placed so people can see every tray from the window and the kitchen, gives the botany a bigger public eye instead of being closed off unlike the rest of the service departments AND allows someone to chef and botany without any plants off screen. 10 trays in sight 

There is now an empty animal pen so when someone orders chickens or cattle, you don't have to put them on the floor or kitchen.

Added a art gallery in place of the library too complete with art supplies and canvases, including painting frames that might be potentially PERSISTANT between shifts

More painting frames around the station might be a separate PR

These changes got in the way of the coffee shop and library so I moved both of those things in the third deck REPLACING the public garden that no one used.

The xenobotany seeds that were there are left unchanged, the center ring already had public dirt piles for plant growing for bored players with equipment.

The library is now in place of the public garden, still complete with a cafe!

Minor mapping change on the large public bathroom is accessible from both the locker room area and the library...

Disposals has their own cargo mailing area now known as "Gallery" along with having the library one re-sorted. Thanks TheGreatKitsune and Kassc!

Why its good for the game?
Service is less depressing and bare-bones then how it currently is, the art gallery gives visitors and players a thing to do when there is down time. Botany is in more public eye to open up for more RP.

EDIT: Better images and most of the issues of the map have been updated are are uploaded as a comment down here!

### CODE REVIEW

**Comment by CMDRYouth** [comment]
I like this.  It’s a well-made map change, and we could use some more of those.  I hope it gets merged.

**Comment by xnqm8h** [comment]
First I think this should be discussed on Discord, perhaps in a threaded conversation managed by the moderators, as GitHub isn't our community center. Also saying that the upstairs garden was never used is disingenuous. I regularly use the deck three garden and have seen quite a few other players using it. It's fairly convenient compared to the central ring gardening area as the plots are closer together. Other than that here are some of my thoughts.

## Library
Close up the hole in the floor. A library wouldn't have a hole opened up
to a gambling area where folks would be loud.

The café should probably have a produce fridge as I can't imagine running
up and down stairs will be fun for any baristas making fruit drinks since
they won't be getting fresh deliveries from botany next door in this layout.

Make the table larger to replace the 2x4 one that would be lost from the
garden hangout.

Can't tell if there is a box of buns in the upstairs café. Should spawn in at
shift start though so they can make bagels.

There is a lot of dead space in this area and could probably benefit from
more things being added.

Add some more greenery. This can kind of tie into the dead space issue.

Disposals would fit better next to the binder/scanner and it's missing a
paper shredder.

The library doesn't need xenobotany seeds.

## Botany
Perhaps instead of making botany bigger and eating the café it should
have been moved downstairs to share space with xenobotany. There was even
construction areas nearby that could have been replaced.

What's the point of the service window to the south? There isn't a café
there anymore.

**Comment by Kazzc** [comment]
It looks alright but you are missing a number of things.
-Missing lots of decals.
-Missing emergency glass shutters under doors.
-Missing emergency shutters under windows.
-Placing Air scrubbers/vent under an APC.
-Library lacks proper walking paths.
-Library missing machines.
-Missing "Emergency Storage". I moved the gear in to maints.
-Coffee shop missing items
-Coffee shutters facing the wrong direction.
-Disposal pipes connects to a wrong loop. Made a new loop, cargo can now send packages to the Bridge conference room, Gym, Library, Cafeteria, Dorms.
-Missing wires under doors.
-Vents/scrubbers under tables/structures.
-Missing disposals in cafeteria .
-Missing sliding door in cafeteria.
-Overlapping wall mounting machines.
-Avoid placing large machines next to windows.
-Repeating security cameras.
-Security cameras `c-tag` not named properly.
-Wires, pipes and disposals going under structures.
-Doors have mislabeled names.
-Misplaced lockers over the tables.
-Missing Entertainment monitors.
-Missing AI monitors.
-Missing Status display.
-Gallery lacks proper walking paths.
-Gallery and Library missing Emergency Closets.
-Missing and wrong directional signs.
-Areas missing lights.
-Gallery missing various items.

**CHANGES**
-Replaced all dorms disposal bins with wall mount disposal.
-Reworked disposals system to loop on the third floor. 
-Added new delivery areas for cargo: Gym, Dorms, Coffee shop and Gallery.
-Added missing directions signs.
-Added more cameras and renamed some misspelled ones.
-Added new decals to the bar
-Added new decals to the second floor bar
-Added new decals to the library
-Added new items to the coffee shop, can now dispense sodi-pops.
-Moved all equipment from the Third deck emergency storage to maints and SMES room.

I got around polishing what you made, hopefully you agree with these changes.

image

image

Besides that. . . hopefully we can get around pushing this and get more traffic in the third deck, and have players have fun with the gallery. (And updated Hydroponics)

**Comment by tacoguy7765093** [comment]
Aaaaand here are the screenshots of Kassc's polish ingame! I am very thankful for Kassc's help with this and I hope this eventually gets merged.

dreamseeker_TUMH85KzCz
dreamseeker_Q9VCzoCLQY

**Comment by tacoguy7765093** [comment]
Those e-cigs cause a runtime on map load, trying to load reagents from /tg/station that dont exist here... who ported these so lazily? Otherwise harmless.

**Comment by tacoguy7765093** [comment]
ALRIGHT, After some discussion we decided the gym was a better place to put in deck 3, now the library is in place of the gym, we did not want the library to be hidden off into the lost void that is deck 3, and now, you do not have to worry about noise entering the library from deck 2.
StrongDMM_v3Kdz3mpTE

StrongDMM_OJC8gbBnkt

And the best part is, people can get themselves some easy protein in the gym now :3

**Comment by Rykka-Stormheart** [comment]
I like this a lot! Only request is if the cafe is going to be that large, can we get some food prep machines or items?
It'd be nice to actually be able to make breakfast food with that much extra space.

**Comment by tacoguy7765093** [comment]
I feel like having the industrial kitchen equipment would be a tad overkill, for both the power grid and the cafe. We do have the microwave for the basic stuff like bagels, and I need to double check if that fridge contains flour and eggs.

**Pull request merged**
