### PR TITLE
[MIRROR] [MIRROR] Teshari name generation fix

### PR DESCRIPTION
**Pull request by CHOMPStationBot**
Original PR: https://github.com/VOREStation/VOREStation/pull/9373
--------------------
Original PR: https://github.com/PolarisSS13/Polaris/pull/7766
--------------------
This makes randomly generated (from pressing random name in character creation) Teshari names have both a pack-name and own name to match with the lore, rather than a singular name.

### CODE REVIEW

**Comment by Darlantanis** [comment]
Is this going to add randomized pack names or draw from the list of 2 which are actually common in space? The single name thing isn't an oversight, tesharii typically omit the pack name because the vast majority of tesharii in space share the same pack name. 

If this is just going to generate a large variety of pack names from the same randomized pool as individual names come from this will be a no as it conflict with lore.

**Comment by Darlantanis** [comment]
Throwing DNM onto here until I get an answer, just in case.

**Comment by Greenjoe12345** [comment]
It generates random names, but this is from Polaris lore where there are more then just two main packs in space and teshari don't ommit their pack name from their name.

**Comment by Greenjoe12345** [comment]
What's the lore for them here, then?

**Comment by Razgriz1032** [comment]
It just gives it a last name and a first name. Current generation only gives it one name.

**Pull request closed without merging**
