### PR TITLE
[MIRROR] [MIRROR] Makes the chaos cake cheaper.

### PR DESCRIPTION
**Pull request by CHOMPStationBot**
Original PR: https://github.com/VOREStation/VOREStation/pull/10648
--------------------
Original PR: https://github.com/PolarisSS13/Polaris/pull/8135
--------------------
People almost never make the thing because of the effort required, but there's a desire from chefs to make it more often.

You still need other departments to help out, but it's much less work now, but still enough effort that it's not just something people can abuse.

I might add other cakes later.
Also hey, new sprites for the slices. Yum.

image

### CODE REVIEW

**Comment by Razgriz1032** [comment]
I say no.

**Comment by Darlantanis** [comment]
Why was this sent upstream in the first place?

**Comment by Razgriz1032** [comment]
Upstream took it from us

**Comment by Darlantanis** [comment]
If we deny it, still take the .dmi so icon conflicts don't happen later.

**Pull request merged**
