### PR TITLE
Modular datums folder and supplypack folder with examples.

### PR DESCRIPTION
**Pull request by LordSaladin**
Adds a datums folder and a supplypack subfolder to the modular folder while moving over the existing medical_ch.dm and adding a munitions one which adds a cowboy crate because serdy bussed me in a colt once and this gives me an excuse to actually clone the repo to my pc and help out with the modularity at the same time.

### CODE REVIEW

**Comment by LordSaladin** [comment]
ree

**Comment by BlackMajor** [comment]
remove the entry added in the .gitignore (why did a removed file need a git ignore) and it's good

**Comment by LordSaladin** [comment]
I'll get to that whenever I next have access to my pc

**Comment by LordSaladin** [comment]
> remove the entry added in the .gitignore (why did a removed file need a git ignore) and it's good

done.

**Comment by Razgriz1032** [comment]
You did not enable the moved medical file in the dme

**Comment by LordSaladin** [comment]
> You did not enable the moved medical file in the dme

fixes

**Pull request merged**
