### PR TITLE
POI balances and SC update.

### PR DESCRIPTION
**Pull request by Kazzc**
SC Floor 1
-Added missing markings and tiles on AI holopads.
SC Floor 2
-Added missing markings and tiles on AI holopads.
-Modified tiles on Server Room to all have the same atmos. Removed Air-alarm inside the server room. (hopefully this stops the Air-alarm from freaking out)
SC Floor 3
-Added missing markings and tiles on AI holopads.
-Removed some OP hidden items in maints.

DeathDen
-Removed SM sheets.
-Added SM Shard.

Demonpool
-Removed Fireball book. (Somehow it's OP now. :T )

Chasm
-Changed the bugged mod.
-Made chasm not as easy to cheese.

Snowfield
-Created small huts and placed spawn points in them, landing on this POI will be a tad safer on landing.

### CODE REVIEW

**Comment by LuciusWorna** [comment]
Aw, getting rid of the locus?

**Comment by r4d6** [comment]
> Aw, getting rid of the locus? I mean, it made no sense being there, but still, lol.

I can't check myself because the map diff bot failed.

**Comment by Kazzc** [comment]
I need help, I don't understand map diff. :cactus:

**Comment by r4d6** [comment]
> I need help, I don't understand map diff. 🌵

Normally the map diff work by highlighting removed and added stuff, but it failed.

**Comment by Kazzc** [comment]
Welp, I fixed it. I am content.

**Pull request merged**
